### ISSUE TITLE
Suggestion: Setting to add gender to clipboard text

### ISSUE THREAD

**Issue by navarr** [farkam135/GoIV#1012]
For those of us focusing on filling out our Pokedex, it'd be very useful if the data included a gender symbol (where applicable)

**Comment by nahojjjen** [comment]
There's a "gender symbol" token, it's the 6th token in the "basic stats" list.

**Comment by navarr** [comment]
I apparently did not see that massive customization screen.

My apologies

**Comment by nahojjjen** [comment]
No worries,  the clipboard screen is very arbitrarily organized, and theres no search, so missing it is understandable.
