### ISSUE TITLE
evolution list shows duplicate pokemon when including Normal Form.

### ISSUE THREAD

**Issue by udnp** [farkam135/GoIV#1019]
In this screen image case,
[Rattata] and [Rattata - Normal Form] are duplicate pokemons.
Also [Raticate] and [Raticate - Normal Form] are duplicate.
![device-2018-11-29-213303](https://user-images.githubusercontent.com/17121615/49240374-5ecb3b00-f448-11e8-9110-410f1edfd0bb.png)

**Comment by xZise** [comment]
This should be fixed with bf985bf. It'll now only show valid evolutions (in your case the normal forms).

**Comment by udnp** [comment]
Thank you for your contributing. I've built and briefly checked commit 423329921f7ca841efd2f0501c241d4eb262d04f. 

For Sandshrew, it just shows [Sandshrew - Normal Form] and [Sandslash - Normal Form], no longer [Sandshrew] and [Sandslash].
 
![issue-1019-case-sandshrew-basic](https://user-images.githubusercontent.com/17121615/57567682-04cb9a00-7418-11e9-9bc9-68413a84cf77.png)

![issue-1019-case-sandshrew-powerup](https://user-images.githubusercontent.com/17121615/57584627-830f6580-7518-11e9-840c-3547a6def2a0.png)

For Pikachu, it just shows [Raichu - Normal Form], no loger [Raichu].
![issue-1019-case-pikachu-basic](https://user-images.githubusercontent.com/17121615/57567731-a226ce00-7418-11e9-93bd-50898a734dea.png)

![issue-1019-case-pikachu-powerup](https://user-images.githubusercontent.com/17121615/57584658-e26d7580-7518-11e9-98c1-fee3d7e0e70b.png)

So we can close this issue.
