### ISSUE TITLE
Scanning Alolan Ninetales doesnt work - selects vulpix even on manual correction

### ISSUE THREAD

**Issue by nahojjjen** [farkam135/GoIV#1034]
When scanning an alolan ninetales, it attempts to parse it as a vulpix. Even if you open the correction dialog and select alolan ninetails, it gives you the results as if you'd selected an alolan vulpix.

**Comment by nahojjjen** [comment]
-A similar issue seems to occur when attempting to scan Azumaril, it selects marill instead.

**Comment by xZise** [comment]
I've issues when scanning an Alolan Raticate that it assumes it is an Alolan Rattata. When I select Alola Raticate and check the IV again, it again selects Alola Rattata. Also typing it, it always selects Alola Rattata.

**Comment by xZise** [comment]
It seems like selecting `POKEMON - Normal Form` or `POKEMON - Alolan Form` doesn't properly work. When scanning a normal form Ninetales it defaults to Vulpix, fair enough, but selecting `Ninetales - Normal Form` seems to be ignored (similar to the issue described here). Selecting just `Ninetales` works actually, so maybe the issue is related.

**Comment by nahojjjen** [comment]
I can no longer reproduce the issue on version 5.2.9, might have been fixed with the forms.xml update?

I havent tested exhaustively, so the issue might still be here, and I dont know why the change would have fixed this issue...

**Comment by PeterWeiler** [comment]
I'm continuing to have the same issue with Deoxy on 5.3.0.  Doesn't matter if I manually select the correct form, it reverts back to the default when I appraise.

**Comment by dominicbarnes** [comment]
I see this issue with Azumarill for certain, even with the latest version.

**Comment by fredkilbourn** [comment]
Also having the same issue with Azumarill ![](https://i.imgur.com/b1Wk4lE.png)

**Comment by nahojjjen** [comment]
Azumarill has become bugged due to another reason this patch. The 'new attack' button lists a candy cost of 50, and is in the same place as the evolution cost. GoIV miss-reads the new-attack candy cost, and mistakes it for evolution cost. And since a Marill has an evolution cost of 50, it misstakes it for marill. I've attempted to fix this in #1045

**Comment by fredkilbourn** [comment]
not sure if related but I'm also seeing this with Dugtrio

**Comment by nahojjjen** [comment]
Should be fixed in 5.4.0, open a new issue if similar / same issue appears.
