### ISSUE TITLE
Delete number when fixing CP / HP manually

### ISSUE THREAD

**Issue by rpgrca** [farkam135/GoIV#104]
When editing CP or HP, the keyboard blocks the input field.
This wouldn't be that bad if the cursor was set at the end of the number, but instead it's placed at the beginning, so you have to guess the position while editing. If the cursor was placed at the end instead, you would delete the number with backspace.

Maybe you could just delete the whole number when tapped? It would be much faster inputting the correct number instead of editing the old one.

**Comment by Blaisorblade** [comment]
> When editing CP or HP, the keyboard blocks the input field.

I've seen that too, that's something that @nahojjjen is trying to fix.

> Maybe you could just delete the whole number when tapped? It would be much faster inputting the correct number instead of editing the old one.

👍 . Or could it be selected by default, so just typing deletes it but you have a choice?

**Comment by Blaisorblade** [comment]
Additionally: if recognition fails sometimes the code picks 10 as CP. It'd be better to pick an empty string and force you to enter something.

**Comment by farkam135** [comment]
Closed. EditTexts should be moving up now. Please update and try again.
