### ISSUE TITLE
Bug "Show clipboard preview popup" covers HP

### ISSUE THREAD

**Issue by Limero** [farkam135/GoIV#1041]
The setting for "Show clipboard preview popup" is very useful but it makes it it impossible to quickly swipe between Pokémons because the preview covers the HP.

Solution would be to show the preview window underneath any information used for scanning.

Screenshot of the issue (OnePlus 5T)
![Screenshot_20190414-140641_Pok�mon_GO](https://user-images.githubusercontent.com/639787/56092647-0197c980-5ebf-11e9-930b-c201e573573d.png)

**Comment by nahojjjen** [comment]
I agree that the popup placement is sub-optimal.

**Comment by Limero** [comment]
This was fixed with the app toasts rework in 5.4.0. Thank you!

**Comment by nahojjjen** [comment]
Thank you for keeping tabs and closing the issue :) Sorry the change took so long.
