### ISSUE TITLE
No IV button, Oneplus 3, Android 6.0.1

### ISSUE THREAD

**Issue by Lacholajban** [farkam135/GoIV#105]
Hi

I just downloaded the app and as some others have commented already the IV button doesn't show for me. As mentioned in the headline I'm using a Oneplus 3 with Android 6.0.1, all permissions granted and under the FAQ I see this which I assume affects me "The phone you're running has a faulty screen capture api (Seems to occasionally affect Cyanogen and some lesser known phone brands)". Is there anything I can do to fix this or is there an update comming that is going to solve this issue? If I have the battery saver option unchecked and press start the phone wants me to type in my pin code for permission or something like that and then nothing happens. If I have the box checked I assume I have to take a screenshot when looking at a pokemon? Nothing happens either way.

The app looks awesome when I saw it on YouTube, hope I also can use it soon :)

**Comment by superdudut** [comment]
Samething happen to me using Xiaomi Redmi Note Android 4.4.4 KTU84P but it just not showing the IV button, nothing like pin or other request to fill in, it just dont appear at my screen

**Comment by icastell** [comment]
Hi @superdudut I had the same problem with MIUI 8 is a permission issue, you have to allow the app to show the floating button. Check the permission app screen.

**Comment by yeow928** [comment]
Same to me. Xiaomi 4i.

**Comment by yeow928** [comment]
Hi icastell, u r right. now can work for my phone. Thanks

**Comment by farkam135** [comment]
Closed. Xiaomi devices require extra permission. @Lacholajban unfortunately that's a bug in the rom and we cannot fix this issue.

**Comment by superdudut** [comment]
@icastell i am using MIUI 7 and have allow for the permission but still cant show up
