### ISSUE TITLE
Porygon2 detected as Porygon_z

### ISSUE THREAD

**Issue by stevedesmond-ca** [farkam135/GoIV#1052]
Particularly troublesome when scan correction dialog is disabled

![Screenshot_20190518-130612](https://user-images.githubusercontent.com/195896/57972834-bb2a0480-796d-11e9-8d42-a5fcd6cbfe1b.png)

![Screenshot_20190518-130322](https://user-images.githubusercontent.com/195896/57972801-61c1d580-796d-11e9-80e1-ab147ddb83e5.png)

**Comment by nahojjjen** [comment]
Does the issue still occur on 5.4.0?

This issue might have been caused by misreading the '100'. 5.4.0 included logic to handle some cases related to this smarter. #1056 Also includes improvements which would fix an issue that would cause this error.

**Comment by stevedesmond-ca** [comment]
Fixed!
![Screenshot_20190520-172619](https://user-images.githubusercontent.com/195896/58053046-709eb880-7b24-11e9-8762-2e9c8d236724.png)
