### ISSUE TITLE
Suggestion: still allow for "Scan Correction Dialog" when feature is disabled

### ISSUE THREAD

**Issue by stevedesmond-ca** [farkam135/GoIV#1053]
As a GoIV user with scan correction dialog disabled, I want an easy way to correct incorrect OCR detection without needing to re-enable the feature from the settings page.

Possible implementations:
- When scan correction dialog is disabled but a Pokémon's stats cannot be detected, the GoIV button opens the scan correction dialog instead of the "something went wrong" IV dialog
- IV dialog contains a small button that goes to the scan correction dialog

**Comment by nahojjjen** [comment]
You can press the back-arrow left of the "IV scan results" text to go back to the input

**Comment by stevedesmond-ca** [comment]
This does exactly what I was looking for!
