### ISSUE TITLE
slakoth crashes GoIV

### ISSUE THREAD

**Issue by jimmywan** [farkam135/GoIV#1062]
Almost always occurs as soon as I click on a slakoth.

**Comment by jimmywan** [comment]
Tested on Samsung Galaxy S8 and Asus ZenPad  3s 10 (aka P027).

**Comment by thearaks** [comment]
If you are using ExtendedCpTierToken in your clipboard configuration then #1064 will fix it!

**Comment by jimmywan** [comment]
Thanks! I bet that will do it.

**Comment by jimmywan** [comment]
Confirming that patch fixed my issue.

**Comment by thearaks** [comment]
Good! Thank you!
