### ISSUE TITLE
Update GoIV for the appraisal rework 0.149.0

### ISSUE THREAD

**Issue by jamesl1001** [farkam135/GoIV#1074]
As of (Android version 0.149.0), the appraisal system has been updated to display the exact IVs of each Pokémon.

Although we can now easily determine the xx/xx/xx IV format, it would still be nice to be able to automatically calculate the % IV, for those who prefer that format.

![Screenshot_20190716-115723](https://user-images.githubusercontent.com/2076731/61289385-23a42f00-a7c1-11e9-94cf-fe5df7c5450c.jpg)

**Comment by xZise** [comment]
Implementd with ba53164 and 5.4.3 this should work, there are still issues see #1077.
