### ISSUE TITLE
69: "This name contains inappropriate text."

### ISSUE THREAD

**Issue by canavan** [farkam135/GoIV#1086]
Any Pokemon name that contains "69" is considered inappropriate and cannot be saved. Since editing text aside from deleting everything from the right is apparently impossible in PoGo, it would be nice if "69" could always be replaced by 68 in the text sent to the clipboard.

**Comment by durandj** [comment]
Rather than assigning an incorrect IV to the name, why not just use superscript numbers instead? The game allows for those and it's how I've been handling this.

**Comment by xZise** [comment]
I'm also confused about "deleting everything from the right". There has been a period where a bug wouldn't open the textbox where you can move the cursor but this is already fixed.

**Comment by canavan** [comment]
_I'm also confused about "deleting everything from the right". There has been a period where a bug wouldn't open the textbox where you can move the cursor but this is already fixed._

That was an issue in PoGo for a month or two when it was indeed impossible to re-position the cursor within the text, it was always stuck at the back, long since fixed.

**Comment by canavan** [comment]
_Rather than assigning an incorrect IV to the name_

It's not incorrect, it's just rounding down, instead of to nearest or up. Correct would be 68.8888..., so neither 69 nor 68 are strictly speaking "correct", 68 is just less accurate.

**Comment by canavan** [comment]
"69" has apparently been removed from the blacklist in the meantime.
