### ISSUE TITLE
Level arc doens't match anymore

### ISSUE THREAD

**Issue by flocke** [farkam135/GoIV#1087]
Since one of the latest updates (I'm not really sure which one) the level arc doesn't seem to match anymore.

And when trying to recalibrate it doesn't properly detect it as well. It always seems to be a little to high when the width matches (see screenshot). I also tried manually adjusting the arc, but since I only can change the radius the problem with the width-to-height ratio also exists there.

![Screenshot_20200422-072844](https://user-images.githubusercontent.com/76665/79944536-13b22d80-846c-11ea-9551-1cb7ff817a1e.png)

**Comment by thearaks** [comment]
There might be something strange happening in the game,
the arc seems to be erroneously shifted downward.
See the lvl 1 dot in this screen:

![Screenshot_2020-04-22-17-58-54-141_com nianticlabs pokemongo](https://user-images.githubusercontent.com/5188791/80023436-d1293900-84dd-11ea-917b-ffcc02752be5.jpg)

Should we wait a little hoping for Pokémon GO to fix it?

**Comment by flocke** [comment]
Doesn't seem to be the case on my phone:

![Screenshot_20200422-212633](https://user-images.githubusercontent.com/76665/80024980-31b97580-84e0-11ea-84c3-d9257d922f7a.png)

But I agree, lets wait at least for the next update and see if something changes.

**Comment by nahojjjen** [comment]
looks like pokemon 173.2 squished the level arc to only be 95% the height, im pushing an update to fix that now (confirmed that it worked for some others on discord)

**Comment by flocke** [comment]
Thank you, I can confirm it now works with the latest update.
