### ISSUE TITLE
Roggenrola/Boldore/Gigalith evolve cost

### ISSUE THREAD

**Issue by stevedesmond-ca** [farkam135/GoIV#1090]
Steps to reproduce:
- inspect a Roggenrola via GoIV and select "Power Up"

Expected result:
- evolution costs 50 candy (or 250 total for Gigalith)

Observed result:
- evolution displayed as 25 (and 125 respectively)

**Comment by udnp** [comment]
Thanks your feedback.

> Expected result:
> * evolution costs 50 candy (or 250 total for Gigalith)

Could you check current release version GoIV 5.4.6?

P.S. traded their evolving candy costs have still been wrong.

**Comment by stevedesmond-ca** [comment]
Confirmed fixed in the latest version. Thanks!
