### ISSUE TITLE
Unable to click start

### ISSUE THREAD

**Issue by LyrrenClock** [farkam135/GoIV#110]
Using HTC one 510 desire the battery saver box and start are grey and un clickable I don't know what I'm doing wrong.

**Comment by mattaereal** [comment]
Are you sure you don't have already an overlay app that may conflict with GoIV? Have you accepted the apps permissions?

**Comment by farkam135** [comment]
Has this issue been resolved?

**Comment by farkam135** [comment]
Closing, reopen if this issue still persists.
