### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by thomasthuyaaung** [farkam135/GoIV#12]
Encounter this error when trying to open APK
There is a Problem Parsing the Package

**Comment by chuparCh0pper** [comment]
Are you using https://drive.google.com/file/d/0B0Nazg34pSbpTzU2YkNFcndENDA/view ?
please check your hashes:
CRC32: 9C37D87F
MD5: 1779FA8166F1948044916F862E28A9A9
SHA-1: 24E781561917D5305EA9CEC253DA15B354759F94

**Comment by thomasthuyaaung** [comment]
yeah downloaded from that link. Not sure how to check the hashes. I'm using Nox emulator.

**Comment by thomasthuyaaung** [comment]
file name downloaded is 'GoIV(1.3.0).apk'

**Comment by chuparCh0pper** [comment]
If you are on windows try this
`CertUtil -hashfile C:\TEMP\MyDataFile.img MD5`
or just redownload it and try again

Thsi just looks like an error while downloading

**Comment by LukasLapa** [comment]
same error here, using nox too

**Comment by farkam135** [comment]
Currently GoIV only supports Android 5.0+ due to utilizing the screen capture api. To my understanding Nox runs android 4.4.4
