### ISSUE TITLE
Beedrill is scanned as BeedHH (internally) and recognized as Weedle

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#120]
I've confirmed this with Android Studio's debugger. Maybe @nahojjjen has an idea how to fix this that is better than replacing occurrences of `BeedHH` by `Beedrill`, since he managed to tune the OCR better?

**Comment by sarav** [comment]
#131 kind of fixes this problem at least for each run of the app. Once you fix the detection from the list, it'll learn from your correction.

**Comment by farkam135** [comment]
Closing for now. Only so much we can do to the OCR to improve results. This is a device specific issue (my device reads Beedrill fine). As long as it gets corrected to Beedrill it's fine.

**Comment by sarav** [comment]
#165 actually save the correction and works around this.
