### ISSUE TITLE
Change getAveragePercent to getMedianPercent and label as such to user

### ISSUE THREAD

**Issue by skylerbunny** [farkam135/GoIV#122]
Suggestion: change getAveragePercent to getMedianPercent. (This is a suggestion regardless of any UI retool that may be done with output *using* these stats.)

Since the IV possibilities at any given point is a discrete set (and not a random possibility within the range), the median of the possibilities is more valuable at a glance. Here's what I'm saying:

List: 0, 1, 45, 48, 49, 52, 53, 58

Min/Average/Max: 0/38.25/58

Min/Median/Max: 0/48.5/58

(Calculation: http://www.calculatorsoup.com/calculators/statistics/mean-median-mode.php )

The latter reflects the fact that it is much more likely that the Pokemon will have an IV set closer to 50 than zero. Generally speaking, a median calculation will give a more accurate 'middle' than a mean/average will.

**Comment by hlplulustg** [comment]
The example you gave is a skewed distribution where median should be used. The arc detection method produces rather normal symmetric distributions without outliers.

List: 69, 73, 76, 76, 78, 82, 84, 87
Average: 78,125
Median: 77

I'm not convinced median would be much of a benefit. Correct me if I overlooked some outlier possibilities or anything else.

**Comment by skylerbunny** [comment]
I used extreme outliers specifically to illustrate why median calculations are superior for discrete data sets in general and freely grant that in these sets, we're more *likely* to see changes of a percentage point or three.

In any event I'll give a real world example or three based on a couple IV sets I have in my inventory.
> (A lvl 14 Dewgong)
> 15/8/13 (80%)
> 13/13/13 (87%)
> 12/15/13 (89%)
> 15/7/14 (80%)
> 12/14/14 (89%)

The pure mean is 83.2%, which I would assume rounds down to 83% (so you see 80-83-89). However the data sets presented above are not themselves very symmetric, assuming these five possibilities have equal chances of being 'true'; they have discrete predictable values in this set of five and they skew upward.

The median is 87%, indicative of the fact that there are three sets that give one 87% or above, and two that give 80%, so you would see (80-87-89). Does those four percentage points matter? I guess it depends on the trainer.

**Comment by hlplulustg** [comment]
That's what I meant. To be exact it's not even two points when using the unrounded values and if I'm not mistaken that's already a high skewness in terms of GoIV. Tbh I don't look at average/mean/median anyway, the only important information is min and max.

**Comment by oskomonzon** [comment]
To add to the discussion... You've got a point when we are talking about some particular cases, but most IV calculation tools display Average instead of Median.
I'm not sure if the change to address such extreme scenarios is worth it due to that fact: Most players are already used to get Min, Avg, Max values.

I really like the idea tho. But I'm concerned about the reception.

**Comment by rpgrca** [comment]
Down here we say, if in doubt, add a setting. It is pretty trivial, and could be added to the list made in #71

**Comment by farkam135** [comment]
Closing. It does seem pretty trivial now especially once the the refinement by appraisal is released this does not seem necessary. Will stay average.
