### ISSUE TITLE
Gastly crashes GoIV

### ISSUE THREAD

**Issue by rpgrca** [farkam135/GoIV#135]
1. Start service
2. Try to scan Gastly, 4 out of 5 times the IV button just disappears.
3. Go back to GoIV screen, click STOP button, the application closes with "Unfortunately, GoIV has stopped.".

Samsung Note 5, 6.0.1, GoIV 2.1.0. It didn't happen with the last version from the Play Store, it would just fail to recognize the CP when the smoke covered it.

**Comment by aa8y** [comment]
Can confirm. Does the same for me. I see it happen when the smoke around it covers the CP number on the top of the screen. If it the CP is clearly visible, it works just fine and I didn't see this issue in the older version of GoIV as well.

**Comment by nahojjjen** [comment]
Are you running 2.1.0 or github version?
As far as I'm aware, I should have fixed all gastly crashes on git main branch.

**Comment by aa8y** [comment]
It's 2.1.0. How do I compile master to make an apk? I am sorry I've never
really worked with Android apps.

**Comment by rpgrca** [comment]
Tried the github version, and looks like it's been fixed for similar cases as well (Koffing, Weezing, etc). Thanks!

**Comment by rpgrca** [comment]
By the way, if you are in a Pokemon screen, scroll up the page (so that the CP goes out of scope) and press the IV button, it disappears and when you stop the service it crashes as it did with the Gastly problem.

**Comment by jehy** [comment]
Confirmed problem when screen scrolled up - IV button disappears, nothing happens and when GoIV is closed, following error occures:


> 08-23 13:01:18.568 31750-31750/com.kamron.pogoiv.nointernet E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                               Process: com.kamron.pogoiv.nointernet, PID: 31750
>                                                                               java.lang.RuntimeException: Unable to stop service com.kamron.pogoiv.Pokefly@c5cb63d: java.lang.IllegalArgumentException: View=android.widget.ImageView{6a8b94 V.ED..... ......I. 0,0-0,0} not attached to window manager
>                                                                                   at android.app.ActivityThread.handleStopService(ActivityThread.java:3116)
>                                                                                   at android.app.ActivityThread.access$2300(ActivityThread.java:154)
>                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494)
>                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                                   at android.os.Looper.loop(Looper.java:234)
>                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5526)
>                                                                                   at java.lang.reflect.Method.invoke(Native Method)
>                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>                                                                                Caused by: java.lang.IllegalArgumentException: View=android.widget.ImageView{6a8b94 V.ED..... ......I. 0,0-0,0} not attached to window manager
>                                                                                   at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:424)
>                                                                                   at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:350)
>                                                                                   at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:113)
>                                                                                   at com.kamron.pogoiv.Pokefly.onDestroy(Pokefly.java:224)
>                                                                                   at android.app.ActivityThread.handleStopService(ActivityThread.java:3097)
>                                                                                   at android.app.ActivityThread.access$2300(ActivityThread.java:154) 
>                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494) 
>                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                                   at android.os.Looper.loop(Looper.java:234) 
>                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5526) 
>                                                                                   at java.lang.reflect.Method.invoke(Native Method)

**Comment by Blaisorblade** [comment]
@jehy I'm working on that crash, I have identified something iffy which might cause it in part.
It seems like sometimes the MainActivity never replies to the Pokefly service?
