### ISSUE TITLE
Show last possibility too if only one left

### ISSUE THREAD

**Issue by rpgrca** [farkam135/GoIV#137]
From latest github version:

![screenshot_20160823-001232](https://cloud.githubusercontent.com/assets/15602473/17879243/bc777558-68c6-11e6-805e-d642fde67468.jpg)

If there's only one more possibility, use that line to show it instead of informing it. In other words, that message should only appear if there are at least 2 extra combinations.

**Comment by nahojjjen** [comment]
I think we're gonna work on the new UI instead of tweaking the old one

**Comment by farkam135** [comment]
Closing, #162 includes this.
