### ISSUE TITLE
Is the math for cutting out the Pokemon name bitmap correct?

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#139]
At a quick glance, it seems to be misaligned in the same picture I posted in issue #96 

Maybe I'm missing something? Like the status bar and navigation bar? Or am I doing the math wrong? Can someone check this? It looks like it's chopping off the bottom part of the pokemon name and it's going too high up.

**Comment by nahojjjen** [comment]
![huhu](https://cloud.githubusercontent.com/assets/8545451/17888122/c8cd4496-6929-11e6-8ca3-ef629b72468b.png)

And example scan of the name which I took by going into debug mode. Looks pretty good on my device.

**Comment by sarav** [comment]
How did you get this image? I want to check it on me 720x1280 device. Can you use the screenshot I posted and see what it gives you? You can "share" it with the app to test.

**Comment by nahojjjen** [comment]
Go into debug mode, put a breakpoint after the tesseract has read the image, and press "view bitmap" in the debug variable list.

**Comment by farkam135** [comment]
Closing, seems accurate if you can post a picture proving otherwise issue will be reopened.

**Comment by sarav** [comment]
Thanks @nahojjjen I tried it and the bitmap is good. I'm guessing my assumptions about displaymetrics.width and height were wrong because the math certainly wasn't :)
