### ISSUE TITLE
Always get - No possibilities, please check your stats again!

### ISSUE THREAD

**Issue by squiggie** [farkam135/GoIV#14]
I always get this message when I try to calculate IV's. Stepping through the code, it appears that in the getIVText() method, the if (hp == pokemonHP) is never true. The hp is always > than pokemonHP. Is there something I'm doing incorrectly or are the calculation off? I've probably tried about 100 pokemon and I've never got anything other than no possibilities.

**Comment by agrajaghh** [comment]
did you correctly set your trainer level?

**Comment by squiggie** [comment]
I sure did. Set that to 24. I even tried setting the pokemon hp, arc and cp levels manually as well.

**Comment by chuparCh0pper** [comment]
Please try this tool:
https://pokemon.gameinfo.io/tools/iv-calculator

Also can you please tell us your stats

**Comment by squiggie** [comment]
Sure. I used that tool on an example Pikachu and got the following at trainer level 24, CP501, HP50 Starrdust cost 2500 and refined with a single power up;
Level | Attack | Defence	 | Stamina | Percentage perfect
------|-------|----------|---------|------------------
20 | 14 | 11 | 13 | 84%

**Comment by hlplulustg** [comment]
Didn't you say you don't get any possibilities? Can you supply images with the stats GoIV recognises and the resulting possibilities?

**Comment by squiggie** [comment]
![screenshot_20160816-112821](https://cloud.githubusercontent.com/assets/2479851/17707227/07c8b5b6-63a5-11e6-9c78-ecaff695a7a1.png)
![screenshot_20160816-112811](https://cloud.githubusercontent.com/assets/2479851/17707226/07c8261e-63a5-11e6-929b-a55012a7d134.png)

**Comment by hlplulustg** [comment]
I calculated your pikachu example by manually adjusting the values. Got the correct six combinations with version 1.2.1/1.2.2 and 1.3.0 as well. The logic is correct.

**Comment by simonho1989** [comment]
i stepped into this problem as well. Yesterday , i can calculate my dragonite, this morning, it shows no possibilities on all pokemon.

**Comment by simonho1989** [comment]
Mine was working fine yesterday but not today. Is showed no possibility on all encounters. I resolve the issue by unstalling and reinstalling the 1.3 apk. You guys may try to reinstalling it. Dont sure what part of the code causing this.

**Comment by McAJBen** [comment]
The pikachu is level 20, but the red dot is slightly out of alignment. so it tests all variables for a level 20.5 instead and finds none.

**Comment by squiggie** [comment]
I can adjust the level slider down .5 to 20 and it still gives me the no possibilities result.

**Comment by Blaisorblade** [comment]
This issue overlaps with #34.

**Comment by Blaisorblade** [comment]
And... this is fixed on master! I've input the same values and got 6 matching combinations.

![2016-08-22 10 27 18](https://cloud.githubusercontent.com/assets/289960/17852207/45c7cf62-6866-11e6-94a1-5a27330d76e7.png)

**Comment by farkam135** [comment]
Fixed in update
