### ISSUE TITLE
There was a problem parsing the package

### ISSUE THREAD

**Issue by alowva** [farkam135/GoIV#146]
When trying to install the 2.2 apk I get the above error.

I Tried on an samsung s5 and s6 both running marshmallow

**Comment by jehy** [comment]
Package is valid, just checked it.
Please check your md5 file hash. It should be 57F2C9628389E787BA2F1B095C9261EC
You can also try re-downloading.

**Comment by nahojjjen** [comment]
The first package we uploaded was signed wrong, we fixed it after 5 minutes, maybe you managed to download it during the time it was wrong?

**Comment by agrajaghh** [comment]
I just downloaded the 2.2 release, MD5 is `57F2C9628389E787BA2F1B095C9261EC`, but updating from 2.0.0 is not possible:

` W/PackageManager: Package com.kamron.pogoiv signatures do not match the previously installed version; ignoring!`

**Comment by alowva** [comment]
I download it 5 minutes before opening the issue.

I get md5 of e226948a8d9f3f4604ffd18ca26eeda7
For both copy's I have. Will try dowoas again now

**Comment by alowva** [comment]
Downloaded again, got md5 of 57f2c9628389e787ba2f1b095c9261ec
Had to uninstall previous version as it would not upgrade but it installed this time

**Comment by agrajaghh** [comment]
please reopen, since update is not possible. Or did you guys switch certificates on purpose?

**Comment by alowva** [comment]
Update is a different issue, feel free to open a new ticket
