### ISSUE TITLE
can't update from 2.0 to 2.2. Certificate change?

### ISSUE THREAD

**Issue by agrajaghh** [farkam135/GoIV#147]
I just downloaded the 2.2 release, MD5 is `57F2C9628389E787BA2F1B095C9261EC`, but updating from 2.0 is not possible:

```
W/PackageManager: Package com.kamron.pogoiv signatures do not match the previously installed version; ignoring!
```

**Comment by Blaisorblade** [comment]
I observed the same problem—uninstalling, reinstalling and granting permissions again worked around the problem.
Though honestly I was using a self-built APK from master, so my case doesn't count.

**Comment by Eccenux** [comment]
Yeah, you have to uninstall each time going from debug->release and vice versa.

**Comment by agrajaghh** [comment]
I'm running the normal 2.0 release downloaded from github, not the self-built debug version

**Comment by Blaisorblade** [comment]
The workaround will still work and it's quickest—have you done that? Also, @nahojjjen has answered this on Reddit.
https://www.reddit.com/r/GoIV/comments/4z5qxz/goiv_220_released/d6tht3i

The maintainer should stick to the same certificate (if that's the reason) to avoid this in the future, but I guess for this release there's not much to do.

**Comment by agrajaghh** [comment]
yeah I know that re-installing works, just wanted to report it in case its a mistake. thanks for the reddit link
> We ran into some issues with signing the application because we split it into two different versions, make sure you uninstall the previous application before installing the new one.

**Comment by archon810** [comment]
Why did the signature change between 2.1 and 2.2 for release versions?

**Comment by archon810** [comment]
Got response from dev: "@archon810 Old key got corrupt, backed up the new key so there shouldn't be anymore problems."
