### ISSUE TITLE
Cannot install 2.2.0

### ISSUE THREAD

**Issue by leblangi** [farkam135/GoIV#148]
There an error with the installation of the 2.2.0 apk on my Nexus 5x. Its work with 2.1.0.

**Comment by agrajaghh** [comment]
are you trying to update? duplicate of #147?
or is it happening with a clean install?

**Comment by leblangi** [comment]
Clean install, first time using GoIV.

**Comment by agrajaghh** [comment]
what is the md5 hash of the apk? what is the error? can you get a adb log?

**Comment by leblangi** [comment]
The file is : GoIV-Online.2.2.0.apk
The file checksum is : E226948A8D9F3F4604FFD18CA26EEDA7 (from http://onlinemd5.com/)
I downloaded it this morning via this link : https://github.com/farkam135/GoIV but the link is no longer there.
Finally, I don't know how to get a adb log and google do not really help me easily about it. Sorry! Can you explain me how to get this log ?

**Comment by agrajaghh** [comment]
you should download it again from
https://github.com/farkam135/GoIV/releases

the correct hash should be 57F2C9628389E787BA2F1B095C9261EC

**Comment by leblangi** [comment]
The error using the App "APK Installer" :
Parse error
There was a problem parsing the package.

**Comment by leblangi** [comment]
Its working now! Do you know the error ? I was sure the link I download was good and was from you so its not infected package or something.

**Comment by agrajaghh** [comment]
maybe it was this: https://github.com/farkam135/GoIV/issues/146#issuecomment-241696442

**Comment by leblangi** [comment]
Same checksum so yes! Thanks!

**Comment by archon810** [comment]
Why did the signature change between 2.1 and 2.2 for release versions?

**Comment by archon810** [comment]
Got response from dev: "@archon810 Old key got corrupt, backed up the new key so there shouldn't be anymore problems."
