### ISSUE TITLE
Screenshot Mode not responding to screenshots

### ISSUE THREAD

**Issue by cdsimpkins** [farkam135/GoIV#149]
On a stock Nexus 6, I started the app and let it detect my screenshot folder in the "Setup" phase.  The problem is no matter how many screenshots I take, it never picks any of them up  for processing.  I have tried taking multiple screenshots (up to 5 with ~5 sec between), as well as clearing out GoIVs data and starting over to no avail.

I can use the Now on Tap option or "Share" a screenshot with the app and it works fine, it's just that both of those options are slower due to all the user interaction required.  

Edit: That was weird.  ~3-4 minutes after a screenshot, the overlay popped up.
![screenshot_20160823-080334](https://cloud.githubusercontent.com/assets/2373603/17891203/54146c4a-6908-11e6-88c4-7f6d3db2c25e.png)

**Comment by simonho1989** [comment]
same here, my stock nexus 6 pop up result window after ~2 minutes

**Comment by sarav** [comment]
@farkam135 I think you should just go back to the content observer and add a settings for "number of content observer events per screenshot" option.

**Comment by farkam135** [comment]
@sarav hmm, I wonder why the current implementation is struggling. @cdsimpkins Did the setup detect your screenshot folder fine?

**Comment by sarav** [comment]
@farkam135 Like I said in the earlier comment, I think the FileObserver events aren't coming :( So, contentObserver is the best bet, but it'll need some setting or massaging. Maybe a setting called "Missed screenshot workaround" and that could be used to decide how many events to wait for.

**Comment by sarav** [comment]
@farkam135 With my better familiarity with the Android Studio debugger, I've confirmed the CLOSE* events don't come for the screenshot.

**Comment by sarav** [comment]
If only Google Now on Tap didn't spend ages before it showed me the "share options" I wouldn't care so much for this.

**Comment by cdsimpkins** [comment]
@farkam135 It claims to have detected it, and the folder it lists is in fact my SS folder. 

@sarav I feel the same way about now on tap, but I'm using it for now because I need every ounce of batter life I can get. lol.

**Comment by sarav** [comment]
@farkam135 plan on working on this?

**Comment by DJCrapsody** [comment]
@cdsimpkins there were changes to screenshot mode, if you have Android Studio, you can build from sources and test it.

**Comment by sarav** [comment]
Should be fixed in the next release. And you shouldn't get those random popups either. PR #393

**Comment by Blaisorblade** [comment]
@cdsimpkins Please let us now if this is still a problem.

**Comment by cdsimpkins** [comment]
sorry, got buried in the other projects i'm following.  I'll check it out this afternoon and report back, thanks!

**Comment by cdsimpkins** [comment]
Latest build from master seems to work as designed.  tested with a few different pokemon.  Thanks!
