### ISSUE TITLE
Incorporating Appraisal Information

### ISSUE THREAD

**Issue by hlplulustg** [farkam135/GoIV#153]
With the GoIV information from a single calculation combined with appraisal information a feature to narrow down could become unnecessary. To begin with, what information does appraisal provide?

- IV ranges but with rather wide sections described by a phrase (e.g. 80% - 100%).
- The strongest IV stat or set of stats if equal (attack/defense/stamina).
- A phrase describing the value of the strongest stat or set of stats (15, 13-14, 8-12, 0-7).

The IV range won't help in most cases but in some if the arc detected range is broken up into two appraisal sections. The phrase describing the strongest IV value or set would definetely help the elimination process. Regarding implementation and usability both phrase possibilities would need to be included for selection which makes input overwhelming.

The strongest IV stat or set of stats however are very easy to comprehend from the appraisal. Three simple optional fields need to be on the input screen - ATK, DEF, HP. I'm thinking of buttons getting highlighted if selected. Above those three buttons the line 'optional appraisal stats'

Using that information only many IV combinations can be eliminated leading to the exact combination or very few. People can still look up the exact combination by evaluating the phrase regarding the highest stat if necessary without wasting a single candy or stardust. 

Example code for filtering the calculated combinations based on the passed appraisal stats:

in `IVScanResult.java`

edit: included phrase evaluation

    public void filterByHighestAppraisal(boolean attack, boolean defense, boolean stamina, int phraseMinValue, int phraseMaxValue) {
    
        for (IVCombination ivc : iVCombinations) {

            maxStat = max( ivc.att, ivc.def, ivc.sta );
            if ( ( maxStat < phraseMinValue ) || ( maxStat > phraseMaxValue ) ) {

                iVCombinations.remove(ivc);
        
            } else if ( ( ( attack && defense && stamina ) && ( ( ivc.att != ivc.def ) || ( ivc.att != ivc.sta ) ) {

                iVCombinations.remove(ivc);

            } else if ( ( ( attack && defense ) && ( ( ivc.att != ivc.def ) || ( ivc.sta >= ivc.att ) ) )
                || ( ( attack && stamina ) && ( ( ivc.att != ivc.sta ) || ( ivc.def >= ivc.att ) ) )
                || ( ( defense && stamina ) && ( ( ivc.def != ivc.sta ) || ( ivc.att >= ivc.def ) ) ) {
					
                iVCombinations.remove(ivc);
		
            } else if ( ( attack && ( ( ivc.def >= ivc.att ) || ( ivc.sta >= ivc.att ) ) )
                || ( defense && ( ( ivc.att >= ivc.def ) || ( ivc.sta >= ivc.def ) ) )
                || ( stamina && ( ( ivc.att >= ivc.sta ) || ( ivc.def >= ivc.sta ) ) ) {
			
                iVCombinations.remove(ivc);
			
            }
		
        }
	
    }

That's crappy else ifs, maybe someone can come up with something more suitable. But that's simple logic eliminating a majority of combinations.

**Comment by hlplulustg** [comment]
Maybe going further and adding a phrase dropdown below the three stat fields. Since this is team specific a team selection on the start screen would be needed as well. Dropdown example elements 'WOW', 'exciting', 'job done', 'no greatness' in case of Candela (english). Will be a lot of translation.

**Comment by rpgrca** [comment]
Isn't that what PokemonGo 0.35 does?

![appraisal](https://cloud.githubusercontent.com/assets/15602473/17904719/cc6f928a-6946-11e6-92d3-99dda95f45f8.jpg)

**Comment by hlplulustg** [comment]
Yes those are snippets of possible answers. You don't need GoIV if you got that appraisal ;-) 15/15/15

**Comment by rpgrca** [comment]
Yep, that's my 100% Eevee. Also, I think I finally understand what you were saying, you want that the user optionally inputs the appraisal given by the trainer so that the possibilities could be narrowed down to an even smaller set. Unless GoIV saved that information somehow, it might not be that useful, I believe.

**Comment by hlplulustg** [comment]
Yes that's what I was aiming for. It would be as useful as it is now but much smaller ranges, exact combinations even in certain cases.

**Comment by farkam135** [comment]
We are already looking at designs for the implementation of this!

**Comment by Eric678** [comment]
It is pretty quick and easy to run appraisal before IV and pick the correct one - works in 2/3 or so of mine.  Worst is when Sta is highest then you cannot tell often whether is a good attacker or defender.  Still needs a power up refine.  Thanks.
Pretty annoying that when the list of possibilities is full it will put a line saying 1 more possibilities ... when you could just put the line in!  Poor coding there.   Really need to be able to scroll the list of possibilities as one knows none of those showing is correct but cannot see the rest. Could be difficult to put an interface in to fully encode the appraisal that is faster than just the user scanning the list of options unless one can OCR all the appraisal screens and languages... sounds hard.
BTW v2.2 is very smooth, big improvement - thanks :-)

**Comment by hlplulustg** [comment]
> Pretty annoying that when the list of possibilities is full it will put a line saying 1 more possibilities ... when you could just put the line in!

It's a part of #162 .

> Really need to be able to scroll the list of possibilities as one knows none of those showing is correct but cannot see the rest.

That's part of the redesign.

> Could be difficult to put an interface in to fully encode the appraisal

Discussion on this has already started, should fit in the input screen and provide fast user access.

**Comment by z-m-k** [comment]
You can add a couple of buttons in three lines each line with hidden overflow. I think it is enough to include a keyword from the appraisal. In Python you could do:

```python
appraisalIvRanges={
    0: [37,45],
    1: [30,36],
    2: [23,29],
    3: [0,22],
}
appraisalIvValues={
    0: [15,15],
    1: [13,14],
    2: [8,12],
    3: [0,7]
}
appraisalIvValuesStrings={
    'incredible': 0,
    'impressed': 1,
    'positive': 2,
    'normal': 3
}
appraisalIvRangesStrings={
    'wonder':0, 
    'attention':1, 
    'average':2, 
    'headway':3
}

#Format ivs=[att,def,sta,sum,max]
#ivs=refine_appraisal(('attention', [0,2], 'impressed'), ivs)
def refine_appraisal(appraisal, ivs, ix=False):
    ivs_refined=[]
    for iv in ivs:
        if iv[3]<appraisalIvRanges[appraisalIvRangesStrings[appraisal[0]]][0]: continue
        if iv[3]>appraisalIvRanges[appraisalIvRangesStrings[appraisal[0]]][1]: continue
        if 0 in appraisal[1] and iv[0]!=iv[4]: continue
        if 1 in appraisal[1] and iv[1]!=iv[4]: continue
        if 2 in appraisal[1] and iv[2]!=iv[4]: continue
        if 0 not in appraisal[1] and iv[0]==iv[4]: continue
        if 1 not in appraisal[1] and iv[1]==iv[4]: continue
        if 2 not in appraisal[1] and iv[2]==iv[4]: continue            
        if iv[4]<appraisalIvValues[appraisalIvValuesStrings[appraisal[2]]][0]: continue
        if iv[4]>appraisalIvValues[appraisalIvValuesStrings[appraisal[2]]][1]: continue
        ivs_refined.append(iv)
    return ivs_refined
```

In your code it would return a new IVScanResult. This is a very useful feature.

**Comment by Blaisorblade** [comment]
Somebody asked this again and pointed to Pokeassistant. https://pokeassistant.com/main/ivcalculator?locale=en

They have only 3 checkboxes to pick the strongest stat, which is probably an acceptable amount of complexity. Not sure about a good interface for mobile use though.

**Comment by rpgrca** [comment]
Wouldn't that make most people use GoIV twice per pokemon? They will probably forget they have to first run the appraise and remember the stats? Ideally I'd think the summary screen should have three buttons, "back", "refine" and "close", with "refine" moving the screen upwards to "free" the menu button, and asking the user to choose "appraise", then OCRing the text and adjusting the results.

With checkboxes, if they err one of the options they will be forced to recheck the appraise, and run GoIV again...

**Comment by Nizzem** [comment]
> OCRing the text and adjusting the results

This wont work well for battery saving mode

**Comment by farkam135** [comment]
@rpgrca I actually tested this out a couple hours ago, initially I was forgetting, but after about 6 pokemon  I got into the habit of appraising beforehand. We will be sticking with refining before checking.

**Comment by rpgrca** [comment]
What about the range? Dismissing it?

**Comment by Eric678** [comment]
In the field I find myself running GoIV first, recycle lots, if looks interesting then appraise as it is quite slow in comparison with GoIV, then run GoIV again with the appraisal data to narrow it down, and relabel and keep if good enough.

**Comment by hlplulustg** [comment]
@rpgrca I think most people checking IV's go for 85+ or  90+, the range phrase won't help there since it's seperating 80-/82+ sections.

**Comment by Blaisorblade** [comment]
> I think most people checking IV's go for 85+ or 90+, the range phrase won't help there since it's separating 80-/82+ sections.

I think no two players will agree on what they want, and it depends on Pokemon, scarcity, etc. IIRC I can only look for 85+ on Eevees and Magikarps, but nothing else. But I agree it's hard to support all infos without cluttering the UI :-(.

**Comment by oskomonzon** [comment]
Also, OCRing it would bring lots of headaches due to the need of multi-language support.
I think narrowing down the possibilities with a set of checkboxes or togglebuttons to pick the strongest IV stats should be enough in most cases.

**Comment by z-m-k** [comment]
All that is needed really:

![capture](https://cloud.githubusercontent.com/assets/3216223/17985114/9edde3d8-6b14-11e6-8f4f-926c06e3fd67.JPG)

**Comment by Blaisorblade** [comment]
@z-m-k Well, good point. I feel that *still* won't fit on a phone easily, but what do I know? It's still more convenient than going through a website maybe. But we can't have that for all IV checks.

**Comment by z-m-k** [comment]
No. But you a third button in the result modal can be added. You would have 'Back', 'Refine', 'Close'. Once you click refine you can have a full screen modal with toggles and after that you simply eliminate the options and report a new, refined, result.

**Comment by rpgrca** [comment]
If the user can choose a team during the setup, you would just need three checkboxes and a combo, right? Since it's not like they will be changing teams often enough, it should work.

**Comment by Blaisorblade** [comment]
@rpgrca To get all info from appraisals, you do want what @z-m-k showed. Except that I'd sort by ranking, e.g. headway -> above average -> attention -> wonder (from smallest to biggest).
That's *after* you select the team. His example fits best team Mystic (blue), see reference in http://pokemongo.gamepress.gg/pokemon-appraisal.

And yes, we can input the team during setup/in the settings, as suggested.

**Comment by BHMath** [comment]
According to everything I read here.

This is in my opinion a good possiility to implement this new appraisal.

First you scan your pokemon like you do for weeks now.
If more than one IV is possible a new button "Refine" appears.
If we click on this button, the overlay move to the top of our screen allowing the user to use the Evaluate menu of our Team leader.
Then we can select in GoIV overlay the 3 infos allowing us to get the more accurate iv. The button "Calculate again" on this new screen should move back to bottom IV to display the new IV set like it is now.

If I'm not clear enough I should try to create some design. But I'm terrible with this kind of stuff.

**Comment by farkam135** [comment]
Going to chime in again on this issue with the final judgment that I believe is fair and effective. Once released, if enough people complain, adjustments will be made. I played around with the current possibilities and refining using the appraisal, the statements usually don't make any difference for refinement. Out of 40 of my pokemon tested only 1 resulted in the statement cutting down a possibility and even then it wasn't a large change in the range. The extra UI clutter and work the user has to do to use the statements just isn't worth the refinement of range. For now we will be sticking with only stats.

**Comment by hlplulustg** [comment]
@BHMath That method would imply you had to run the appraisal before each and every GoIV scan.

The method @Eric678 pointed out is the most time-saving one for users. Run GoIV as you normally do and only use appraisal if you are interested in narrowing down. Appraisal is slow and you don't need precise results for bad ranges. If following that method a refine button on the results screen is not needed, only options for the input are.

Workflow:
Pokemon a: GoIV 20-30%
Pokemon b: GoIV 40-55%
Pokemon c: GoIV 45-60%
Pokemon d: GoIV 80-90% - Appraisal - GoIV+options 90%
Pokemon ...

@farkam135 already mentioned we will be sticking with refining before checking.

In the end team setup on first use (and settings), three toggles for the stats and two dropdown fields for the phrases (or one) are needed on the input screen if we want to use all information.

**Comment by hlplulustg** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/21061226/18002425/f96cc418-6b87-11e6-811a-055eb4366e67.jpg)

**Comment by hlplulustg** [comment]
@farkam135 I saw that last comment of yours too late. I agree only the highest stats should be in focus of the next release. Just looked at a few of my pokemon and the additional phrases (actually only the last one) would help identifying the exact combination. Posted two screens, in both cases range of the highest stat (atk) is the deciding factor. [http://imgur.com/a/akEWM](http://imgur.com/a/akEWM)

**Comment by rpgrca** [comment]
OT, but it irks me still that the cursor for editing numbers is left at the beginning of the textbox instead of the end.

**Comment by Blaisorblade** [comment]
@rpgrca Can you file a separate issue for that? Here it'll surely get lost 😉

**Comment by z-m-k** [comment]
I personally don't collapse the information to a single number or range. I prefer to know the exact stats. In my, anecdotal evidence incorporating information cuts down on the number of options a lot. But anecdotal evidence on one side here are the simulations. I look at all Pokemon, at 4 levels (15,20,25,30), all combinations of IVs (0-15); so some 2.5m options. First, the average number of IV combinations which would be reported based on different options:

Level|GoIV|+bestIV|+bestIV+bestIVval|+bestIV+bestIVval+rangeIV
---|---|---|---|---
15|5.67|2.67|1.85|1.74
20|4.0|2.13|1.6|1.52
25|3.11|1.83|1.45|1.38
30|2.56|1.63|1.35|1.3

So for instance, if you have a level 20, Pokemon you can expect to have 4 results returned right now. You can cut it to 1.52 on average if you incorporate all info. And 2.13 if you only ask for which IVs are the best. We can normalize this by the most exact result:

Level|GoIV|+bestIV|+bestIV+bestIVval|+bestIV+bestIVval+rangeIV
---|---|---|---|---
15|3.25|1.53|1.06|1.0
20|2.63|1.4|1.05|1.0
25|2.25|1.32|1.04|1.0
30|1.96|1.25|1.04|1.0

So indeed, it seems, that incorporating the info about the range of the sum of IVs does not bring a lot of improvement.

If we look at only the interesting cases, which I define as sum of IVs greater than 35. The results are:

Level|GoIV|+bestIV|+bestIV+bestIVval|+bestIV+bestIVval+rangeIV
---|---|---|---|---
15|2.51|1.41|1.23|1.18
20|2.06|1.3|1.16|1.13
25|1.74|1.21|1.12|1.09
30|1.53|1.16|1.1|1.07

Again, the improvements from including the range info are not great.

But, improvement from including the info about value of the best stat are rather big. The bottom line is that my impression was that this app was supposed to unearth the hidden information, all of it. Not hide some of it and there is an improvement at every stage here.

**Comment by nahojjjen** [comment]
Since the checkboxes have been implemented, after talking to @farkam135 we decided to close this issue. If the desire for the extra options is expressed by enough people, a new issue may be opened.
