### ISSUE TITLE
IV validation

### ISSUE THREAD

**Issue by magnumfonseca** [farkam135/GoIV#156]
![screen shot 2016-08-23 at 4 05 14 pm](https://cloud.githubusercontent.com/assets/14917264/17906065/0c668af6-694c-11e6-8a3c-f1266260d9f6.png)
![screenshot 23 de ago de 2016 16-04-52](https://cloud.githubusercontent.com/assets/14917264/17906200/b8cfe968-694c-11e6-91b3-e8f1083dcd6d.png)

Which of these is correct?

**Comment by hlplulustg** [comment]
Both are correct. GoIV shows you the combinations for the detected level 15.5. PokeAssistant shows you the combinations for the 16 because it doesn't know the pokemon level. You didn't toggle the 'Powered' field thats why PokeAssistant doesn't show you level 15.5 combinations.

**Comment by farkam135** [comment]
Make sure the red dot is overlapping the white pointer of the arc and then try again!
