### ISSUE TITLE
Options for less screen real estate

### ISSUE THREAD

**Issue by SunMar** [farkam135/GoIV#169]
Hi,

Loving the new 2.2.0 release :). Great improvements!

I've got some more suggestions for a some new options:
- Make showing the max CP when powered up and candy/stardust cost optional. It takes up quite a bit of real estate and I'm not really interested in those stats.
- Allow the number of possible Att/Def/Sta combinations shown to be chosen. Right now it shows 8 possibilities, but that also takes up quite a bit of real estate, I'd rather have it limited to 5 or maybe even 3.
- An option to instead of showing the possible combinations only show the possible range for each stat (so f.ex. Atk: 13~15 Def: 10~14 Sta: 08~12). Especially when there are a lot of possibilities I'm mostly interested in the possible ranges (what's the lowest and highest possible value of each stat) rather than all the possibilities.

My primary reason for limiting the used real estate on the screen is because right now you can't check the HP value and the overlay window also often falls partially over the arc which makes it not possible to check if the level is correct. Using less real estate so that the HP and level arc remain visible are great for combining with the new option to skip the input window. Also I before also read on reddit a post of someone with a 480p screen that too much real estate was used so this would be beneficial to users with a small or low resolution screen.

**Comment by DJCrapsody** [comment]
Refer to https://github.com/farkam135/GoIV/issues/162 for temporary bloat clean.
Why temporary? Because this: https://www.reddit.com/r/GoIV/comments/4z2a0v/second_design_draft_for_potential_result_screen/

**Comment by farkam135** [comment]
Redesign is up on 3.0.0!
