### ISSUE TITLE
IV button not appearing

### ISSUE THREAD

**Issue by Onoderra** [farkam135/GoIV#17]
I've got meizu m2
and of course, i activate "Allow Pop Up app"
but, the Iv button not appearing
![s60816-200145 1](https://cloud.githubusercontent.com/assets/21063780/17707018/a1cd4786-6408-11e6-9fa9-890562bb3107.jpg)

**Comment by jehy** [comment]
Did you select your level and press "start" button? I don't see recording sign in your notification area.

**Comment by deneektolentino** [comment]
I am also encountering this issue on android 5.1 using cherry mobile flare 4 (probably a rebranded china phone)
![screenshot_2016-08-17-02-10-11](https://cloud.githubusercontent.com/assets/8186436/17712404/53e1fa56-6428-11e6-95e8-8a25eda3862e.png)
![screenshot_2016-08-17-02-09-52](https://cloud.githubusercontent.com/assets/8186436/17712403/53cda07e-6428-11e6-8a6b-9f78f2f42665.png)
![screenshot_2016-08-17-02-09-37](https://cloud.githubusercontent.com/assets/8186436/17712402/53cd399a-6428-11e6-8773-6176671676b2.png)

**Comment by simonho1989** [comment]
It also appear on XiaoMi MI 3W (cancro), Galaxy Note 2, Pantech Vega No 6. What are they in common except they are old? DPI too low?

**Comment by farkam135** [comment]
Closed. Solution: go to Security app - Permissions - Permissions - Then select GoIV - allow the Popup notifications"

**Comment by deneektolentino** [comment]
![screenshot_2016-08-24-20-47-52](https://cloud.githubusercontent.com/assets/8186436/17938941/c0c24526-6a5a-11e6-941d-849e5bda55ae.png)

Hello. Goiv does not appear in app permissions in thr security settings

**Comment by simonho1989** [comment]
your app list is not complete, where are the google apps which also start with G?
