### ISSUE TITLE
If only one IV result is available, don't use average

### ISSUE THREAD

**Issue by rpgrca** [farkam135/GoIV#174]
If there's only result available, maybe MIN/AVG/MAX doesn't make sense, especially if the average is lower than MIN/MAX. It's confusing.

![screenshot_20160824-135818](https://cloud.githubusercontent.com/assets/15602473/17940028/9a903fd6-6a03-11e6-883d-0bd879c51ee3.png)

I know the new HUB might probably change this, but just want to make sure we won't have cases where AVG is lower than MIN threshold.

**Comment by nahojjjen** [comment]
Head shouldnt have the issue that average is less than min,  Ive commited a change that removes decimals

**Comment by Blaisorblade** [comment]
Agreed, this should be fixed on master by https://github.com/farkam135/GoIV/pull/163.
