### ISSUE TITLE
Use single line mode in tesseract

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#180]
I was reading up some tesseract stuff and it looks like it supports a "single line" mode. I think we should give it a shot. That way, it won't waste time trying to find the number of lines, the line spacing, etc. I couldn't find the java docs for it. Otherwise, I'd give it a shot.

**Comment by agrajaghh** [comment]
I had a quick look around, but couldn't find any hint in the official docs, I just found this "announcement" from 2009:
https://groups.google.com/forum/#!searchin/tesseract-ocr/single$20line|sort:relevance/tesseract-ocr/YWlt_nA6a88/TpEHC2b0i5gJ

> There will be explicit support for single line mode in 3.00, mostly for the benefit of ocropus.

**Comment by sarav** [comment]
@agrajaghh Paging Profile master. If you already have OCR profile numbers and if you feel like doing this.

**Comment by agrajaghh** [comment]
@sarav here you go:
![timing single line](https://cloud.githubusercontent.com/assets/5296073/18049453/abf6e19c-6de8-11e6-8875-aa7e017dc7b1.png)

I measured three pokemons each two times (with clearing data in between)
Single line mode seems faster (why should it be slower? :wink: ) but the measurements are showing quite a lot of variation, I couldn't figure out why.

https://github.com/agrajaghh/GoIV/tree/timing_single_line_off
https://github.com/agrajaghh/GoIV/tree/timing_single_line_on

**Comment by sarav** [comment]
Thanks @agrajaghh. The data is all over the place! I hope it's real savings. Oh well.
