### ISSUE TITLE
Mr. Mime identified as Mew

### ISSUE THREAD

**Issue by SimFriHS** [farkam135/GoIV#182]
Hi,

Decided to try your app and noticed a bug regarding the detection of Mr. Mime. 

Mr. Mime is incorrectly being identified as Mew as seen here![Normal Mr. Mime wrong detection](https://cloud.githubusercontent.com/assets/14929688/17965908/3bb98118-6abf-11e6-9d8f-ea0a6ab91343.png)

My apartment happens to sit on a Mr. Mime spawn so I have been able to test on several Mr. Mime and the bug is consistent across all the Mr. Mime caught so far (High and low CP values etc.) and renamed Mr. Mime as well![Renamed Mr. Mime wrong detection](https://cloud.githubusercontent.com/assets/14929688/17966083/0cac5dd6-6ac0-11e6-8e33-1f5836ba2f01.png)

Edit: GoIV is version 2.2.0

**Comment by Blaisorblade** [comment]
The bug when you rename it shows a bug with candy-based detection, which is relevant to #130.
I'm suspecting the dot in the name might confuse the code, but haven't checked. Luckily I have a Mr. Mew to debug this on.

**Comment by sarav** [comment]
Sorry, what's the candy name for Mr Mime?

**Comment by Blaisorblade** [comment]
The string is "MR. MIME CANDY". Note the space! Since we always take the first word (or always the 2nd in French/Spanish), we read MR. (or similar) hence the closest name is Mew.

**Comment by sarav** [comment]
Ahhhh... OK. We just need to change it to which word we throw away.

**Comment by sarav** [comment]
Btw, one thing I noticed is that we don't have "." in the whitelisted chars for OCR. So, the "." is probably being misrecognized too. But adding it might screw up OCR if it's starts interpreting normal letters as a ".".

**Comment by Blaisorblade** [comment]
Nicely enough, the OCR reads "MR MIME CANDY I", so removing the last word doesn't quite work. However, Mr. Mime is still closest to MR MIME CANDY, so it kind of works.

Why the I at the end? Because the image contains a dark piece of border 😢 .

**Comment by Blaisorblade** [comment]
@sarav fixed the "extra I" problem in https://github.com/farkam135/GoIV/pull/219/commits/c241b0ad54c02ed4a9e95d9e22cee7ef843c8a65. This is mitigated for 3.0.0 by the "correction learning", so I'm scheduling this issue for 3.1.0.
