### ISSUE TITLE
Candy detection doesn't support Spanish

### ISSUE THREAD

**Issue by MalkavSoft** [farkam135/GoIV#188]
Hi! 
In 2.1.0 GoIV detect correctly the pokemon name, even if you edit it, for example "Machop 76".
In 2.2.0 GoIV can't do that. It's supose to look at the candy name if doesn't get the name but it's not working, at least for me. 
Could be a game language problem? 
Thanks!

**Comment by Blaisorblade** [comment]
> Could be a game language problem?

What's your language? A screenshot of a misdetected pokemon, both alone and with the detection results, might be the easiest way to get all the info 😉

**Comment by Blaisorblade** [comment]
FWIW: this works well for me in English, but yes this is language dependent and we have a special case for French because it says "Bonbon Machop" rather than ""Machop Candy", so we must pick the 2nd word rather than the 1st. And of course we also need translations of the pokemon names :-|

**Comment by MalkavSoft** [comment]
Sorry, Im new at github and Im writing from mi phone. The game language is Spanish
Here they are. 
![screenshot_20160825-181823](https://cloud.githubusercontent.com/assets/21245122/17977065/71ca4536-6af0-11e6-907a-2ef583eb31fd.png)
![screenshot_20160825-181817](https://cloud.githubusercontent.com/assets/21245122/17977073/784cde46-6af0-11e6-94e0-76e4726d722e.png)

**Comment by MalkavSoft** [comment]
Looks like its the same problem that you have said. Like in french, in spanish the candy name is de second word. 
At least in spanish the pokemon names are the same. 
I can help with spanish translations if you need it.
