### ISSUE TITLE
clean github repo

### ISSUE THREAD

**Issue by agrajaghh** [farkam135/GoIV#19]
you might want to remove the excluded files from [.gitignore](https://github.com/farkam135/GoIV/blob/master/.gitignore)
You can use these commands:
```
git rm -r --cached .
git add .
git commit -am "Remove ignored files"
```

**Comment by chuparCh0pper** [comment]
Good Idea, I made a pull request https://github.com/farkam135/GoIV/pull/20

**Comment by agrajaghh** [comment]
that was fast, I'll close this one then...
