### ISSUE TITLE
Using new appraisal for better IV calculation

### ISSUE THREAD

**Issue by BHMath** [farkam135/GoIV#190]
Everything is here !

https://www.reddit.com/r/pokemongo/comments/4zbmji/i_know_some_of_you_have_been_struggling_to_figure/

Maybe new dropbox before checking iv

**Comment by Blaisorblade** [comment]
We've been thinking about this. Feel free to join the discussion in #153. Closing this as duplicate.

Also, the issue tracker allows searching for issues to find existing ones. 😉
