### ISSUE TITLE
Candy Detection Support

### ISSUE THREAD

**Issue by DJCrapsody** [farkam135/GoIV#193]
### Languages supported by Pokemon GO
Language (Locale*)|Format|Require Fix
:--|:--|:--
English (en)|Pokemon Candy|NO
Japanese (ja)|PokemonCandy (No spaces between words, Candy is written with 3 Japanese words)|YES (NEED TO BE FIXED)
Smplified Chinese (zh-cn)|UNRELEASED|UNRELEASED
Traditional Chinese (zh-tw)|UNRELEASED|UNRELEASED
French (fr)|Candy Pokemon|YES (FIXED)
German (de)|Pokemon Candy|NO
Italian (it)|Candy Pokemon|YES (FIXED)
Spanish (es)|Candy Pokemon|YES (FIXED)

*Based on Android strings 'values-xx' (up to language unless country is required to identify different language styles, i.e. Simplified Chinese and Traditional Chinese), default being 'values' (without language or country). GoIV and Pokemon GO is defaulted in English (en) language.

Referenced from: http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_GO#In_other_languages

**Comment by Blaisorblade** [comment]
I've fixed the case for Italian, and I'm fixing #182...

**Comment by DJCrapsody** [comment]
It's ok, it's a collab, everyone can work on anything. As for the issue, will be taking info from reddit.

**Comment by DJCrapsody** [comment]
Thread reference: https://www.reddit.com/r/GoIV/comments/4zlfwd/candy_detection/

**Comment by DJCrapsody** [comment]
Updated OP of issue with languages supported by Pokemon GO. There are 3 languages yet to be tested.

**Comment by DJCrapsody** [comment]
https://github.com/farkam135/GoIV/pull/209 would enable OCR to read Japanese pokemons.

**Comment by Blaisorblade** [comment]
Closing for now, as no further reports surfaced and #209 was merged.
