### ISSUE TITLE
Stop keyboard from popping up when app is launched

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#197]
In the apk built from the latest code (from this commit: https://github.com/farkam135/GoIV/commit/1aa4e60fa69b8788c5c34318a6cc6fa5f253bcad -- not 2.2.0) they keyboard automatically pops up when the app is launched. On phones with smaller screens, this blocks the "Start" button. Quite annoying. Please don't set the focus on the text box by default. No idea how to fix UI, otherwise, I'd do it myself.

**Comment by oskomonzon** [comment]
I have a fix working on the UI branch. Adding android:windowSoftInputMode="stateHidden" to the MainActivity in manifest does the trick.

**Comment by nahojjjen** [comment]
Im closing this issue even though its not on master yet, because the fix is in the new result ui implementation branch

**Comment by Blaisorblade** [comment]
I've now edited the #198 so this will be closed exactly when the PR is in 😉
