### ISSUE TITLE
Add a way to copy stats to clipboard

### ISSUE THREAD

**Issue by Jabe** [farkam135/GoIV#2]
Copy to clipboard would be great. For example, pressing and holding the possible combinations list creates some kind of compact string (len <= 12) of the stats and copies it to the clipboard.

A configurable format for the string or multiple community provided presets would be fantastic. Something like "[truncated_pokename] [min_percent]-[max_percent]%", "[truncated_pokename] [avg_percent]", "[avg_percent] [min_A] [min_D] [min_S]" and so on.

Cheers!

**Comment by coldwaterq** [comment]
If this happens we should make it so the app can read those specific truncated names whenever possible as well.

**Comment by farkam135** [comment]
IV range now copied to clipboard on check iv, customization of what is copied might be added later for now closing this!

**Comment by Jabe** [comment]
Wow, amazing customization options in 3.3.0!
👍
