### ISSUE TITLE
Simplify intent flow to prevent bugs

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#203]
Sometimes IV button still won't show on pokemons. Reason: `Pokefly.infoShownSent` sometimes gets stuck to `true`, because the `MainActivity` still doesn't answer with the pokemon screenshot.

BTW, we're also getting the screenshot twice for no reason it seems (with copy-pasted code), you'd think once would be enough for both detecting "this is a pokemon" and getting its stats?

I've just gotten it again when I accidentally suspended the apps (by pressing the home button); I suspect we can't assume intent delivery is guaranteed. In that case, the current flow needs rearchitecting even more.

I think this will be fixed by @sarav's refactorings of the intent flow.

**Comment by Blaisorblade** [comment]
In a twist, now I've observed `MainActivity.readyForNewScreenshot` being stuck to `false`.
(BTW this is all under debugging, but I think the bugs are still there, just easier to trigger with a debugger).

**Comment by sarav** [comment]
Yeah, I'd say, just wait for my un-Intent-ional fixes for this one.
