### ISSUE TITLE
Feedback regarding latest build (correct IV guessed, no possible IV, colors)

### ISSUE THREAD

**Issue by rpgrca** [farkam135/GoIV#217]
Just tried the latest code to check if it fixed the dot misalign (it does in Note 5 at least), quite nice! Leaving here some general feedback about it.

![2016-08-27 02 02 54_](https://cloud.githubusercontent.com/assets/15602473/18024490/fca4d1a2-6be1-11e6-8ac6-502ddc44b49b.jpg)

1) If the correct IV has been guessed, I believe it would be much more useful to show the IVs instead of showing the three boxes with the percentage.

![2016-08-27 02 03 04_](https://cloud.githubusercontent.com/assets/15602473/18024491/fca8418e-6be1-11e6-897e-010decdfbd3c.jpg)

I'm assuming the majority of people would end up expanding the combinations to check how the IV end up looking, so by showing the result in the main screen you prevent people from having to do an extra click.

~~2) If there's 0 possible combinations (like, clicked the wrong appraisal or had the wrong level, etc), maybe the "Show All" link should be disabled / not appear at all, since it shows an empty screen only. Also noticed that if you have too many results possible, it won't show any (like a L1 bulbasaur that has 4096 possible combinations): the link should also be disabled there.~~

~~3) Blue text with black background is somewhat hard to see in the combo box with the pokemon names.~~

**Comment by oskomonzon** [comment]
Hey, thanks for the feedback. We are currently doing lots of quick iterations over the new changes (lots of them). So we really appreciate users input.

1 - I agree, maybe we can incorporate something different when there is a single match. Something cheerful to make the user feel awesome :P
2 - About this one, I think we need to do a few more passes and consider the best approach. Maybe we shouldn't even display a result screen if there's nothing to show.
3 - It's already addressed :+1: 

Again, thanks for the feedback and keep up the good work.

**Comment by rpgrca** [comment]
Geez, nice to see I'm not the only Ingresser who's playing Pokemon ;-) Roberto here ;-)

Couple of crashes:

4) Start GoIV (with "Launch Pokemon Go" disabled to make it faster), kill it. Restart it, kill it again and it will crash.

5) Textboxes for CP / HP don't have input limit, inputting a large number crashes the application when checking IVs.

**Comment by oskomonzon** [comment]
Made a quick fix for 2: If no results inform the user and keep the inputs dialog. (Pending review)
I'll take a look at 5) since that seems to be an easy fix (falling asleep right now).

**Comment by rpgrca** [comment]
6) Dialogs don't disappear if application is switched (but the IV button does).

7) The IV result list has "columns" (from left to right) attack, defense and stamina, but it's sorted from right to left (stamina, defense, attack), so at first glance the list looks really messy. Ideally it should be sorted from left to right (that's the natural scanning direction for western cultures) or by IV percentage, although some might prefer having the column that have been appraised colored and sorted by it (so that the result list would be sorted by DEF if the Defense checkbox has been ticked).

![2016-08-27 03 25 05](https://cloud.githubusercontent.com/assets/15602473/18024902/1368e666-6bed-11e6-8761-22554d523ae0.jpg)

I know, having such a long list is not useful at all (especially if you can't even copy it), but keeping it "untidy" isn't helping at all.

**Comment by sarav** [comment]
(7) is due to the way the IV list is calculated. We "could" sort that list again, but that's extra work == extra power consumption. I'm not sure if the IV calculation math is simple enough to transform it to loop through the attack IVs first. I'll check it out later to see if it's possible.

**Comment by DJCrapsody** [comment]
7) Technically, attack is sorted first, followed by defense then stamina, that's why the output is sorted by stamina. We could reverse the sorting process, ending with attack so attack would he the last sorted attribute.

**Comment by sarav** [comment]
Didn't realize we already sort. Anyway, as I said, I'll check if the math is simple enough to have attack as the outer loop (probably not).

**Comment by nahojjjen** [comment]
I think we intend to leave in 8, people want might to see how much CP the pokemon had before they evolved it.

**Comment by rpgrca** [comment]
@nahojjjen I guessed as much. Can you change it visually from +-100 to -100 at least?

10) Is the updater working? It won't continue downloading unless I keep the application on the foreground, switching it to the background will make the download stop, trying to continue it will just get a new copy downloaded, ended up with 8 or so update.apk files. And didn't run the apk installer after it finished downloading.

![2016-08-27 12 24 23](https://cloud.githubusercontent.com/assets/15602473/18027407/1b55f53e-6c39-11e6-9cfe-4a0b2fabca81.jpg)

**Comment by nahojjjen** [comment]
You could create new issues for 7,8,9, 11, 12, this thread is difficult to keep track of. Rest are solved or have their own issue threads as far as i can see.
