### ISSUE TITLE
Don't show refine [New UI] if the previous Pokemon is not the same type

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#218]
Was looking at a Magnemite and previous scan was Ryhorn. I'm seeing the refine option with "Last scan: Ryhorn".

We probably shouldn't show it if the last scan was a higher level too. Because you couldn't have "powered up" from a higher level.

**Comment by oskomonzon** [comment]
Additionally, it would make sense to also hide or disable the whole "See more" and "Refine" section if there's a single match for the IV calculations.

**Comment by Eccenux** [comment]
I don't understand the refine button (even when looking on the code).

Is it to do with apprise information? Then maybe move it to a separate "Apprise refine" section with selection.

If Refine button uses another scan to improve OCR then it should be on previous page (not on the results page). It would make more sense to be able to refine name, CP, HP scan (especially for Gastly). Maybe simply name it "Rescan" then.

If none of above is true :-) then there should some info button on what does it refine and based on what.

**Comment by Blaisorblade** [comment]
FWIW: Refine compares the current and the previous scan. The UX might indeed be unclear.

**Comment by Blaisorblade** [comment]
The main issue is fixed in https://github.com/farkam135/GoIV/pull/250, so closing. @oskomonzon are there other things here forgotten?
