### ISSUE TITLE
Dialogs don't disappear if application is switched (but the IV button does)

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#220]
Reported by @rpgrca in https://github.com/farkam135/GoIV/issues/217#issuecomment-242893214.

This is an old issue and it's not yet fixed fixed for 3.0.0, nor will it I think. But it's not even clear how to do it—once we've snapshotted the underlying Pokemon, we don't need the underlying app to be Pokemon Go.

However, most other Pokemon Go addendum apps do disappear (with or without bugs), and they don't even do screen caps. I guess they detect some other way whether Pokemon Go is active (looking at active programs perhaps?).
Also, importantly, they resume the previous state. Showing again the IV button wouldn't do it.

Finally, if we do this we need to make sure we don't break GoIV when you share a snapshot with it, since that _can_ work with Pokemon Go.

**Comment by Blaisorblade** [comment]
BTW, this should probably wait for #203. @sarav, any insight?

**Comment by sarav** [comment]
I don't think this is an important enough of a bug to fix. The use can just hit the back or cancel button and move on. AFAIK, the only way to reliably detect which app is on top is to use Accessibility permissions. And I'd rather not add more permissions to the app.

**Comment by rpgrca** [comment]
This could become somewhat of an improvement if you add a button in the main screen for "Manual input" or "standalone". Sometimes you just want to quickly check some stats, maybe a friend send you a screenshot or you saw some stats in some site and don't want to turn on Pokemon GO or take a screenshot to edit the information, just want a quick calculator (also, having the game open implies faster battery draining due GPS and data being exchanged.

**Comment by sarav** [comment]
@rpgrca , are we talking about the same thing anymore? I'm not sure I understand.

**Comment by rpgrca** [comment]
@sarav Kind of, obviously keeping the dialog even if the game is no longer running is a (low priority) bug. But that gave me an idea, you could eventually add a way to access the IV dialog from the main screen so that you can use it as a calculator without having to launch the game or take a screenshot (for example, if you have a list of pokemon data in a spreadsheet), which would eventually appear as it's now, the IV dialog now "owned" by GoIV  (so that if GoIV is switched, the dialog disappears) instead of being owned by the game itself.

**Comment by sarav** [comment]
@rpgrca You can kinda do that already if you "Start" GoIV and then share a screenshot with it. But only screenshot from your devices will have the detection work correctly. But keep in might you'll have to change trainer level to what it was when you took the screenshot, etc. This feature comes as part of adding the Google Now on Tap integration.

**Comment by rpgrca** [comment]
@sarav Yeah, could be a workaround, there's no need to know the level since you would only want the IV dialog to appear. A pity screenshots cannot be prefixed with the level of the player so that they are usable at a later time.

**Comment by nahojjjen** [comment]
Im closing this issue, the current behavior is arguably correct since it keeps the user input data in case he accidentally pressed the multitask or home button, if there's more discussion or argument that someone wants to add, please create a new github issue. //cleaning out old issues.
