### ISSUE TITLE
Updater won't run in background

### ISSUE THREAD

**Issue by rpgrca** [farkam135/GoIV#222]
Is the updater working correctly? It won't continue downloading unless I keep the application on the foreground, switching it to the background will make the download stop, trying to continue it will just get a new copy downloaded, ended up with 8 or so update.apk files, several corrupted. And didn't run the apk installer after it finished downloading.

![2016-08-27 12 24 23](https://cloud.githubusercontent.com/assets/15602473/18027407/1b55f53e-6c39-11e6-9cfe-4a0b2fabca81.jpg)

**Comment by Blaisorblade** [comment]
Good point on both things. I'm sorry we join all the Android apps where downloading in background stop, it's a common bug. Any ideas @rhari991 (you contributed the updater IIRC, sorry if I'm wrong)?
