### ISSUE TITLE
Don't reestimate current CP, consolidate CP/HP estimation formulas

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#227]
- [x] Code in https://github.com/farkam135/GoIV/blob/70ddd971654ef0c3c5989c5703084d7d4683e598/app/src/main/java/com/kamron/pogoiv/Pokefly.java#L685 uses `realRange.high` to recompute the current CP from the guessed IV, because it's not accessible. I've eyeballed the code and I think it'll compute the current CP*, but I'd prefer to simply use the one we know. The issue is that we need some refactoring to have access to the value.

*We selected the IVs so that the derived CP would be equal to the actual one.

- [ ] Also, the formulas for deriving CP from IVs are duplicated and we're using different copies of them when computing IVs from CP and when computing CP from IV. The calculation seem equivalent, but ideally we'd avoid that duplication.

**Comment by nahojjjen** [comment]
7e8a6eef344d94458562f1fa6adf0281bd3d9ad5 solved this
