### ISSUE TITLE
Select not only best IV, but also range (from Appraisal)

### ISSUE THREAD

**Issue by SunMar** [farkam135/GoIV#231]
It's great that GoIV now can take appraisals into account by being able to select the best IV('s) for a Pokemon, but is it possible to also add an option to select the IV range for the best IV('s)?

See http://www.serebii.net/pokemongo/appraisal.shtml to know what line will the Team Leader says means what the IV range of your best IV is.

Like right now it shows:

Appraisal narrowing (optional)
`[  ] Attack    [  ] Defense    [  ] HP`

It might be nice to add below that:
`[  ] 15    [  ] 13-14    [  ] 8-12    [  ] 0-7`

**Comment by SunMar** [comment]
I think you meant to reference #153 ?

Though how is it possible to express desire if that issue is closed? :)

**Comment by Blaisorblade** [comment]
Yeah sorry, #153. Technically you can still post there—but I'd say, you'd need to collect overwhelming support on Reddit for this.

**Comment by phate89** [comment]
Probably the current implemented is the most useful one but there are a lot of times that the individual state range helps a lot to also actually find the exact IV value..maybe some option user can disable (and choose their team)? I used it a lot at least personally

**Comment by Blaisorblade** [comment]
Frankly, I'm finding it'd be convenient for me too.
And now we know how to unclutter the GUI—we can just do the same as for advanced info.
We must only make sure the input dialog still fits under the HP line (#239).

**Comment by Blaisorblade** [comment]
Fixed in #368. Last discussion in #327.
