### ISSUE TITLE
Additional information does not account for the candy cost for actual evolutions

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#233]
Splitting this from #223. Right now we don't count how many candies it takes to actually evolve a Pokemon. That depends on us having that info in our resources, which is ongoing work for #184.

**Comment by sarav** [comment]
I personally wouldn't want it to include evolution cost though. I know that that'll be. I'm just trying to figure out how much candy I'd need after evolution to hit a CP. But this is a subjective opinion.

**Comment by Blaisorblade** [comment]
I suspect that's because you can account for evolution costs in your head—so you could also leave with the changed behavior.
We might want to show both entries, say, show `125+48=173` for 125 evolution cost (from two evolutions) + 48 candies for powering up.

**Comment by nahojjjen** [comment]
The candy cost is now included. I discussed with farkam as well.
