### ISSUE TITLE
[3.0.1] Killing the application makes it unusable thereafter

### ISSUE THREAD

**Issue by rpgrca** [farkam135/GoIV#234]
Coming from #217 4):

Start GoIV (with "Launch Pokemon Go" disabled to make it faster), kill it. Restart it, kill it again and it will crash.

It seems the crash itself is fixed. However, it would look as if GoIV stops working if you kill it just once: the IV button won't do anything and battery saver mode won't trigger detection. Only way to get it working again (from what I tried) was reinstalling.

**Comment by rpgrca** [comment]
As a sideline, the same happens sometimes when I turn off the service and then turn it on, the IV button won't work until I kill the application after stopping the service. Can't find how to do it, though.

**Comment by Blaisorblade** [comment]
> Start GoIV (with "Launch Pokemon Go" disabled to make it faster), kill it. Restart it, kill it again and it will crash.

In the OP, by "kill it", you meant "press STOP"? In that case, I think this is an instance of #203 and/or #230.

> As a sideline, the same happens sometimes when I turn off the service and then turn it on, the IV button won't work until I kill the application after stopping the service. Can't find how to do it, though.

That is, you don't know how to fully kill GoIV? I actually kill the app by going to the "recent app" list and sliding GoIV away, on stock Android 6.

**Comment by rpgrca** [comment]
> In the OP, by "kill it", you meant "press STOP"? In that case, I think this is an instance of #203 and/or #230.

Yes, killing means going to the recent app list and sliding the application away. The original error was that doing that twice would crash the application. That was fixed with 3.0, now it doesn't crash but the button becomes unresponsive.

> That is, you don't know how to fully kill GoIV? I actually kill the app by going to the "recent app" list and sliding GoIV away, on stock Android 6.
Yes, I know. While testing, there was one combination of starting/stopping/switching the service that made the button unresponsive as well. In this case, killing GoIV actually fixes the button instead of triggering the bug, which makes it harder to replicate the bug.
