### ISSUE TITLE
'Scanning failed, please scroll up...' message not always displayed. (minor)

### ISSUE THREAD

**Issue by Paxtez** [farkam135/GoIV#237]
Scrolling down slightly, so that CP is still visible, and then pushing the IV button will bring up 10/10/Mew and search results, without message.

I'm not sure which element is being searched for to display the button, but it might make more sense to only display the button if the window is scrolled to the correct position?

**Comment by Blaisorblade** [comment]
That message had been added in 4ee1aa7f031357bbdea8626b6bc8c216419b7be9, but apparently it was removed altogether 😢  👎

**Comment by DJCrapsody** [comment]
@nahojjjen @Blaisorblade have we added the string back?

**Comment by nahojjjen** [comment]
Im confused, isnt this in the master branch? https://github.com/farkam135/GoIV/blob/master/app/src/main/java/com/kamron/pogoiv/Pokefly.java#L1444

https://github.com/farkam135/GoIV/blob/master/app/src/main/res/values/strings.xml#L97

**Comment by Blaisorblade** [comment]
Thanks @nahojjjen, you're right.

> Scrolling down slightly, so that CP is still visible, and then pushing the IV button will bring up 10/10/Mew and search results, without message.

Now it's empty/empty/Mew with message:
![image](https://cloud.githubusercontent.com/assets/289960/18561027/62f3acd4-7b7e-11e6-8574-d8b92c48d16c.png)

Closing.
