### ISSUE TITLE
New scanning edit display obscures the HP.

### ISSUE THREAD

**Issue by Paxtez** [farkam135/GoIV#239]
The new scanning window (which looks great) is a little too tall; on the Galaxy S7 edge the window goes about halfway up the name.  I looks like if the CP / HP label was on the same line as the numbers it would make the window small enough to show the HP.

**Comment by DJCrapsody** [comment]
Temporarily you can scroll the Pokemon info up to check HP. The scan ends after the pop up appears, so moving to another screen will not affect the results.

**Comment by Blaisorblade** [comment]
The same happens on Nexus 5. 

> It looks like if the CP / HP label was on the same line as the numbers it would make the window small enough to show the HP.

Makes sense, but at least on Nexus 5 that's not enough! In my test, I'd need to drop the label on the level seekbar, and to put the pokemon name on the same line.

@oskomonzon What do you think?

**Comment by oskomonzon** [comment]
I'd like to see an screenshot. From what I read I think it's related to pixel density so accounting for that and scaling down the sizes may be the way to go. Maybe we are showing huge texts/buttons on those displays for no reason.

Here is an example of how I see it on most of my test devices: 
![screenshot_2016-08-28-01-39-24](https://cloud.githubusercontent.com/assets/10285769/18031636/cfb70e32-6cc0-11e6-9d44-aa3289c80419.png)

So if you guys can attach a few examples it will be really useful.
Fear not. We'll do more passes on the UI front until we get it right.

**Comment by SunMar** [comment]
Here on a Galaxy S6:

![image](https://cloud.githubusercontent.com/assets/8324268/18032892/c410e14e-6d14-11e6-9411-01d411510f0e.png)

**Comment by Blaisorblade** [comment]
@oskomonzon If we had the same text density, I'd think your screenshot is from a tablet/phablet screen. Screenshots from my Nexus 5:
![image](https://cloud.githubusercontent.com/assets/289960/18032902/667d147a-6d15-11e6-9a21-fa0ee77115bf.png)
![image](https://cloud.githubusercontent.com/assets/289960/18032903/6a03ccba-6d15-11e6-8c1c-c2c862a245b1.png)

**Comment by Eccenux** [comment]
Maybe hide apprise options in a group as "Advanced information" on results can be hidden. Both "Advanced information" and Apprise group should be hidden (closed) by default.

BTW. I think "Advanced information" should be more descriptive e.g. "Evolution and powerup".

**Comment by Blaisorblade** [comment]
> Both "Advanced information" and Apprise group should be hidden (closed) by default.
> BTW. I think "Advanced information" should be more descriptive e.g. "Evolution and powerup".

👍  to both.

> Maybe hide apprise options in a group as "Advanced information" on results can be hidden.

That saves only one line, I'd like to avoid that. But I was thinking of something like this for other appraisal infos.

**Comment by sarav** [comment]
Can we fix this before next release please? Maybe  add to milestone?

**Comment by nahojjjen** [comment]
Solution attempt in #294

**Comment by Blaisorblade** [comment]
#294 became #304 that became #311 and was merged. That improves things but is still not enough for me. Note the trapped whitespace between seekbar and "appraisal refining"—recovering that would be more than enough to uncover the missing HP line:

![image](https://cloud.githubusercontent.com/assets/289960/18111015/6fce6778-6f1c-11e6-8fb8-eee88088f672.png)

**Comment by Blaisorblade** [comment]
Testing current master, this is finally fixed! Closing.
