### ISSUE TITLE
Ensure settings (especially trainer level) are reloaded upon changes

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#241]
Right now they aren't necessarily. Approaches
- After #203, most of the processing will be in Pokefly. Then we could just restart Pokefly when changing settings.
- Alternatively, we could ensure all parts of the code that depend on settings are notified when the relevant settings change. That's certainly possible, it just requires lots of discipline and attention.

**Comment by Blaisorblade** [comment]
#266 is relevant; we should still ensure we react to settings changes though.

**Comment by nahojjjen** [comment]
Im closing this as a duplicate / subset of #467 , sorry if I misunderstood.
