### ISSUE TITLE
Added best moves to GoIV

### ISSUE THREAD

**Issue by simonho1989** [farkam135/GoIV#245]
http://i.imgur.com/wQVpDNu.png

I am a newbie android developer from Hong Kong. Thanks to the open source of GoIV, I just want to contribute a bit but I am not familiar with GitHub. Here is how I implement the move set in the expanded_result_box.xml. Here are the added code in Pokefly.java

My app(It is in Chinese)
https://play.google.com/store/apps/details?id=simonhcm.pkmonchattw2

 List<String> OFFENSIVE_QUICK_MOVE = new ArrayList<>(Arrays.asList("Vine Whip",
            "Vine Whip",
            "Vine Whip",
            "Scratch",
            "Scratch",
            "Wing Attack",
            "Bubble",
            "Water Gun",
            "Water Gun",
            "Bug Bite",
            "Bug Bite",
            "Bug Bite",
            "Bug Bite",
            "Bug Bite",
            "Bug Bite",
            "Tackle",
            "Wing Attack",
            "Wing Attack",
            "Tackle",
            "Bite",
            "Peck",
            "Steel Wing",
            "Poison Sting",
            "Bite",
            "Thunder Shock",
            "Spark",
            "Mud Shot",
            "Mud Shot",
            "Poison Sting",
            "Poison Sting",
            "Poison Jab",
            "Poison Sting",
            "Poison Jab",
            "Poison Jab",
            "Pound",
            "Pound",
            "Ember",
            "Ember",
            "Pound",
            "Pound",
            "Bite",
            "Wing Attack",
            "Razor Leaf",
            "Razor Leaf",
            "Razor Leaf",
            "Bug Bite",
            "Bug Bite",
            "Bug Bite",
            "Bug Bite",
            "Mud Slap",
            "Mud Slap",
            "Scratch",
            "Scratch",
            "Water Gun",
            "Water Gun",
            "Scratch",
            "Low Kick",
            "Bite",
            "Fire Fang",
            "Bubble",
            "Bubble",
            "Bubble",
            "Zen Headbutt",
            "Psycho Cut",
            "Psycho Cut",
            "Low Kick",
            "Low Kick",
            "Karate Chop",
            "Vine Whip",
            "Razor Leaf",
            "Razor Leaf",
            "Bubble",
            "Poison Jab",
            "Rock Throw",
            "Mud Slap",
            "Mud Slap",
            "Ember",
            "Ember",
            "Water Gun",
            "Water Gun",
            "Spark",
            "Spark",
            "Cut",
            "Peck",
            "Feint Attack",
            "Lick",
            "Frost Breath",
            "Poison Jab",
            "Poison Jab",
            "Tackle",
            "Frost Breath",
            "Lick",
            "Shadow Claw",
            "Shadow Claw",
            "Rock Throw",
            "Pound",
            "Zen Headbutt",
            "Bubble",
            "Metal Claw",
            "Spark",
            "Spark",
            "Confusion",
            "Zen Headbutt",
            "Mud Slap",
            "Mud Slap",
            "Rock Smash",
            "Rock Smash",
            "Lick",
            "Tackle",
            "Tackle",
            "Mud Slap",
            "Mud Slap",
            "Pound",
            "Vine Whip",
            "Mud Slap",
            "Water Gun",
            "Water Gun",
            "Mud Shot",
            "Poison Jab",
            "Water Gun",
            "Water Gun",
            "Zen Headbutt",
            "Fury Cutter",
            "Pound",
            "Thunder Shock",
            "Ember",
            "Fury Cutter",
            "Tackle",
            "Splash",
            "Bite",
            "Frost Breath",
            "Pound",
            "Tackle",
            "Water Gun",
            "Thunder Shock",
            "Ember",
            "Tackle",
            "Water Gun",
            "Water Gun",
            "Scratch",
            "Mud Shot",
            "Bite",
            "Lick",
            "Frost Breath",
            "Thunder Shock",
            "Ember",
            "Dragon Breath",
            "Dragon Breath",
            "Dragon Breath",
            "Psycho Cut",
            "Pound"));

```
List<String> OFFENSIVE_CHARGE_MOVE = new ArrayList<>(Arrays.asList("Sludge Bomb",
        "Solar Beam",
        "Solar Beam",
        "Flamethrower",
        "Flamethrower",
        "Fire Blast",
        "Aqua Tail",
        "Hydro Pump",
        "Hydro Pump",
        "Struggle",
        "Struggle",
        "Bug Buzz",
        "Struggle",
        "Struggle",
        "Sludge Bomb",
        "Aerial Ace",
        "Aerial Ace",
        "Hurricane",
        "Body Slam",
        "Hyper Beam",
        "Drill Peck",
        "Drill Run",
        "Sludge Bomb",
        "Gunk Shot",
        "Thunder",
        "Thunder",
        "Rock Slide",
        "Earthquake",
        "Sludge Bomb",
        "Sludge Bomb",
        "Earthquake",
        "Sludge Bomb",
        "Sludge Bomb",
        "Earthquake",
        "Moonblast",
        "Moonblast",
        "Flamethrower",
        "Fire Blast",
        "Body Slam",
        "Hyper Beam",
        "Sludge Bomb",
        "Poison Fang",
        "Sludge Bomb",
        "Petal Blizzard",
        "Solar Beam",
        "Seed Bomb",
        "Solar Beam",
        "Signal Beam",
        "Bug Buzz",
        "Dig",
        "Earthquake",
        "Body Slam",
        "Play Rough",
        "Aqua Tail",
        "Hydro Pump",
        "Cross Chop",
        "Cross Chop",
        "Flamethrower",
        "Fire Blast",
        "Body Slam",
        "Scald",
        "Hydro Pump",
        "Psyshock",
        "Shadow Ball",
        "Psychic",
        "Cross Chop",
        "Cross Chop",
        "Cross Chop",
        "Sludge Bomb",
        "Sludge Bomb",
        "Solar Beam",
        "Water Pulse",
        "Hydro Pump",
        "Rock Slide",
        "Stone Edge",
        "Earthquake",
        "Fire Blast",
        "Fire Blast",
        "Psychic",
        "Psychic",
        "Thunderbolt",
        "Flash Cannon",
        "Leaf Blade",
        "Drill Peck",
        "Drill Peck",
        "Aqua Tail",
        "Blizzard",
        "Sludge Bomb",
        "Gunk Shot",
        "Water Pulse",
        "Blizzard",
        "Sludge Bomb",
        "Sludge Wave",
        "Sludge Wave",
        "Stone Edge",
        "Psychic",
        "Psychic",
        "Water Pulse",
        "X-Scissor",
        "Thunderbolt",
        "Thunderbolt",
        "Psychic",
        "Solar Beam",
        "Bone Club",
        "Earthquake",
        "Brick Break",
        "Brick Break",
        "Hyper Beam",
        "Sludge Bomb",
        "Sludge Bomb",
        "Stomp",
        "Earthquake",
        "Hyper Beam",
        "Solar Beam",
        "Earthquake",
        "Dragon Pulse",
        "Hydro Pump",
        "Aqua Tail",
        "Megahorn",
        "Power Gem",
        "Hydro Pump",
        "Psychic",
        "Bug Buzz",
        "Psyshock",
        "Thunder",
        "Fire Blast",
        "X-Scissor",
        "Earthquake",
        "Struggle",
        "Hydro Pump",
        "Blizzard",
        "Struggle",
        "Body Slam",
        "Hydro Pump",
        "Thunder",
        "Fire Blast",
        "Signal Beam",
        "Brine",
        "Hydro Pump",
        "Aqua Tail",
        "Stone Edge",
        "Hyper Beam",
        "Hyper Beam",
        "Blizzard",
        "Thunder",
        "Fire Blast",
        "Aqua Tail",
        "Dragon Pulse",
        "Dragon Claw",
        "Psychic",
        "Psychic"));
List<String> DEFENSIVE_QUICK_MOVE = new ArrayList<>(Arrays.asList("Tackle",
        "Razor Leaf",
        "Razor Leaf",
        "Ember",
        "Ember",
        "Ember",
        "Bubble",
        "Water Gun",
        "Water Gun",
        "Tackle",
        "Tackle",
        "Confusion",
        "Poison Sting",
        "Poison Sting",
        "Poison Jab",
        "Tackle",
        "Steel Wing",
        "Steel Wing",
        "Tackle",
        "Quick Attack",
        "Quick Attack",
        "Steel Wing",
        "Acid",
        "Acid",
        "Quick Attack",
        "Spark",
        "Mud Shot",
        "Metal Claw",
        "Poison Sting",
        "Poison Sting",
        "Poison Jab",
        "Peck",
        "Poison Jab",
        "Poison Jab",
        "Zen Headbutt",
        "Zen Headbutt",
        "Ember",
        "Ember",
        "Feint Attack",
        "Feint Attack",
        "Quick Attack",
        "Wing Attack",
        "Razor Leaf",
        "Razor Leaf",
        "Razor Leaf",
        "Bug Bite",
        "Bug Bite",
        "Confusion",
        "Confusion",
        "Mud Slap",
        "Mud Slap",
        "Scratch",
        "Feint Attack",
        "Zen Headbutt",
        "Confusion",
        "Scratch",
        "Karate Chop",
        "Ember",
        "Fire Fang",
        "Bubble",
        "Bubble",
        "Bubble",
        "Zen Headbutt",
        "Confusion",
        "Confusion",
        "Karate Chop",
        "Karate Chop",
        "Bullet Punch",
        "Acid",
        "Razor Leaf",
        "Razor Leaf",
        "Bubble",
        "Poison Jab",
        "Rock Throw",
        "Mud Slap",
        "Mud Slap",
        "Ember",
        "Ember",
        "Confusion",
        "Confusion",
        "Spark",
        "Spark",
        "Cut",
        "Quick Attack",
        "Steel Wing",
        "Ice Shard",
        "Ice Shard",
        "Poison Jab",
        "Poison Jab",
        "Ice Shard",
        "Ice Shard",
        "Sucker Punch",
        "Shadow Claw",
        "Shadow Claw",
        "Rock Throw",
        "Confusion",
        "Confusion",
        "Bubble",
        "Metal Claw",
        "Tackle",
        "Tackle",
        "Confusion",
        "Confusion",
        "Mud Slap",
        "Mud Slap",
        "Rock Smash",
        "Rock Smash",
        "Zen Headbutt",
        "Tackle",
        "Tackle",
        "Mud Slap",
        "Mud Slap",
        "Zen Headbutt",
        "Vine Whip",
        "Mud Slap",
        "Bubble",
        "Water Gun",
        "Peck",
        "Poison Jab",
        "Tackle",
        "Tackle",
        "Confusion",
        "Steel Wing",
        "Frost Breath",
        "Thunder Shock",
        "Ember",
        "Rock Smash",
        "Tackle",
        "Splash",
        "Bite",
        "Ice Shard",
        "Pound",
        "Tackle",
        "Water Gun",
        "Thunder Shock",
        "Ember",
        "Tackle",
        "Water Gun",
        "Mud Shot",
        "Scratch",
        "Mud Shot",
        "Steel Wing",
        "Zen Headbutt",
        "Frost Breath",
        "Thunder Shock",
        "Ember",
        "Dragon Breath",
        "Dragon Breath",
        "Steel Wing",
        "Confusion",
        "Pound"));
List<String> DEFENSIVE_CHARGE_MOVE = new ArrayList<>(Arrays.asList("Sludge Bomb",
        "Solar Beam",
        "Solar Beam",
        "Flamethrower",
        "Flamethrower",
        "Flamethrower",
        "Aqua Tail",
        "Hydro Pump",
        "Flash Cannon",
        "Struggle",
        "Struggle",
        "Bug Buzz",
        "Struggle",
        "Struggle",
        "Sludge Bomb",
        "Aerial Ace",
        "Aerial Ace",
        "Hurricane",
        "Hyper Fang",
        "Hyper Beam",
        "Drill Peck",
        "Drill Run",
        "Sludge Bomb",
        "Dark Pulse",
        "Thunderbolt",
        "Thunder Punch",
        "Dig",
        "Earthquake",
        "Sludge Bomb",
        "Sludge Bomb",
        "Earthquake",
        "Sludge Bomb",
        "Sludge Bomb",
        "Earthquake",
        "Moonblast",
        "Dazzling Gleam",
        "Flamethrower",
        "Flamethrower",
        "Play Rough",
        "Play Rough",
        "Sludge Bomb",
        "Poison Fang",
        "Sludge Bomb",
        "Petal Blizzard",
        "Solar Beam",
        "Seed Bomb",
        "Solar Beam",
        "Signal Beam",
        "Bug Buzz",
        "Dig",
        "Earthquake",
        "Body Slam",
        "Play Rough",
        "Aqua Tail",
        "Hydro Pump",
        "Low Sweep",
        "Low Sweep",
        "Flamethrower",
        "Flamethrower",
        "Body Slam",
        "Scald",
        "Hydro Pump",
        "Psyshock",
        "Psybeam",
        "Psychic",
        "Low Sweep",
        "Brick Break",
        "Submission",
        "Sludge Bomb",
        "Sludge Bomb",
        "Solar Beam",
        "Water Pulse",
        "Hydro Pump",
        "Dig",
        "Dig",
        "Earthquake",
        "Fire Blast",
        "Fire Blast",
        "Psychic",
        "Psychic",
        "Thunderbolt",
        "Flash Cannon",
        "Leaf Blade",
        "Drill Peck",
        "Drill Peck",
        "Aqua Tail",
        "Blizzard",
        "Sludge Bomb",
        "Sludge Wave",
        "Water Pulse",
        "Blizzard",
        "Sludge Bomb",
        "Shadow Ball",
        "Shadow Ball",
        "Rock Slide",
        "Psychic",
        "Psychic",
        "Water Pulse",
        "Water Pulse",
        "Thunderbolt",
        "Thunderbolt",
        "Psychic",
        "Solar Beam",
        "Dig",
        "Dig",
        "Low Sweep",
        "Brick Break",
        "Hyper Beam",
        "Sludge Bomb",
        "Sludge Bomb",
        "Bulldoze",
        "Earthquake",
        "Hyper Beam",
        "Solar Beam",
        "Stomp",
        "Flash Cannon",
        "Hydro Pump",
        "Water Pulse",
        "Drill Run",
        "Bubble Beam",
        "Psybeam",
        "Psychic",
        "Bug Buzz",
        "Ice Punch",
        "Thunder Punch",
        "Flamethrower",
        "X-Scissor",
        "Earthquake",
        "Struggle",
        "Dragon Pulse",
        "Ice Beam",
        "Struggle",
        "Dig",
        "Water Pulse",
        "Thunderbolt",
        "Flamethrower",
        "Signal Beam",
        "Ancient Power",
        "Rock Slide",
        "Ancient Power",
        "Water Pulse",
        "Hyper Beam",
        "Hyper Beam",
        "Ice Beam",
        "Thunderbolt",
        "Flamethrower",
        "Twister",
        "Dragon Pulse",
        "Dragon Pulse",
        "Psychic",
        "Psychic"));

@BindView(R.id.att_skill)
TextView att_skill;
@BindView(R.id.def_skill)
TextView def_skill;

    att_skill.setText(OFFENSIVE_QUICK_MOVE.get(pokemonList.getSelectedItemPosition())+" + "+OFFENSIVE_CHARGE_MOVE.get(pokemonList.getSelectedItemPosition()));
    def_skill.setText(DEFENSIVE_QUICK_MOVE.get(pokemonList.getSelectedItemPosition())+" + "+DEFENSIVE_CHARGE_MOVE.get(pokemonList.getSelectedItemPosition()));
```

**Comment by oskomonzon** [comment]
I like the idea, it goes in line with issue #69. But I'm concerned about the implementation, there is a list of things to consider in order to pick the best approach:

1. There are divergent studies about optimal movesets, it's important to pick a reliable one with enough information to backup his claims.
2. Maintainability could be a problem in the scenario of a sudden balance change. This is espacially true for the offline flavor of GoIV where the application would require an update to get the latest values right.
3. Localization, we need to be able to translate every move. This one shouldn't be an issue but it's something to consider.

Overall, I really like the idea and I think it would be useful for our userbase.

**Comment by simonho1989** [comment]
my moveset is based on http://pokemongo.gamepress.gg/pokemon-list

**Comment by Blaisorblade** [comment]
To sum up, the idea is simply to show the best offensive and defensive moveset, taken from that website. Personally I've used that website in the past and it seems careful (though I'm no expert).

I share @oskomonzon's concerns on updates. Is there a way to scrape the move database from the website for generation? Or, ideally, to query it for the newest database? I'm not sure we can support this well for the offline version: movesets have already changed twice.

**Comment by Eccenux** [comment]
I don't think there is room to push pokedex into current GoIV data, but if you want DPS data then I have it in my app here:
https://github.com/Eccenux/MyPokedex/tree/master/workdir/app/data

Best move calculations are complicated:
1. For given pokemon there is a fixed set of possible moves/attacks. So if you want to show a best move it has to be a best move for given pokemon.
2. Based on the pokemon type there is a STAB bonus. So you have to calculate DPS based on pokemon and attack type.
3. (not yet solved in my app) For different opponents different attacks might be better. This is due to different effectiveness of types.

Overall I don't think GoIV would be the best app implement attacks calculation. Also because on the pokemon screen you don't see attacks until you scroll down.

**Comment by Eccenux** [comment]
I mean GUI above. IV and DPS are separate things. I don't see a place where we could show more information about attacks. Maybe a different activity for that.

**Comment by Blaisorblade** [comment]
I'm not sure everything needs to be in the same app, just conveniently accessible on mobile. We could link to some other app for this—I would even propose yours @Eccenux, but I don't find how to install it/use it from the README. 

@Eccenux Are you using the same formulas as GamePress? Instead of querying them, if you (or somebody) offers data in JSON format (or XML/YAML/whatever) and you or somebody hosts it, we could query that instead of GamePress. Of course we'd credit whatever webservice we use.

> IV and DPS are separate things.

Absolutely. Yet you want to consider both to select good pokemons. Designing a good UX for this is not easy.

Since it's hard to OCR moves, the only thing that's convenient about GoIV is that it's accessible while playing PG. Loading a browser would probably take too much RAM and kill PG/GoIV (Chrome certainly kills PG 50% of times for me).

**Comment by Blaisorblade** [comment]
> Designing a good UX for this is not easy.

But let me add: a UX to show the best movesets in general, as proposed in this issue, is easy—add it under advanced info (and maybe adjust things).
That's not always what you want, but it's often useful—and at least for me it's almost enough.

**Comment by Eccenux** [comment]
With current GUI it might fit in. I would make a separate group for that. Both would act as accordion (one is shown, others are closed). This is what I show on pokemon:
http://m.enux.pl/myPokedex/#page-pokemonCard?id=1
Obviously this is much larger for mew ;-)
http://m.enux.pl/myPokedex/#page-pokemonCard?id=151

So to save some spaces maybe show two best attacks?

As for data source I would prefer for it to be static. I don't want to kill my server ;-). But if you it is possible to get it from Github then be my guest ;-). I'm also not sure if that is not against Github ToU. If it is OK, then source JSON data is here:
https://github.com/Eccenux/MyPokedex/tree/master/data_builder/data

**Comment by sarav** [comment]
I actually prefer for it to be part of GoIV so that only the relevant info pops up based on what pokemon we are viewing. For example, I get a pokemon and I check the IV to decide if I should transfer it. But the same applies after evolves too. If I evolve a pokemon with a shitty move set, I want to throw it away. 

I understand the moveset maintenance issue though. Maybe we can put a "moveset last update: xx/xx/xx" on the main screen? So that people know if it's out of date?

**Comment by podkot** [comment]
What do you think of an option to copy moveset rates to clipboard? E.g. for Lapras with Ice Shard / Blizzard it will be B for attack and A for defence (rates are taken from [gamepress](https://pokemongo.gamepress.gg/pokemon/131)).

Moveset rating seems to be more useful than IV. And it would be great to rename pokemons like `Lap ⑮⑮⑮ AA`

**Comment by nahojjjen** [comment]
A newer issue with further discussion seems to have popped up here: #576
