### ISSUE TITLE
Unable to build master - getShowConfirmationDialog missing

### ISSUE THREAD

**Issue by Eccenux** [farkam135/GoIV#253]
The line it's called from:
`if (!GoIVSettings.getSettings(getBaseContext()).getShowConfirmationDialog())`

I've double checked and there are no other occurrences of that function in `master` branch.

**Comment by Eccenux** [comment]
Hm... Seems like `@Getter` is not working for me... No idea why. Any help?

**Comment by Blaisorblade** [comment]
See https://github.com/farkam135/GoIV/blob/master/DEVELOPMENT.md:
> Install lombok-intellij-plugin (https://github.com/mplushnikov/lombok-intellij-plugin)

**Comment by Blaisorblade** [comment]
We might want to make those instructions more discoverable, but they're already linked from the README so I'm out of ideas. Suggestions?

**Comment by simonho1989** [comment]
I am a newbie developer, I actually cannot build the follow method in SettingActivity. Did I miss out something? I have include the following lines in the app level gradle dependency
    provided "org.projectlombok:lombok:1.16.10"
    apt "org.projectlombok:lombok:1.16.10"

    public void onSharedPreferenceChanged(SharedPreferences sharedPreferences, String key) {
        GoIVSettings.saveSettings(mContext, new GoIVSettings(
                sharedPreferences.getBoolean(GoIVSettings.LAUNCH_POKEMON_GO, true),
                sharedPreferences.getBoolean(GoIVSettings.SHOW_CONFIRMATION_DIALOG, true),
                sharedPreferences.getBoolean(GoIVSettings.MANUAL_SCREENSHOT_MODE, false),
                sharedPreferences.getBoolean(GoIVSettings.DELETE_SCREENSHOTS, true),
                sharedPreferences.getBoolean(GoIVSettings.COPY_TO_CLIPBOARD, false),
                sharedPreferences.getBoolean(GoIVSettings.SEND_CRASH_REPORTS, true),
                sharedPreferences.getBoolean(GoIVSettings.AUTO_UPDATE_ENABLED, true)));
    }

**Comment by Blaisorblade** [comment]
@simonho1989 It's the same problem. If you're building in Android Studio you need that lombok plugin, instructions are at that URL. If you have trouble following https://github.com/farkam135/GoIV/blob/master/DEVELOPMENT.md, at least mention which step failed.

**Comment by nahojjjen** [comment]
I'd like to point out that if you install the lombok plugin you will get an error that tells you 

 Annotation processing seems to be disabled for the project "GoIV".
         For  plugin to function correctly, please enable it under
         "Settings > Build > Compiler > Annotation Processors"

Which is nonsense, that setting does not exist in android studio, see issue on lombok: https://github.com/mplushnikov/lombok-intellij-plugin/issues/264

However from what I can tell, things work anyway.

**Comment by nahojjjen** [comment]
Blaisorblade linked to the plugin repo, here's the specific part that tells you how to install:

https://github.com/mplushnikov/lombok-intellij-plugin#plugin-installation

**Comment by DJCrapsody** [comment]
Annotation processing can only be enabled when no projects are open. Close to project then go to "Settings > Build > Compiler > Annotation Processors".

I will add this to DEVELOPMENT.md

**Comment by DJCrapsody** [comment]
https://github.com/farkam135/GoIV/pull/260 should help with devs trying to contribute

**Comment by nahojjjen** [comment]
I'm closing this issue because complete instructions have been given.
