### ISSUE TITLE
Add Travis integration

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#254]
I started testing it in my fork: https://travis-ci.org/Blaisorblade/GoIV
This only ensures the code builds, for both pushes and PRs. We could try adding tests but that's not easy.

**Comment by Blaisorblade** [comment]
/cc @harkin since he just asked for CI.
@farkam135 needs to flip the switch on his repo, but we can test things on mine meanwhile.

**Comment by harkin** [comment]
This makes me happy :)

**Comment by Blaisorblade** [comment]
We need some Crashlytics ID (which would be of some developer maybe?) and some certificates, not the official ones (which is probably much easier to setup)—the most annoying part would be ensuring this setup doesn't break the "real" releases. I have ideas there.
For Crashlytics, here that only works in my IDE, not on the command line, so I don't fully know how that works.

> The hard part is having the discipline to write them

Oh sure.

> As for tests, I'm a fan of them. There's not much work in setting the project up so that it has tests, you can run them with ./gradlew test (once they're there). 

What I meant: We either need to set up an emulator to run them on Android (which is experimental on Travis, and could slow builds down), or to have tests on the core logic that run on the usual JDK (we do have core logic that is Android-independent).

I've never done either (I've never really developed on Android before).

Moreover, the Java build systems I know don't include Gradle (I've only used Ant, a bit of Maven and SBT), so I wouldn't know how to set up things to build and test on a JDK.

**Comment by harkin** [comment]
> experimental on Travis

That sounds like 'flakey and unreliable' to me. 

I can set up the testing stuff. For simplicity I'll probably use [RoboElectric](http://robolectric.org/) which shadows the Android components so you can write tests for the JDK that still use Android components. No dice for things like UI testing though.

**Comment by Blaisorblade** [comment]
@harkin There's lots of logic that doesn't even use Android. If we can test that I'm happy. We can also try to separate business logic from the UI to allow testing more of it—that's a good idea anyway, isn't it?

**Comment by harkin** [comment]
For sure. Lets start simple and see if we need to mock android components often
