### ISSUE TITLE
Application can reach a state where IV button does nothing

### ISSUE THREAD

**Issue by nahojjjen** [farkam135/GoIV#256]
https://www.reddit.com/r/GoIV/comments/4zvnvh/version_301_hotfix_released/d6zgcut - several people have the issue

and another one:  https://www.reddit.com/r/GoIV/comments/4zvnvh/version_301_hotfix_released/d6zyu9x

Ive managed to get the bug once on my own S7, and I did not get any crashlog. I do not know how to reproduce the issue.

**Comment by Blaisorblade** [comment]
This used to crash, now it just makes the application stuck. It should be an effect of #203 and #230. Overlaps with #234.

**Comment by nahojjjen** [comment]
Then ill close this as a duplicate
