### ISSUE TITLE
Wrong apprise filtering

### ISSUE THREAD

**Issue by Eccenux** [farkam135/GoIV#257]
See attached image. One more stat fits when filtering by defense

![tmp_31385-screenshot_20160828-1645011643765456](https://cloud.githubusercontent.com/assets/1045235/18034522/7949a332-6d3f-11e6-92f8-b854e7252a81.png)
![tmp_31385-screenshot_20160828-164514-1862554662](https://cloud.githubusercontent.com/assets/1045235/18034524/7ebb9f46-6d3f-11e6-8c43-b0b20d211924.png)

**Comment by hlplulustg** [comment]
Seems correct. Where's the error?

**Comment by nahojjjen** [comment]
All rows except last two have stamina > defense, so if you're filtering by defense, you should only get the two bottom results.

**Comment by DJCrapsody** [comment]
Seems okay to me.

**Comment by nahojjjen** [comment]
Closed until someone can motivate why the current behavior is wrong.

**Comment by Eccenux** [comment]
Right, OK. I was looking at the attack vs defense.
