### ISSUE TITLE
In app FAQ

### ISSUE THREAD

**Issue by nahojjjen** [farkam135/GoIV#26]
I notice that most question threads submitted to /r/goiv are repeats of previously posted questions, would there be any idea in creating a FAQ page in the app, or link to the subreddit faq? https://www.reddit.com/r/GoIV/wiki/index

**Comment by mattaereal** [comment]
Submited pull request to apply this. And also gave toc structure to all the readme.

Here is on my repo: https://github.com/mattaereal/GoIV/blob/299b2ab3f13556c43cf08e3b90b9288012bd4143/README.md

**Comment by farkam135** [comment]
Added
