### ISSUE TITLE
Request: Automate prefixing mon names with rating

### ISSUE THREAD

**Issue by crd** [farkam135/GoIV#261]
Rather than having users hit the IV button over and over, it would be cool if the app supported using the official gui to rename pokemon to prefix their names with their rating percentages.

**Comment by nahojjjen** [comment]
Are you suggesting that the application should rename the pokemon for the user?

**Comment by crd** [comment]
Not automatically, but yes.

**Comment by rpgrca** [comment]
Related to #55.

**Comment by Blaisorblade** [comment]
I suspect copying the name in the clipboard so you can paste it easily might be the best we can do. Clicking around the GUI is both really fragile and hard, it hopefully requires extra permissions, and I am afraid it also crosses into bot territory. Especially if Pokemon Go tried to detect if it's being played by humans or not.

As a personal opinion, I suspect doesn't stop anybody from implementing it, but I'm afraid it could cause the project (and its users) more trouble.

**Comment by nahojjjen** [comment]
I'm gonna close this since the only reasonable non-cheat / bot way to help with this as far as i can tell is related to #55

**Comment by crd** [comment]
I clearly hadn't thought through the ramifications. Thanks guys. I agree with the decision to close this.
