### ISSUE TITLE
First few Pokemon have wrong Base stats?

### ISSUE THREAD

**Issue by McAJBen** [farkam135/GoIV#27]
it looks like bulbasaurs base stats are actually the ones for abra?

**Comment by farkam135** [comment]
Good catch, this was caused when the pokemon names were put in as a resource. Originally the pokemon were added alphabetically, the resources has them by pokedex number so the names are now in pokedex order but the stats are still alphabetical. v1.3.0 has the correct stats and i'll be sure to fix this as well before next release.

**Comment by McAJBen** [comment]
My pull has it fixed, and also changes them to resources
