### ISSUE TITLE
Sort IV result list from left to right

### ISSUE THREAD

**Issue by rpgrca** [farkam135/GoIV#271]
Splitting from #217:

> The IV result list has "columns" (from left to right) attack, defense and stamina, but it's sorted from right to left (stamina, defense, attack), so at first glance the list looks really messy.
Ideally it should be sorted from left to right (that's the natural scanning direction for western cultures) or by IV percentage, although some might prefer having the column that have been appraised colored and sorted by it (so that the result list would be sorted by DEF if the Defense checkbox has been ticked).

![2016-08-27 03 25 05_](https://cloud.githubusercontent.com/assets/15602473/18024947/d65a35c0-6bee-11e6-830d-34555ac1732b.jpg)

**Comment by sarav** [comment]
My personal preference. If others like it, go for it?

Sort by IV%, followed by Att, Def, Sta. Don't have a strong opinion on appraisal field based sort.

**Comment by rpgrca** [comment]
How hard is to make the list sortable by clicking the header? Would mean displaying one row less since it overlaps with the notification bar if possible.

**Comment by sarav** [comment]
I feel like if we spend too much on making the UI fancy, the app will keep getting bloated. And with PoGo using up so much memory, we have to be a bit leaner.

**Comment by leppie** [comment]
Requested sorting with #341

**Comment by nahojjjen** [comment]
Since #341 discusses something which would make this obsolete & a lot has changes with the "all iv results" screen since this issue was posted, I'm closing this issue.

**Comment by nahojjjen** [comment]
Since #341 discusses something which would make this obsolete & a lot has changes with the "all iv results" screen since this issue was posted, I'm closing this issue.

**Comment by nahojjjen** [comment]
Since #341 discusses something which would make this obsolete & a lot has changes with the "all iv results" screen since this issue was posted, I'm closing this issue.
