### ISSUE TITLE
Small modifications on start screen

### ISSUE THREAD

**Issue by rpgrca** [farkam135/GoIV#273]
Splitting from #217:

> Limit level input to 2 digits (currently any number of them can be added).

> Change instructions when selecting battery saver mode (instructions continue to say "Press IV button" when it should be "take a screenshot", might confuse people who forgot they have turned the option on and then don't see the button anywhere).

**Comment by oskomonzon** [comment]
What do you guys think about a number picker instead? It may be the right UI element for this scenario.
Most users will set it up once and then only change it in increments of one at a time.

About the instructions we can add the missing string for that as a quick fix. But, depending on the ammount of features we end up adding to the app (there are a lot of cool ideas around), the best approach would be to get rid of those instructions and add a fully fledged tutorial/welcome screen/whatever. 

It would be a clean way to introduce and explain to the user new features after every update.

**Comment by DJCrapsody** [comment]
Number picker from 1 to 40 seems good.

**Comment by Blaisorblade** [comment]
> the best approach would be to get rid of those instructions and add a fully fledged tutorial/welcome screen/whatever.

That might be good. Development-wise, I guess that's probably better as soon as the core feature set starts stabilizing more—assuming that such a tutorial takes more effort and care to update than instructions here and there.

**Comment by rpgrca** [comment]
Just checked the latest code, somehow the number picker begins in level 1 with 1 highlighted (which gives the impression it can be edited. Also, the control makes (in my case) the screen larger, so you can't get to see the links nor the version of the program, you need to scroll the page (which isn't obvious since there's no scrollbar).

![2016-08-30 02 44 31](https://cloud.githubusercontent.com/assets/15602473/18074444/0e2f3b66-6e43-11e6-88a5-21ab5e06c2e1.jpg)

**Comment by Blaisorblade** [comment]
> which gives the impression it can be edited

I think that's correct—just tap on the number. That's also the standard behavior of this NumberPicker control. (https://developer.android.com/reference/android/widget/NumberPicker.html).

> Also, the control makes (in my case) the screen large

It's even worse here :-|, I hadn't realized a number picker works like that. Maybe we should reuse horizontal seekbars with +/- like elsewhere, but we'd also need a text field.

But the version could go elsewhere next to GoIV, and the links could move elsewhere.

**Comment by DJCrapsody** [comment]
We can use dropdown for worse case scenario.

**Comment by oskomonzon** [comment]
Or we can adjust/customize the control.

**Comment by Blaisorblade** [comment]
This something we can do for 3.1.0?

**Comment by oskomonzon** [comment]
@Blaisorblade I'll see what I can do tomorrow. I hope to have the time to fix it before the deadline.
To clarify, shouldn't be hard, we can do some UI trickery like scaling it down or something more robust like making a new skin for it. But it requires some thinking/testing to decide the best approach. Also there is Issue #309.

We'll figure it out :)

**Comment by Blaisorblade** [comment]
I split the 2nd part of the issue in #325 while the level input was tuned. I think we can close for 3.1.0 (let us know otherwise).
