### ISSUE TITLE
Adjust Evolution spinner in expanded info box

### ISSUE THREAD

**Issue by DJCrapsody** [farkam135/GoIV#312]
Previous attempt was unable to fix the alignment therefore reverted.

**Comment by Blaisorblade** [comment]
Not a blocker for the release, but would be nice in 3.1.

**Comment by Blaisorblade** [comment]
Here are two screenshot from current master (4c70007b6649247667753ba6967d890211810397) plus reverted 59b94362ed4f8e470853040f4d830167d2750a7f (hence, with the negative margins readded):
![image](https://cloud.githubusercontent.com/assets/289960/18111225/226b8c3e-6f1e-11e6-8c68-790a3ca77886.png)
![image](https://cloud.githubusercontent.com/assets/289960/18111230/24dadede-6f1e-11e6-87ab-1a68ddc89dfe.png)
