### ISSUE TITLE
Battery-saver mode is only force-enabled on 4.4 when entering settings

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#315]
To reproduce:
- start GoIV on Android 4.4
- press start
- observe a crash

To workaround:
- enter the settings menu (without having to touch anything), return, and start. Tis must be done only once IIUC, the issue stays fixed.

Solution approach:
- force battery-saver mode on when starting the MainActivity, not in settings.

**Comment by kaneki1985** [comment]
#342
