### ISSUE TITLE
SharedPrefs might need to be committed properly

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#317]
Almost none of the edits to SharedPrefs seem to be "committed". See what I did for userCorrections. When I implemented userCorrections saving across app launches, I found that if I didn't .commit() it, it wasn't saved. My guess is that since we save a lot more on SharedPrefs, some of the "keys" get saved when we update the next "key", but not all are saved.

I think that might be the reason for the bug where people can't get the app to work even after killing it (swiping it in Recents). There's nothing else that's preserved across app restarts. I think @nahojjjen  has hit this bug too?

**Comment by nahojjjen** [comment]
If you're talking about the bug where the iv button when clicked does nothing, and the button reappears after a short while, I've experienced it.

**Comment by Blaisorblade** [comment]
I'm unhappy with adding so much stuff to 3.1.0, but this seems also important.

**Comment by Blaisorblade** [comment]
Meanwhile: why does the app use 102MB data and 16.40 MB cache? That's a debug version, but the app itself is 33.30 MB only:
![image](https://cloud.githubusercontent.com/assets/289960/18126076/c4b70026-6f79-11e6-8e4d-9c79b3d903e3.png)

**Comment by sarav** [comment]
That's a lot of data! Not okay at all.

I hope it's corrupt preferences. And not userCorrections or crashalytics or auto updater. Otherwise, well have to kick those out.

**Comment by sarav** [comment]
Try adb dumpsys on the package and see if you get more info.

**Comment by Blaisorblade** [comment]
I've reviewed the APIs, and using `apply` like we do is fine, and officially recommended for the main thread (https://developer.android.com/reference/android/content/SharedPreferences.Editor.html#apply()). Closing the app won't interrupt saving. `apply` is asynchronous, so at worst is problematic if the entire phone crashes IIUC. We might still want to doing `commit` as long as this is not on the main thread.

We went from `commit` to `apply` in a369980b7102ea2da80d7d4f0e6710fe9797f838 (which doesn't have the best commit message frankly).

Finally, we're using a default PreferenceFragment to manipulate the settings. [Its docs](https://developer.android.com/reference/android/preference/PreferenceFragment.html) say:

> Shows a hierarchy of Preference objects as lists. These preferences will automatically save to SharedPreferences as the user interacts with them.

So this seems fine enough for 3.1.

**Comment by Blaisorblade** [comment]
Re `dumpsys` I'm not sure what you have in mind—couldn't find yet how to get info on saved data. Will have to take a closer look. And probably on a release build.

**Comment by sarav** [comment]
If others are sure the current API usage is correct, then someone who's sure should close this issue.

**Comment by Blaisorblade** [comment]
As the one who looked it up, closing.
