### ISSUE TITLE
Fix instructions for screenshot mode

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#325]
Splitting from #273 (which came from #217), since it didn't get attention there:

> Change instructions when selecting battery saver mode (instructions continue to say "Press IV button" when it should be "take a screenshot", might confuse people who forgot they have turned the option on and then don't see the button anywhere).

@DJCrapsody Do you think you can fix this by 3.1.0?

**Comment by DJCrapsody** [comment]
Ah I didn't catch this issue. Can we go for 3.2.0?

**Comment by Blaisorblade** [comment]
I don't think that should a problem.

**Comment by sarav** [comment]
Made irrelevant by #393
