### ISSUE TITLE
Add two extra spinners to appraisal box for the missing info input

### ISSUE THREAD

**Issue by nahojjjen** [farkam135/GoIV#327]
Now that the appraisal information is in a collapsible box in the input dialog, space is not the same issue as before for extra input components. I suggest adding a feature where the user selects which team he is on, and that he is given two spinner options that correspond to the team-leader feedback to further narrow down the result.

**Comment by oskomonzon** [comment]
Do you think we can have that working before the feature lock?
I'd love to have it before that since some users were pretty vocal about it missing (maybe it's a low minority, tho. But it would be nice adding it sooner or later even if it's not a priority).

**Comment by leppie** [comment]
I made a similar suggestion in my PR (#336), where you have a multi-state checkbox (uncheck, check, rank #1, etc). 

Was thinking the checkbox color could change based on the IV color determination from my PR.

**Comment by Eccenux** [comment]
Spinners with parts of phrases would be great. E.g. for Valour stats sum phrases should be:
37-45: simply amazes me
30-36: is a strong Pokemon
23-29: is a decent Pokemon
0-22: may not be great

Best stat spinner should be:
15: blown away
13-14: excellent stats
8-12: gets the job done
0-7: don't point to greatness

Choosing team should be on the first screen (same as player level).

**Comment by Blaisorblade** [comment]
I was thinking of rows of radiobuttons (see https://developer.android.com/guide/topics/ui/controls/radiobutton.html) with no options selected by default.
Advantage: one tap to pick a preference.
Disadvantage: you can't "go back" to unselected easily.

**Comment by Eccenux** [comment]
Radiobuttons are generally better, but in this case texts are too long. You won't be able to fit 4 radio buttons with text in a single row. Each option would have to be in a separate row. So in total there would have to be something like 10 rows (including labels).

**Comment by nahojjjen** [comment]
I have implemented this feature in my other branch, and osko and me is working on tweaking the ui.

**Comment by rpgrca** [comment]
I'm afraid it might be a bit too much to ask for someone to remember three or more piece of information regarding appraisal. Maybe it would be better if GoIV also stayed on top of the appraisal information, slightly above so that the user can read and add the information as the trainer is mentioning it. Or just two independent screens altogether, one that pops up when the appraisal information is being read so that you can complete it, with the other being the usual one with the appraisal information incorporated.

**Comment by nahojjjen** [comment]
@rpgrca I agree with the memory problem, Ive been using the appraisal version for a day now & it was annoying. I'll see if i can find some easy way to "move up" the entire info dialog when the appraisal box is expanded so the user can click appraise without closing the dialog. Pokefly is pretty messy though so I might not be able to

**Comment by Blaisorblade** [comment]
The main issue is fixed by #368. Opened #373 for the "memory" issue.
