### ISSUE TITLE
Add a screen where we give credit to the third party tools and libraries the app uses

### ISSUE THREAD

**Issue by nahojjjen** [farkam135/GoIV#328]
I believe some of the dependencies we have have licenses that require us to link back to their sources, something which we currently don't do. Even if the license does not require that we give credit, it would be a nice thing to do.

here's a list of the things I think we should mention (some might be missing)

Fabric

Tesseract

okhttp

butterknife

lombok

timber(?)

**Comment by oskomonzon** [comment]
I agree. Maybe a good way to do it is adding an information icon (you know, the "i" in a circle) next to the settings cog and have it display a dialog with a little information, like an about section. Thoughts?

**Comment by nahojjjen** [comment]
Ive created a pr that adds a button in settings which navigates you to a basic view of the info

#559
