### ISSUE TITLE
Pushing IV button does nothing

### ISSUE THREAD

**Issue by SteinerKD** [farkam135/GoIV#333]
Previously (v2.1.0-13) this app worked fine for me and I could get IV ranges. Now after the auto update to 3.1.0 it doesn't work for me. The app shows as running and the IV button appears, but no matter how many times I tap it absolutely nothing happens (except for the IV button blinking away for a second or so). (PoGO 0.35.0 on Galaxy S7, Android 6.0.1)

**Comment by rpgrca** [comment]
This is the behaviour I described in #234. The workaround I found was to stop GoIV, and then kill it (recent task list, swipe). Then the next time I launch GoIV and start it, it would work.

**Comment by SteinerKD** [comment]
Confirmed. Thank you, sorry for the double report.
