### ISSUE TITLE
No possible IV found for valid stats

### ISSUE THREAD

**Issue by dw13** [farkam135/GoIV#34]
For reference, I am level 28, and it was set accordingly.

The pokemon seems to scan correctly from this screenshot:
![tmp_3017-screenshot_20160816-174341726553371](https://cloud.githubusercontent.com/assets/3765450/17718110/263c5cce-63e0-11e6-836f-b053cde1ec54.png)

After scanning, I get this result:
![tmp_3017-screenshot_20160816-174351700325996](https://cloud.githubusercontent.com/assets/3765450/17718146/533e9890-63e0-11e6-879a-8377c3f39a95.png)

Here is a raw view of the pokemon before scanning: 
![tmp_3017-screenshot_20160816-174548809711147](https://cloud.githubusercontent.com/assets/3765450/17718003/7f7bd964-63df-11e6-9e5e-24c8f52817ee.png)

**Comment by McAJBen** [comment]
It is actually level 27, red dot is not in correct possition

**Comment by farkam135** [comment]
May I actually have your device info as well, looks like the iv button is also super small.

**Comment by CaptorOfSin** [comment]
I'm having same issue, every pokemon is getting the "No possibilities".
Didn't have the problem with the playstore version of the app though.

**Comment by McAJBen** [comment]
What pokemon were they?

**Comment by mattaereal** [comment]
I sometimes get this, but when I retry a few times it shows. I'll pay attention to it and provide feedback.

Moto X (2nd gen)

**Comment by CaptorOfSin** [comment]
I'm getting this on every pokemon I've tried, i'm on a Samsung Galaxy S7 Edge

**Comment by simonho1989** [comment]
I resolve the issue by re-installing the app

**Comment by dw13** [comment]
This is on my Samsung Galaxy S6 Edge Plus

**Comment by skaforey** [comment]
You can fix this by simply clearing the app data/cache instead of uninstalling/reinstalling.  Something in the data must be getting corrupt somehow.

**Comment by dw13** [comment]
Clearing cache/data did not fix this issue for me.

**Comment by SunMar** [comment]
I'm also getting this with my Nidoran♂ which is a perfect 100% pokemon (other Pokemon I've tried so far scan fine).

![image](https://cloud.githubusercontent.com/assets/8324268/17765632/4ff442dc-6527-11e6-9a5f-242e7cc75285.png)

![image](https://cloud.githubusercontent.com/assets/8324268/17765636/5606f3ea-6527-11e6-857e-8c7b3c2ae141.png)

My trainer level is set correct, and the pokemon level is also correct (I've got a reference pokemon for each level to check them). I haven't yet powered up this Nidoran♂ so it shouldn't be able to be at a half level.

How does GoIV calculate its stats? Does it use the formula's like in https://docs.google.com/spreadsheets/d/1wbtIc33K45iU1ScUnkB0PlslJ-eLaJlSZY47sPME2Uk and TheSilphroad IV calculator or something else?

**Comment by farkam135** [comment]
@SunMar Right now the OCR has a tough time detecting gender symbols, in your results screen you can see it says "Nidoran Female" on the previous screen where you can correct your data click the pokemon name and change it to the female nidoran.

**Comment by CaptorOfSin** [comment]
I'd just like to mention that I did a pull this morning and rebuild and now it's working as expected again..

I love the app, and nice updates as well!

**Comment by moggd** [comment]
I'm having same issue with newest build - any advice? Galaxy S7

**Comment by farkam135** [comment]
Fixed in latest update
