### ISSUE TITLE
".../".split("/")[1] crashes

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#357]
This looks impossible——pokemonHPStr contains "/", but splitting on "/" produces a 1-element array. WTF? I don't know what the string in question is.

Stacktrace at http://crashes.to/s/ad8a16ae9c1.

**Comment by nahojjjen** [comment]
If the detected string is for example "1/" then the produced array would be [1], wouldnt it? Trying to get the second element (index 1) would produce an index out of bounds exception.
