### ISSUE TITLE
Inform OCR text with a toast in "debug" mode or after several failures

### ISSUE THREAD

**Issue by rpgrca** [farkam135/GoIV#359]
Splitting from #358, idea for a future build:

> With all these unexpected OCR mistakes maybe it would be useful if the user could turn on a "debug" switch so that the application informs the user with a toast what has been recognized to make it easier to fix, or without such switch, inform him after 4 or 5 consecutive failed attempts to recognize either CP or HP.

This way when someone reports his pokemon CP couldn't be read, it would be trivial to ask him both the pokemon's CP and the read value to adjust if necessary instead of waiting until a developer gets a pokemon with exactly the same CP value.

Another way could be remembering the OCR value and the correction, just as the application is remembering the name and the pokemon type.

**Comment by nahojjjen** [comment]
We've sort of introduced a similar feature to this in 4.0.1, where the user can email debug info of the screen scan recalibration info. I'm closing this issue for now.
