### ISSUE TITLE
Pokemon image stat scan does not find correct CP value

### ISSUE THREAD

**Issue by dw13** [farkam135/GoIV#36]
Here is a screenshot of the scan vs actual:
![tmp_3017-screenshot_20160816-1744091711190943](https://cloud.githubusercontent.com/assets/3765450/17718285/f80162ea-63e0-11e6-9ce3-ce665990b638.png)

Here is the raw view for debugging purposes:
![tmp_3017-screenshot_20160816-1745142039435894](https://cloud.githubusercontent.com/assets/3765450/17718306/1ef392c4-63e1-11e6-99de-501ca681541c.png)

Things to consider:
- The first two digits of the actual CP are the last two of the scanned issue
- The bubbles in the background may interfere, but this is on no basis

**Comment by mattaereal** [comment]
I was about to report this. Seems like a dyslexic mistake.

Also, I know this may not be the best solution, but since pokemons sometimes are bigger and move over the arc, maybe scanning a few times just to validate that the number obtained is correct can be a good solution for now. If you got 3 times the same number you're okay, if you don't, tell the user to enter manually or to manually check it.

**Comment by Antonio-Kuri** [comment]
It may be super expensive to do. I'm not sure, but the OCR might have some reliability index, that indicates how likely the program read the image correctly. Maybe setting a minimum for that, and if the index is below that minimum, ask, for another screenshot, maybe a max of 1 time more, and then just ask to input the cp correctly.

Something similar could be done for the arc, if there is any problem

**Comment by sadyc1** [comment]
More data points when it doesn't work:
Squirtle CP 618, gets detected as 361. (550 squirtle works ok)
Poliwag CP 498, gets detected as 349. (442 poliwag works ok)
Drowzee CP 648, gets detected as 364. (547 drowzee works ok)
In my case, it seems to be a problem with the CP ending in 8, but it doesn't always verify. Tentacool 488 gets detected correctly.

**Comment by nahojjjen** [comment]
Ive redone some of the CP scanning parameters and how it handles the resulting string in #75 , I think i fixed it.

**Comment by sadyc1** [comment]
I tested your changes and I can confirm the detection failure I posted are fixed.
