### ISSUE TITLE
Stop using 10 when failing to read a number

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#374]
Rather use `Optional<Integer>` to represent OCRed numbers.

EDIT: reasons:
- failing to OCR the CP is no reason to write 10 in an input box so the user has to delete it; we could later even handle this differently in the GUI (by highlighting the missing input, etc.)
- we have code that compares the OCRed numbers to 10 to check if scanning failed, and I expect that might misbehave in edge cases.

**Comment by sarav** [comment]
What does this improve for the end user? Why is this a bug and not an enhancement?

**Comment by Blaisorblade** [comment]
OP edited. I can relabel as enhancement if you really care.

**Comment by imapokemon4** [comment]
This bugs me. So I'd agree with @Blaisorblade calling it a bug.

**Comment by Blaisorblade** [comment]
Thanks. Let's not focus too much on the label though ;-).

**Comment by DJCrapsody** [comment]
No input if fail to ocr is better. I find it troublesome to delete and type every time it fails.
`need improvement` seems ideal for a label

**Comment by Blaisorblade** [comment]
Switched to *enhancement* (which is already available).
