### ISSUE TITLE
Don't enable/show "Show All" if there are too many IV combinations

### ISSUE THREAD

**Issue by rpgrca** [farkam135/GoIV#376]
It only shows an empty screen. I think this was fixed and is back in the latest build.

![2016-09-06 00 14 58](https://cloud.githubusercontent.com/assets/15602473/18258559/72c8b37a-73ae-11e6-88a7-67b2214b97c5.jpg)

**Comment by Blaisorblade** [comment]
Yep, noticed today. Thanks for the issue!

Meanwhile, with appraisals we should probably allow inspecting pokemons with HP=CP=10.
