### ISSUE TITLE
Refine by powering up/evolving not working as intended

### ISSUE THREAD

**Issue by DJCrapsody** [farkam135/GoIV#383]
Powering up works as intended while evolution does not.

Check IV on Pokemon A, evolve Pokemon A, check IV on Pokemon A - `canLastScanBePoweredUpPreviousScan()` returns false.

Unintended behavior:
Check IV on 2ndEvolutionPokemon, check IV on 1stEvolutionPokemon (e.g. Flareon then Eevee) - `canLastScanBePoweredUpPreviousScan()` returns true.

**Comment by oskomonzon** [comment]
IIUC, this one:
`boolean isEvolved = p1.isInNextEvolution(p2);`
should be 
`boolean isEvolved = p2.isInNextEvolution(p1);`

p1 is current Pokémon, p2 is previous scan. Current should be in the evolution list of previous.
