### ISSUE TITLE
Stop copying Image into Bitmap at each check

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#391]
I noticed while debugging #390. I believe this is rather wasteful if we are to just access two pixels. Fixing this would require to index correctly the raw ByteBuffer, but I expect this is the kind of optimization that is wortwhile.

@sarav, opinions?

**Comment by Blaisorblade** [comment]
Just noticed #300 which is related (but more ambitious).

**Comment by sarav** [comment]
I think this would be a good optimization anyway. Even if #300 is implemented. Transferring buffers can cause quite a bit of power usage.

**Comment by Blaisorblade** [comment]
I bet. And... I did get this working! PR coming soon.
