### ISSUE TITLE
Workingon Nox?

### ISSUE THREAD

**Issue by FantoYouYou** [farkam135/GoIV#397]
Hi, great app but i would like toi test it on nox, but can't seems to get it to work. it doesn't find capture rep. Any suggestion ?

**Comment by DJCrapsody** [comment]
It should, with the standard resolution. But till date, no one has reported on GoIV working on an emulator/VM. It will probably not be supported at any time in the near future as such programs are usually linked to gps spoofing due to the ability to change gps.

**Comment by d-bischoff** [comment]
"would like toi test it on nox" haha. sure thing. playing pogo on nox is soooo legitimate.
