### ISSUE TITLE
Screenshot mode doesn't work

### ISSUE THREAD

**Issue by Slivo-fr** [farkam135/GoIV#401]
Hello,

The screenshot mode doesn't work anymore since the last system update of my phone.
I have a zenfone 2 ZE551ML with the latest asus rom (android 6.0.1) and goiv 3.1

I tried to reset app data, reconfig screenshot directory. I can not get it to work again :(

**Comment by sarav** [comment]
I rewrote that code in #393 and it should hopefully work in the next release.

**Comment by Slivo-fr** [comment]
Great, thanks for your work. I'll keep you updated !

**Comment by sarav** [comment]
Looks like you do some Android dev too? If that's the case, maybe make a build of the latest master branch and let us know if it works. Also, I just refactored some code that @farkam135 had done. So, mostly his work that I fixed up a bit.

**Comment by Slivo-fr** [comment]
Dev for sure, but I Nevers had the chance to mess with android yet. I'll try anyway :)

**Comment by Slivo-fr** [comment]
Just tried it, on the latest master, work pretty fine.
It seem it was the offline apk, but it doesn't matter, does it ?

Thanks again for your work, this app is wonderfull <3

**Comment by Blaisorblade** [comment]
Offline is fine, yes. Thanks for the test and the compliments, and closing this issue then!
