### ISSUE TITLE
IV button is not sized correctly

### ISSUE THREAD

**Issue by DJCrapsody** [farkam135/GoIV#402]
![iv-wrong-size](https://cloud.githubusercontent.com/assets/2212292/18439672/dff8d468-7938-11e6-9a24-e8ac2035a088.png)

Reported at https://www.reddit.com/r/GoIV/comments/50s7uf/version_310_released/d7hiykj

**Comment by Blaisorblade** [comment]
Thanks for creating a ticket. Bad news: it seems device dependent. On my Nexus 5 the button is fine in size and alignment (a couple of pixels too high maybe, so the opposite direction).

![image](https://cloud.githubusercontent.com/assets/289960/18475445/b150d6d6-79c6-11e6-9d19-05d3930d664e.png)

**Comment by DJCrapsody** [comment]
I think it's due to the image being badly resized and stuff. Will check on it.

**Comment by DJCrapsody** [comment]
@Blaisorblade bug and need help labels would be good

**Comment by schachmat** [comment]
Maybe the correct size and positioning can be derived from the hamburger menu icon in the screenshot.

**Comment by Blaisorblade** [comment]
Doing that at runtime would be pretty expensive I imagine... or at least, I'm not sure how to do it quickly.

**Comment by NightMadness** [comment]
Adding one more
![20160929_075941](https://cloud.githubusercontent.com/assets/22281828/18953112/c1134a58-861a-11e6-99ac-d87bd2c53164.png)

Samsung s7 edge

Full img
(https://cloud.githubusercontent.com/assets/22281828/18953121/c9ff0e04-861a-11e6-8543-5f5583e9d1b3.png)

**Comment by DJCrapsody** [comment]
This has been taken care in a PR. Tested ok just needs fixing for 4.4.

**Comment by NightMadness** [comment]
@DJCrapsody the vector graphics look awesome! 
I downloaded latest from PR https://github.com/farkam135/GoIV/pull/490 as of 9/29/2016, 
looks like the IV button is the right size, but not aligned.

![screenshot_20160929-220648b](https://cloud.githubusercontent.com/assets/22281828/18978465/73d88a38-8691-11e6-9fdd-4bacd9299dbd.png)

full image:
https://cloud.githubusercontent.com/assets/22281828/18978467/75e414fa-8691-11e6-9d43-2b3f9b9a76ea.png

S7 Edge Screen Size:
```widthPixels = 1440```
```heightPixels = 2560```

**Comment by Blaisorblade** [comment]
> I downloaded latest from PR #490 as of 9/29/2016,

Assuming you mean commit https://github.com/farkam135/GoIV/pull/490/commits/2e394efd5e9152e43694317fb912bcf680208fb7 (protip if you want: links to commits are safer IDs ;-) ).

**Comment by Blaisorblade** [comment]
Also, for the record: if #490 works, we should probably still merge it even if it doesn't give perfect alignment everywhere, as soon as it's better. Getting it perfectly right on all devices seems very hard.

**Comment by nahojjjen** [comment]
I believe this was fixed when the quick-iv-scan was introduced.
