### ISSUE TITLE
Wrong gravity for dialog

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#406]
To reproduce:
1. press IV button
2. expand appraisal (this will move the floating input window upward)
3. press Check IV (the window will move back down)
4. press button to inspect combinations (window stays down)
5. press back, and *the window moves incorrectly up* instead of staying down.

This sounds like the kind of bug you prevent by just separating the windows.

**Comment by sarav** [comment]
I saw this too... I just couldn't figure out the steps.

6. Open the detailed IV list and that's stuck up top too.
