### ISSUE TITLE
Optimize memory usage

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#407]
Here are some memory stats. They're not averaged and they're from a debug build, so the numbers aren't accurate. But if the true numbers are in this ballpark we're using lots of memory

Here's memory usage after starting main activity (41MB)—that seems quite egregious. Compare to Google App using twice as much _and showing tons of info_, while we have _one_ dialog.
![image](https://cloud.githubusercontent.com/assets/289960/18471606/05c00728-79b3-11e6-93cc-f9cc7733779d.png)

With service running (74MB):
![image](https://cloud.githubusercontent.com/assets/289960/18471633/22fa7ec2-79b3-11e6-89b0-28d15136de6b.png)

Adding ~30 MB is probably hard to avoid—simply the buffers for 2 uncompressed screenshots (allocated by ScreenGrabber) take 16MB at my resolution (1920*1080). But we shouldn't keep the original 40MB around.

After stopping service (67MB):
![image](https://cloud.githubusercontent.com/assets/289960/18471585/f1279cea-79b2-11e6-88c2-eb8725eb3057.png)

**Comment by DJCrapsody** [comment]
I have been looking into this for some time but hardly got any ideas. my phone runs slowly even after closing GoIV, got me thinking something leaked, but can't seem to put a finger on where it is at. This happened since the first version till now.

**Comment by Blaisorblade** [comment]
From experience, this sort of things is hard to solve without profiling—probably it's just one pointer we're keeping set that goes for too long. But the refactorings planned for 3.2 could help.

**Comment by DJCrapsody** [comment]
The refactoring so far did help in eliminating non potential issues. Thanks to all.

**Comment by sarav** [comment]
There's a memory profiler in Android Studio that one of you could try out, But @DJCrapsody I'm surprised your phone is slow even after killing GoIV. That's "almost" impossible. The only place that could happen is if we screen up releasing the projectio manager and stuff inside ScreenGrabber. Or if GC is taking its own sweet time.

**Comment by DJCrapsody** [comment]
@sarav unfortunately it does. I had times without GoIV and just Pokemon GO or just a day without either. The phone goes fine, but with GoIV turned on and after killing GoIV, the phone goes slow until I do a restart.

**Comment by Blaisorblade** [comment]
Regarding the unexplained slowdown, I won't be surprised at driver bugs causing that after seeing the crashes in #492.

**Comment by nahojjjen** [comment]
Memory was optimized, activity references are now weak references. Please create a new issue if another specific memory leak or problem is found.
