### ISSUE TITLE
The orange bar in "power up info" shouldn't be user movable

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#412]
The orange bar in the seekbar that shows which part of it is about the current trainer level is user movable if we try to drag it. It should not be moveable.

@oskomonzon -- you might be familiar enough with this to fix it quickly?

**Comment by DJCrapsody** [comment]
I was the one who made it. I will check on the code when I am back from work.

**Comment by nahojjjen** [comment]
I can confirm that the orange bar is movable.
