### ISSUE TITLE
Better bound-checking when cutting images

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#420]
Somehow, sometimes, we go out-of-bounds when extracting the name from a bitmap: http://crashes.to/s/c9a025fd5e9.

**Comment by Blaisorblade** [comment]
Same here for candies: http://crashes.to/s/1bebe53d2e9

**Comment by sarav** [comment]
How the fuck is this even possible?! I thought all the points were a percentage of the display metrics width and height. Sigh...

**Comment by nahojjjen** [comment]
I think it'd be clearer if we rewrite the cuttoff method call as I did in getPokemonEvolutionCostFromImg (in the candycost identification branch), instead of using division, use multiplication.

```
 Bitmap.createBitmap(pokemonImage, (int) (widthPixels * 0.625), (int) (heightPixels * 0.86),
                        (int) (widthPixels * 0.2), (int) (heightPixels * 0.05));
```

It's somewhat clearer that it's starting 62.5% into the screen width, and reading 20% of the screen up to 82.5%, and from 86% to 91% of the screen height.

**Comment by sarav** [comment]
@nahjjjen Yes please!

**Comment by Blaisorblade** [comment]
👍  to @nahojjjen's idea. For old code we want probably to do this with special care—no clue why there are so many digits (@farkam135 can you weigh in) but I'd suspect that's from all of @farkam135's testing on tons of screenshots, so we want to keep this equivalent.

> I thought all the points were a percentage of the display metrics width and height.

Yep. But who says that `heightPixels` and `widthPixels` from metrics relate to the actual bitmaps? Some fuzzy guesses over who knows how much code in how many variants.
For instance, on my phone the raw screenshots have padding so the metrics are *better* and smaller than the bitmap size.

More relevantly, we assume that both are in portrait mode.

The previous out-of-bounds errors we did fix happened when scanning the screen in landscape mode. I wonder if sometimes when we read the display metrics the phone is still in landscape mode—and then we should flip them. Not sure this *can* cause the bugs, but I'd keep it in mind. 

And maybe that's also affected by Android skins: both bugs happen on strange distributions of devices. Though maybe that's random (not many users so hard to do good statistics).

**Comment by Blaisorblade** [comment]
Closing in favor of #463, which probably explains the actual crashes.
