### ISSUE TITLE
Also show HP in evolution stats

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#423]
- [x] We show the CP of a possible evolution/powerup. We should also show its HP.
- [ ] And probably we should show the damage as we're discussing in #252.

**Comment by nahojjjen** [comment]
Hp adressed in #469

**Comment by nahojjjen** [comment]
I'm not sure what you mean with "show the damage"

**Comment by Blaisorblade** [comment]
In #252 we discusses a formula for the damage done in gym battles—there's a component depending only on IVs that uses them differently (https://github.com/farkam135/GoIV/issues/252#issuecomment-247769516). But I'm happy to ignore that.
