### ISSUE TITLE
setArcPointer not understandable

### ISSUE THREAD

**Issue by chuparCh0pper** [farkam135/GoIV#43]
I'm trying to rewrite the code to make it easier to understand but I'm having problems understanding it myself.

https://github.com/farkam135/GoIV/blob/master/app/src/main/java/com/kamron/pogoiv/pokefly.java#L226

`(45+ 180) * Math.PI / 180.0 = 3.92699081699`
But the real value is 0,785398, so ` Math.toRadians(45) * Math.PI ` would be a nicer code, but then again the variable is called `angleInRadians`

Also, there is a lot of duplicated code.

PS: can someone help me understand it ?

**Comment by mattaereal** [comment]
I downloaded the project yesterday and was about to do something like you're doing. I haven't started though, if I ever come to this point I'll reply. Mind sharing your modifications via pull requests so we don't make duplicate work?

**Comment by chuparCh0pper** [comment]
I stopped refactoring the logic and just outsourced duplicated code. https://github.com/farkam135/GoIV/pull/47
