### ISSUE TITLE
Input dialog should start with appraisal mode closed

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#432]
Appraisal mode starts expanded if you used it on your last pokemon, but that means it covers the HP/CP for the new one. @sarav doesn't like it, and I find it annoying because I only use it on a few pokemon, so I don't want it open by default.

[Quoting @sarav](https://github.com/farkam135/GoIV/issues/372#issuecomment-247825059):
> Every time I scan the pokemon, it opens up in appraisal mode that ends up blocking CP and HP. I'll have to fold appraisal mode to see what the HP is (which is barely missed from being blocked) and then open appraisal again and go through the rest of the steps. Adding this feature would make the steps a lot more simpler.

**Comment by DJCrapsody** [comment]
Guess we can set the values in the onClick methods of CloseBtn and CancelBtn.

We have to set the following:
1. Arrow to be collapsed state
2. Visibility of layout to be hidden

I can take this, will be finishing the last bit of my drawables crap and I'll go into this.

**Comment by nahojjjen** [comment]
My usage of GoIV is currently as a collective rater which i use at the end of the day after catching a lot of pokemon. I trash all pokemon that arent "breathtaking" according to the built in appraise feature, and then I go through all the remaining pokemon and use GoIV to get a more precise appraisal. 

If we change so the appraise always starts collapsed, then that will add an extra click each scan for my type of usage.

Therefor, I am against the suggested change in app behaviour.

**Comment by oskomonzon** [comment]
If we want to cater everyone then maybe we should add a "pin" button somewhere to lock the UI in the position until unpinned (or service stopped). Maybe a subtle tack in one of the corners when the layout is at the top.

**Comment by voltaek** [comment]
Alternatively, is there not a way to move the word "Appraisal" to be on the same line as the three checkboxes, eliminating the need to ever have the section hidden? We could abbreviate "Attack" and "Defense" if needed to in order to accomplish this. You could also stack "Appraisal" on top of "Refining"  to do so if you really need to keep "Refining" there.

Personally, I use the appraisal feature every time I use GoIV, so I'd prefer it to be either always showing or have an option to always show it.

**Comment by DJCrapsody** [comment]
I don't think you're on the latest commit. Build from source and you'll see there's no possible changes other than allowing users to have an option to keep it opened.

**Comment by Blaisorblade** [comment]
@voltaek Specifically, we added options to put in the other two sentences. And now we move the dialog up when you open appraisals, so you can appraise with the dialog open, but we cover the actual data from the Pokemon image. So maybe we should actually show the images (per #372), though that's tricky to get right.
