### ISSUE TITLE
Start screen slightly too large

### ISSUE THREAD

**Issue by rpgrca** [farkam135/GoIV#436]
The start screen in the last build is slightly too large, cutting the links, apparently a regression since the current build works correctly.

![2016-09-18 21 58 07](https://cloud.githubusercontent.com/assets/15602473/18619430/630d29ce-7dd2-11e6-9233-7e921e12c24d.jpg)

**Comment by nahojjjen** [comment]
The page is scrollable, the page hasnt fit for my samsung S7 since the new level picker. Afaik we're not aiming to fit the entire page on screen. You just happen to have an unfortunate resolution / dpi combo where the cutoff is a little weird.

**Comment by rpgrca** [comment]
Actually, it worked fine with the level picker. And I'm pretty sure it even worked fine after the team picker was added, unfortunately I updated the code and didn't keep an old apk to verify.
