### ISSUE TITLE
offline czy online

### ISSUE THREAD

**Issue by szamuka** [farkam135/GoIV#439]
Which version is better?

Pokemon Go has access to file and then I can get ban for this use program?

**Comment by DJCrapsody** [comment]
Seems like English is not your first language. I will keep it as simple as possible.

Offline or Online version is the same.
Online adds Auto Updating and Anonymous Crash Statistics Sending.

GoIV does not connect to Pokemon Go. It is not likely to get banned but Niantic can choose to ban you as they deem.

**Comment by szamuka** [comment]
but is chance to get banned for use this apps?

**Comment by DJCrapsody** [comment]
Yes. They can ban you for using a normal calculator as well. They have full control, it is the matter of them trying to justify on the ban. We will say, "If you are scared, don't use it".

**Comment by nahojjjen** [comment]
The ban risk for online and offline are identical.
