### ISSUE TITLE
Finish translating 3.2?

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#447]
Since the release is almost ready and we shouldn't have UI changes, I thought I'd let translators know. Of course this doesn't mean you *have* to translate stuff, it's just FYI

Pinging:

@Eremiell (Czech)
@Remiscan (French)
@thearaks (Italian, in case there's sth. else)
@oskomonzon (Spanish)
@RuiNascimento (Portuguese)
??? (German—seems unmaintained)

**Comment by Remiscan** [comment]
I just checked and with #446 I think everything is translated in French :)

**Comment by thearaks** [comment]
Please check #456 for Italian ;)

**Comment by sarav** [comment]
Really, no german players? :-/

**Comment by DJCrapsody** [comment]
Who did the German translation anyway?

**Comment by Eremiell** [comment]
git blame it? :P seems like @chuparCh0pper and @Dreckiger-Dan have some share there with me adding the file closing tag for some reason :)

**Comment by chuparCh0pper** [comment]
@sarav germans are everywhere...
i'll give it a try

**Comment by Blaisorblade** [comment]
@chuparCh0pper Thanks a lot, I saw your name in git blame but I thought you had moved along to other enterprises, should have tagged you anyway 😅 . And merged!

**Comment by Blaisorblade** [comment]
Closing as now 3.2 is tagged.
