### ISSUE TITLE
Scanning incorrectly detects pokemon level at level 30

### ISSUE THREAD

**Issue by rpgrca** [farkam135/GoIV#455]
Sorry about the big screenshots, I don't have editing software here. First time it happens in a while, a L30 pidgey, GoIV detects it as a 30.5 one, so the calculation fails:

![2016-09-20 02 06 12](https://cloud.githubusercontent.com/assets/15602473/18680637/05b6eb38-7f3b-11e6-88d5-f25bc45af9fe.png)

When I drop half a level, it works. This is where it should have been:

![2016-09-20 17 05 42](https://cloud.githubusercontent.com/assets/15602473/18680757/6a21fd24-7f3b-11e6-9d09-05a19aa5f8c9.png)

I kind of remember there were some issues with the arc in the higher levels.

**Comment by oskomonzon** [comment]
@rpgrca, is your trainer level set correctly?

**Comment by Blaisorblade** [comment]
Also reported on Reddit with similar screenshots https://www.reddit.com/r/GoIV/comments/53cduw/buggs7_edge_level_30_pokemon_get_detected_as_305/d7u2ms7

> I kind of remember there were some issues with the arc in the higher levels.

The old issues are fixed I think—the level is mapped correctly to an angle. But at that level, the difference between levels is smaller than the size of the dot. We just sample one pixel in the circle, checking if it's white, and I suspect **both levels map to pixels inside the dot**.

**Comment by Eremiell** [comment]
so maybe we could sample multiple pixels? like one we expect to be upper left one one we expect to be lower down or something?

**Comment by rpgrca** [comment]
I'm guessing this could happen with anyone who catches a pokemon that is at his level (like a L28 catching a L28 pokemon). Would it be advisable to show somehow that the level might have been incorrectly set? If you start with the appraisal expanded, the box would cover the dot almost immediately, giving you no time to notice the mistake.

The main problem would be if it could be calculated with the wrong level. If you don't use the appraisal, you will probably get a lower rating. If you use it, with some luck you won't get any match, but if you get a match, it'll probably be the incorrect one.

If you are not correcting the bug, I was thinking like using a red font to mark the level, and adding a small note saying "Verify that the dot is correctly set" or similar if the application detects the pokemon is high level.

**Comment by sadyc1** [comment]
This issue is always happening for me in goiv 3.1.0 for pokemon lvl 30, and 31.5.  (29, 29.5, 32.5 work correctly, for 30.5 and 31, I don't lave data). I'm lvl 31. I'm pretty sure the issue with lvl 30 was present when I had lvl 30 as well.

**Comment by BraisGabin** [comment]
This issue remembers me this: https://www.reddit.com/r/PokemonGOIVs/comments/4x2f6v/some_iv_range_calculators_have_been_using_the/ but I think that it's not the same issue 

But looking your code I realice that you use doubles instead of floats. Pokémon Go uses floats for this calculations. The maths with floating point are a bit impredecibles. 

Anyway, I think that the solution is what @Eremiell pointed out.

**Comment by Blaisorblade** [comment]
That link seems about wrong CpM values, while this issue is about detecting the wrong level so it's indeed unrelated. I've created an issue about float-vs-double.

**Comment by mever1ck** [comment]
I have this issues since my L30 with all L30 pokemons, currently I am L32 and problem persist.

**Comment by nahojjjen** [comment]
This issue was fixed by updating the algorithm that detects the level-dot
