### ISSUE TITLE
Screen blacks out when starting on Nexus 5X / Android 7

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#466]
To reproduce, on my Nexus 5X with Android 7, not my Nexus 5 (EDITED):
1. Open PoGo
2. Go to home screen (tested without closing PoGo)
3. Open the GoIV app
4. Disable the "Start Pogo" setting
5. (Ensure GoIV is not in battery saver mode)
6. Start GoIV
7. Observe the screen (not always, sometimes) go black (in full or part)
8. If it does not restore on its own, tap the screen, and see GoIV back there (as expected).

If you then stop and start GoIV this does not happen. Same if you close GoIV and restart it. It does happen if you start GoIV, switch to PoGo, then switch back to GoIV and start it.

Overall, the issue seems in other words to be with starting screen capture the first time after opening PoGo. And it might be Nexus 5X-specific or Android 7 specific. In either case, it's likely we can't do much.

Still, I wanted to have an entry to point people at.

**Comment by DJCrapsody** [comment]
We had this issue (I did mention this recently) for a long time, since the start. @nahojjjen mentioned that it was due to PoGo being developed on Unity engine.

**Comment by DJCrapsody** [comment]
Most of them are reported on reddit but you can see one reported at #424.

**Comment by nahojjjen** [comment]
Ive stated that it seems plausible that it's because of unity or how gpu operations are handled, since when I searched for phrases similar to our problem i encountered other programmers reporting similar issues with their unity games.

**Comment by Blaisorblade** [comment]
I've edited the description, the symptoms here look different. This looks more like "starting screen capture after starting a 3D-using app", and seems an issue with the specific drivers.

Anyway, closing as invalid for now.
