### ISSUE TITLE
Input box moves way too high when appraisal is opened

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#471]
In some devices (my tablet), the input box moves way too high that the top is kinda going into the notification area. So, clicking the pokemon name to correct the detection is kinda impossible/hard.

Also, even without that issue, I think it would be better to have the bottom of the input box lined up with the 25% point (wild guess, but we should be able to find this from screenshots) of the screen from the bottom than having the top of the input box lined up to the top of the screen. That way, it'd be easier to reach on devices with bigger screen and takes care of this notification bar issue.

**Comment by sarav** [comment]
UI guys: @nahojjjen @oskomonzon @DJCrapsody

**Comment by nahojjjen** [comment]
Im not sure I understand the issue, could you post a screenshot?

**Comment by sarav** [comment]
![screenshot_20160926-152458](https://cloud.githubusercontent.com/assets/247061/18854097/d8069f68-83fd-11e6-9a1b-ced20ba825a6.png)

**Comment by sarav** [comment]
@nahojjjen I couldn't reproduce the issue where the UI was overlapping with the notification area. But the 2nd point should be visible here. On a tablet, the UI moves way too far. It could be a lot further down (easy to reach) while still not blocking the appraisal UI.

**Comment by nahojjjen** [comment]
I think adding logic to "how far up" the overlay should move could be complex, I think the current solution is to set a flag (top) to tell the overlay where it should move, we don't actually tell the overlay to move to a position in percent or pixels.

Unless there's a bug where you actually can't click the input like you suggested in the original post, I think we might want to avoid messing with the overlay position code.

Even if we do decide to implement a custom position for the overlay, it would not be as simple as "25% to the bottom" as some small phones have the overlay take more than 75% of the screen. (Z3 compact)

**Comment by cubeyz** [comment]
Close the appraisal refining bit while you try fix the top parts.

**Comment by sarav** [comment]
Actually, can we make the window dragable vertically so that the user can adjust it for their screen and the app can remember it. How hard would that be?

**Comment by oskomonzon** [comment]
@sarav I already have a working prototype of that. Minor details to sort out yet but it's working fairly well.

**Comment by NightMadness** [comment]
If this is issue fixed we can close this.

**Comment by nahojjjen** [comment]
Yea
