### ISSUE TITLE
Updater crashes on Android 7.0 or N preview (?)

### ISSUE THREAD

**Issue by DJCrapsody** [farkam135/GoIV#472]
This was reported on fabric. 268 crashes.

EDIT: This could be the issue https://developer.android.com/training/articles/scoped-directory-access.html

> Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.kamron.pogoiv (has extras) } in com.kamron.pogoiv.updater.DownloadUpdateService$1@c31af1c
>        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1132)
>        at android.os.Handler.handleCallback(Handler.java:751)
>        at android.os.Handler.dispatchMessage(Handler.java:95)
>        at android.os.Looper.loop(Looper.java:154)
>        at android.app.ActivityThread.main(ActivityThread.java:6077)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
> Caused by android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.kamron.pogoiv/files/Download/GoIV_new.apk exposed beyond app through Intent.getData()
>        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
>        at android.net.Uri.checkFileUriExposed(Uri.java:2346)
>        at android.content.Intent.prepareToLeaveProcess(Intent.java:8933)
>        at android.content.Intent.prepareToLeaveProcess(Intent.java:8894)
>        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
>        at android.app.ContextImpl.startActivity(ContextImpl.java:819)
>        at android.app.ContextImpl.startActivity(ContextImpl.java:796)
>        at android.content.ContextWrapper.startActivity(ContextWrapper.java:356)
>        at com.kamron.pogoiv.updater.DownloadUpdateService$1.onReceive(DownloadUpdateService.java:60)
>        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
>        at android.os.Handler.handleCallback(Handler.java:751)
>        at android.os.Handler.dispatchMessage(Handler.java:95)
>        at android.os.Looper.loop(Looper.java:154)
>        at android.app.ActivityThread.main(ActivityThread.java:6077)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by thearaks** [comment]
Related to "Scoped Directory Access" feature of Nougat:
https://developer.android.com/training/articles/scoped-directory-access.html

**Comment by Blaisorblade** [comment]
Worse: the current crashes are in 3.1.0 updating to 3.2.0, so any fix will only work for next release upgrading to the release after that 😢

**Comment by nahojjjen** [comment]
This was fixed by thearaks
