### ISSUE TITLE
Appraisal Refining in screenshot mode crash on Android 4.4

### ISSUE THREAD

**Issue by 4parthy** [farkam135/GoIV#475]
Clicking "Appraisal Refining" instantly crashes GoIV 3.2 showing the "Unfortunately GoIV has stopped." dialog.
This happens on my tablet (cm11/android 4.4) but not on my phone (android 6).

**Comment by DJCrapsody** [comment]
Are you on the Online version? If you are I could check out the stack trace.
On what device?

**Comment by 4parthy** [comment]
Yes the online version. The device is a kindle fire hdx 7

**Comment by DJCrapsody** [comment]
Got the stack trace and seems like it's related to KitKat. We'll look into it.

**Comment by 4parthy** [comment]
Thanks for the quick reply. Keep up the good work.

**Comment by sarav** [comment]
@DJCrapsody -- wanna post the stack trace here so that I can take a look if I have time?

**Comment by DJCrapsody** [comment]
> Fatal Exception: android.view.InflateException: Binary XML file line #2: Error inflating class android.widget.CheckedTextView
>        at android.view.LayoutInflater.createView(LayoutInflater.java:620)
>        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
>        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
>        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
>        at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:371)
>        at android.widget.ArrayAdapter.getView(ArrayAdapter.java:362)
>        at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:193)
>        at android.widget.Spinner.onMeasure(Spinner.java:482)
>        at android.view.View.measure(View.java:16497)
>        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
>        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
>        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
>        at android.view.View.measure(View.java:16497)
>        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
>        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
>        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
>        at android.view.View.measure(View.java:16497)
>        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
>        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
>        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
>        at android.view.View.measure(View.java:16497)
>        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
>        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
>        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
>        at android.view.View.measure(View.java:16497)
>        at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1226)
>        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
>        at android.widget.ScrollView.onMeasure(ScrollView.java:326)
>        at android.view.View.measure(View.java:16497)
>        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
>        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
>        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
>        at android.view.View.measure(View.java:16497)
>        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1940)
>        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1137)
>        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1319)
>        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1024)
>        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5694)
>        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
>        at android.view.Choreographer.doCallbacks(Choreographer.java:574)
>        at android.view.Choreographer.doFrame(Choreographer.java:544)
>        at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:676)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:136)
>        at android.app.ActivityThread.main(ActivityThread.java:5045)
>        at java.lang.reflect.Method.invokeNative(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:515)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
>        at dalvik.system.NativeStart.main(NativeStart.java)
> Caused by java.lang.reflect.InvocationTargetException
>        at java.lang.reflect.Constructor.constructNative(Constructor.java)
>        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>        at android.view.LayoutInflater.createView(LayoutInflater.java:594)
>        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
>        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
>        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
>        at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:371)
>        at android.widget.ArrayAdapter.getView(ArrayAdapter.java:362)
>        at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:193)
>        at android.widget.Spinner.onMeasure(Spinner.java:482)
>        at android.view.View.measure(View.java:16497)
>        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
>        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
>        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
>        at android.view.View.measure(View.java:16497)
>        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
>        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
>        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
>        at android.view.View.measure(View.java:16497)
>        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
>        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
>        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
>        at android.view.View.measure(View.java:16497)
>        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
>        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
>        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
>        at android.view.View.measure(View.java:16497)
>        at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1226)
>        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
>        at android.widget.ScrollView.onMeasure(ScrollView.java:326)
>        at android.view.View.measure(View.java:16497)
>        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
>        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
>        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
>        at android.view.View.measure(View.java:16497)
>        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1940)
>        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1137)
>        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1319)
>        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1024)
>        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5694)
>        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
>        at android.view.Choreographer.doCallbacks(Choreographer.java:574)
>        at android.view.Choreographer.doFrame(Choreographer.java:544)
>        at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:676)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:136)
>        at android.app.ActivityThread.main(ActivityThread.java:5045)
>        at java.lang.reflect.Method.invokeNative(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:515)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
>        at dalvik.system.NativeStart.main(NativeStart.java)
> Caused by android.content.res.Resources$NotFoundException: Resource is not a ColorStateList (color or path): TypedValue{t=0x2/d=0x7f010081 a=2}
>        at android.content.res.Resources.loadColorStateList(Resources.java:2237)
>        at android.content.res.TypedArray.getColorStateList(TypedArray.java:343)
>        at android.widget.TextView.<init>(TextView.java:968)
>        at android.widget.CheckedTextView.<init>(CheckedTextView.java:62)
>        at android.widget.CheckedTextView.<init>(CheckedTextView.java:58)
>        at java.lang.reflect.Constructor.constructNative(Constructor.java)
>        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>        at android.view.LayoutInflater.createView(LayoutInflater.java:594)
>        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
>        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
>        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
>        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
>        at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:371)
>        at android.widget.ArrayAdapter.getView(ArrayAdapter.java:362)
>        at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:193)
>        at android.widget.Spinner.onMeasure(Spinner.java:482)
>        at android.view.View.measure(View.java:16497)
>        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
>        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
>        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
>        at android.view.View.measure(View.java:16497)
>        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
>        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
>        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
>        at android.view.View.measure(View.java:16497)
>        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
>        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
>        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
>        at android.view.View.measure(View.java:16497)
>        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
>        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
>        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
>        at android.view.View.measure(View.java:16497)
>        at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1226)
>        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
>        at android.widget.ScrollView.onMeasure(ScrollView.java:326)
>        at android.view.View.measure(View.java:16497)
>        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
>        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
>        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
>        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
>        at android.view.View.measure(View.java:16497)
>        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1940)
>        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1137)
>        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1319)
>        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1024)
>        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5694)
>        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
>        at android.view.Choreographer.doCallbacks(Choreographer.java:574)
>        at android.view.Choreographer.doFrame(Choreographer.java:544)
>        at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:676)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:136)
>        at android.app.ActivityThread.main(ActivityThread.java:5045)
>        at java.lang.reflect.Method.invokeNative(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:515)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
>        at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by Blaisorblade** [comment]
@thearaks diagnosed this...

**Comment by DJCrapsody** [comment]
We'll need to get 3.2.1 out asap with this.

**Comment by Blaisorblade** [comment]
We know what causes the problem, but I'm not sure we have an easy fix. @thearaks worked it around by disabling some style setting, but I'd expect that to have some downsides.

**Comment by thearaks** [comment]
In `app/src/main/res/layout/goiv_spinner_item.xml`:
This attribute causes the crash:
`style="@style/dialogTheme.SpinnerDropDownItem"`

`dialogTheme.SpinnerDropDownItem` inherits from `dialogTheme`
`dialogTheme` inherits from `Theme.AppCompat.Light`

Probably, since Pokefly Service can't use AppCompat LayoutInflater, the inflation on KitKat with the default platform LayoutInflater crashes on some new, unsupported attribute.

We should make `dialogTheme.SpinnerDropDownItem` not inherit from `dialogTheme`, removing "dialogTheme." from its name and checking that the resulting attribute set is still valid.
