### ISSUE TITLE
Checksums for 3.2 release

### ISSUE THREAD

**Issue by 4parthy** [farkam135/GoIV#476]
They are not in in the readme yet. But maybe you want to add them to the [release info](https://github.com/farkam135/GoIV/releases/tag/3.2.0) as well. I think that would be very convenient.

**Comment by Blaisorblade** [comment]
Thanks for reminding us. Overlaps with #449.

**Comment by Blaisorblade** [comment]
Done. And now the checksums are only in the release info.
