### ISSUE TITLE
[Appraisal][French translation]

### ISSUE THREAD

**Issue by Wddysr** [farkam135/GoIV#479]
Stats' messages has been inverted in French language between "Ses stats sont excellentes ! C'est super !" (it should describe 65-80%) and "Je suis estomaquée par ses stats. Bravo !" (wich should represent 81-100%).

This result as wrong possibilities or even the message saying to check the stat when the player doesn't know that the statements are missplaced.

**Comment by DJCrapsody** [comment]
This is fixed in one of the PR.

**Comment by Wddysr** [comment]
I didn't saw it, sorry about that. I Will close the issue.
