### ISSUE TITLE
New strings breaking naming pattern.

### ISSUE THREAD

**Issue by Eremiell** [farkam135/GoIV#496]
Some recently added [strings](https://github.com/farkam135/GoIV/blob/cc40daea1240ae259b2112b79575321177f24f2c/app/src/main/res/values/strings.xml#L137) names break the pattern used so far to be all lowercase.

Proposed solution is to refactor them into all lowercase.

**Comment by Blaisorblade** [comment]
There's also `wrongPokemonNameInput`. But yeah, most names are in snake_case, not camelCase. @DJCrapsody do you also prefer snake_case for resource names? I forget what you used in your PR.

I can do the changes.

**Comment by Eremiell** [comment]
Missed that one back then. In the end, I mostly focus on string payload. ;)

**Comment by DJCrapsody** [comment]
Resource ids should **ALWAYS**  be in snake_case but some how newer ids are camelCase. Thanks @Blaisorblade

**Comment by DJCrapsody** [comment]
that include xml file names for resources too

**Comment by Blaisorblade** [comment]
Reopened for `wrongPokemonNameInput`, fixing in a moment.
