### ISSUE TITLE
Support reordering tokens in "custom clipboard format"

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#501]
In #480, it'd be cool to be able to reorder tokens somehow. Drag-and-drop is an obvious (but hard-to-implement) UI. I'm opening an issue to remember this, even if it's done after merging #480.

@nahojjjen proposed a simpler alternative:

> We could potentially change the copy-paste ui so that instead of clicking a token in the edit part, it doesnt remove the token, but rather selects it. After that, the description window could transform into an edit field, with remove, move left, and move right as options. That'd be easy to implement. It's not as elegant as a drag and drop solution though.

That'd already be great IMHO, so unless we get better ideas or somebody volunteers drag-and-drop it's probably good.

**Comment by Blaisorblade** [comment]
@oskomonzon @DJCrapsody @thearaks @sarav (and anybody with sth. to contribute) Any other idea on how to support reordering clipboard tokens?

**Comment by thearaks** [comment]
Support Library RecyclerView has a drag-to-reorder feature (Example [here](https://medium.com/@ipaulpro/drag-and-swipe-with-recyclerview-b9456d2b1aaf#.rya7z79dp)).
I suggest using a [StaggeredGridLayoutManager](https://developer.android.com/reference/android/support/v7/widget/StaggeredGridLayoutManager.html) to achieve something like this:
https://www.youtube.com/watch?v=yYsO_h6I_Hw

**Comment by oskomonzon** [comment]
There's also an Advanced RecyclerView library (https://github.com/h6ah4i/android-advancedrecyclerview) that's packed with Drag&Drop, Swipe and Expandable items functionality. It may be overkill, tho.

**Comment by sarav** [comment]
Or we could just have a format string for the user to define however they want it to be and we can just have predetermined tokens for stuff the app will replace.

**Comment by Blaisorblade** [comment]
A format string was proposed, but I think most users would prefer the current UI.
I think I might prefer the current UI over a format string even for myself, even though I understand format strings. And even for reordering tokens, the current GUI is probably faster than copy-pasting on mobile pieces of a format string.

The one annoyance is that you can't insert arbitrary separators, but that could be fixed without using a format string.

**Comment by nahojjjen** [comment]
Clipboard reordering was introduced in 4.0.0, by touch and holding the token.
