### ISSUE TITLE
[NEW FEATURE] Gym details

### ISSUE THREAD

**Issue by ashleykleynhans** [farkam135/GoIV#509]
This isn't directly related to GoIV, but I thought that since the app uses screen recording to evaluate the IV of Pokemon, you might be able to either add a new feature into the existing GoIV app or to build a new app that helps record the status of gyms, so we can swipe through each trainer in a gym, and it records the trainer name, level, pokemon, CP etc and then store it in a local DB on the phone and allow us to view it later.

**Comment by oskomonzon** [comment]
This suggestion is way out of the project scope. I can't say it would never happen, but it's not likely to see something like this comming up in the next few versions at least.

**Comment by nahojjjen** [comment]
I believe this would either require the application to be remodeled as a plugin-based program or implemented in another app altogether. You could certainly use the screen scanning logic in this app as a base for a new fork for a new app which would do this.

**Comment by Blaisorblade** [comment]
FWIW, we've talked multiple times about having plugins for such features, but it's a lot of work and it never went very far, so I agree with @nahojjjen.
