### ISSUE TITLE
Problem on KitKat 4.4.2

### ISSUE THREAD

**Issue by nirdavo** [farkam135/GoIV#512]
I can't get this app to work on KitKat 4.4.2 on two different devices (Samsung Galaxy Tab 3 10.1 and HTC One mini 2). In both cases, the GoIV installs fine, permissions are (automatically) granted, and it starts Pokemon Go when you tick the 'start' button. So far, so good.
However, the IV-Button does not show up when checking on a Pokemon. I tried simply waiting, tapping the screen (once)... nothing.
One thing that may or may not be related is that the option "Use screenshots to caclulate IVs" is greyed out and fixed to 'on'.
Any idea what might be the problem here?

**Comment by DJCrapsody** [comment]
only screenshot mode is supported on 4.4.2.

**Comment by nirdavo** [comment]
I suspected as much - this is probably the reason why the option is fixed to 'on', which makes sense in this case.
I have another update: I can't get it to work on a third device, either (Galaxy Tab 3 V, KitKat 4.4.4).
Anything I can do to help debugging this problem?

**Comment by NightMadness** [comment]
@nirdavo i dont have a galaxy tab so i cant test, what issue do you see? Are you able to **share** the screenshot to GoIV?

**Comment by nirdavo** [comment]
As I said in my original post, my problem is that the overlay button does not appear at all. Hence a screenshot would be quite useless as it would only show a normal, plain Pokemon go-screen.
This not only happens on a Samsung Galaxy Tab 3, but also on an HTC One mini 2. The common thing between those twomdevices is the android version: Kitkat 4.4.2. Another device with 4.4.4 also does not work - no overlay button.

**Comment by NightMadness** [comment]
Screenshot mode does not have an overlay button.

**Comment by Blaisorblade** [comment]
I'm guessing this can be closed as there is no bug—feel free to discuss for clarifications.
