### ISSUE TITLE
Turn CpM from double to float

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#514]
Apparently the PoGo uses floats and we use double, so according to a note in this link we should use float for CpM, as suggested by @BraisGabin (EDIT: in https://github.com/farkam135/GoIV/issues/455#issuecomment-254037883):
https://www.reddit.com/r/PokemonGOIVs/comments/4x2f6v/some_iv_range_calculators_have_been_using_the/

> You should ideally do your calculations in native IEEE-754 single-precision floating point, which is how the game seems to store its data.

Using double instead of float can produce different results even though it's unlikely, it'd be nice to fix this. We should probably also adapt calculations using CpM to use float internally.

**Comment by DJCrapsody** [comment]
unlikely to change results but lesser memory allocated for these numbers be better. float being 32bit while double being 64bit.

**Comment by Blaisorblade** [comment]
I agree it's unlikely because we round to integer, but with floating point common sense doesn't work—I never finished reading https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html (just found http://floating-point-gui.de/, should take a look).

And I've never seen misclassified pokemons due to this, unlike for other bugs we did fix.

**Comment by Eremiell** [comment]
Most precision would be achieved by holding the CpM as integral numbers, but it could be more precise than the actual game is. :)

**Comment by Blaisorblade** [comment]
@Eremiell Well, we're trying to reproduce precisely the game's calculations, so evaluating the formulas more accurately would not really be "most precision" for our goal. (Though maybe we're saying the same thing).

**Comment by Eremiell** [comment]
Yeah, the ultimate goal here is to get the exact same result as the game does. I didn't dig into this aspect of the client before, so no idea, how it's done there, just wanted to note, there are ways to do it much more precisely, but the true question is, how it's done ingame. Even if game stores the data as "floats" (if I remember the code dump, there seem much more like constants in scientific notation to me), it really matters on how it manages it during the computation.
