### ISSUE TITLE
Cache correction and nick name guess not working for Eevee

### ISSUE THREAD

**Issue by NightMadness** [farkam135/GoIV#518]
Hi Team,
Flareon96 will no longer self correct to Flareon even tough it is cached and guess correctly, instead it reads as Vaporeon.

I think we can change that when getCandyNameEvolutionCostGuess applies to more then one pokemon, we should not override cache/guess correction and me it the last priority.

**Comment by nahojjjen** [comment]
Worth mentioning that this was a known issue when merging the new identification module.

This will be solved by having the upgrade cost guessing module return a non-certain answer if an eevolution is found.

**Comment by nahojjjen** [comment]
This issue is addressed in #520
