### ISSUE TITLE
Red dot on Arc is off by height of notification bar

### ISSUE THREAD

**Issue by ThomasMldr** [farkam135/GoIV#519]
I haven't had this problem on my own phone, but on my replacement phone (Samsung Galaxy A3) the notification header is visible and transparent when Pokemon Go / GoIV is open, which causes everything to be pushed down, so the red dot is offset from the actual arc, about the height of the notification bar.. I don't know if this is an only-Samsung thing or not, but it's hard to see if it scanned correctly. Scrolling the pokemon a bit until they match helps, but is not so fun to do for every pokémon, every time. See screenshot for what I mean
![Image of bug](http://i.imgur.com/VwLauRt.jpg)

**Comment by nahojjjen** [comment]
It's not affecting all samsung phones, my S7 does not show this error. Does the phone have options for showing the notification bar / on screen navigation for an on-app basis?

**Comment by ThomasMldr** [comment]
Can't seem to find that option, Googling for a setting or something only results in people suggesting to use a custom launcher.. When clicking through the settings I did get a notification that I could update from 5.0.2 to 6.0.1 (as I said, replacement phone from the shop :-) ) So hopefully it'll be fixed after the update.. Keep you posted! (downloading the update over slow work-wifi now)

**Comment by nahojjjen** [comment]
Okay. I think the issue might originate from that GoIV learns your screen properties when you start the main app, and assumes you've got the same screen settings inside pokemon go. (I believe the app currently works like that)

So if you've got on-screen navigation in GoIV, but not in PoGo, that would cause issues.

**Comment by BraisGabin** [comment]
Can you upload the image in png somewhere?

**Comment by ThomasMldr** [comment]
Okay sorry for the delay, thought I had replied already!
It was solved on the replacement phone (Samsung Galaxy A3) when updating from Android 5.0.2 to 6.0.1, so maybe it is an android 5 related issue. Anyways, I've got my own phone back now, so for me the problem is no longer relevant, but maybe for others out there..
![Here is the image in PNG](http://i.imgur.com/JzURlHL.png)
