### ISSUE TITLE
Crash in Clipboard setting UI

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#525]
When I click "Add" without selecting anything, GoIV crashes. That shouldn't happen.

The UI is also kina confusing for me personally because there are multiple scroll sections without any clear boundaries around them. I didn't even realize I could scroll the middle section and I was clicking on "Add" thinking it'll bring up some UI to choose what to add.

**Comment by nahojjjen** [comment]
The UI is not really done, it's just "good enough" at the moment. I'm planning on fixing stuff, but I'm open to suggestions on improvement. I've got some things I'm planning to do to make stuff more clear.

I've fixed the crash on adding null  2f66f84e49bd1664de9cdc6aa2fb9c7c92c30537 here

**Comment by nahojjjen** [comment]
Fixed in #529
