### ISSUE TITLE
Move Edit Clipboard Setting button to Settings screen

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#526]
Can we add an entry in the Settings screen (after the "Copy to Clipboard" entry) that can be clicked to show the Clipboard settings activity?

I didn't realize we could scroll the Main activity to find a settings button down there.

**Comment by nahojjjen** [comment]
Yes, the edit button for the clipboard settings is supposed to be in the settings screen. 

I added it in the mainactivity because I wanted to get started on implementing the custom clipboard & didn't want to spend time figuring out how the settings screen was constructed.

**Comment by nahojjjen** [comment]
#529 solves the issue, and tweaks the UI
