### ISSUE TITLE
Add support for unicode digits for other numbered values too

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#527]
There's no reason we can't use unicode digits for other numbers that only take 2 digits like min/avg/max IV, max CP%, etc. That's reduce the number of characters and make it easier to read since GoIV would pick a larger font size if the nick name is fewer characters.

**Comment by DJCrapsody** [comment]
not possible unless we are going to represent 100 as (20)+(202020+20)

**Comment by sarav** [comment]
We can always represent that as 1(00). I mean, now common is that? I don't have a single 100. Also, people can always hand edit that if they want to.

**Comment by nahojjjen** [comment]
Circled unicode numbers only range from something like 0 to 25.

**Comment by sarav** [comment]
😭

**Comment by nahojjjen** [comment]
It's pretty sad, I was also hoping to represent percentage as a single character - would have been really cool.
