### ISSUE TITLE
Inefficient math for arc estimation

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#53]
https://github.com/farkam135/GoIV/blob/master/app/src/main/java/com/kamron/pogoiv/MainActivity.java#L415

This code in here is repeated for every scan attempt. Floating point operations are expensive in terms of power. All the calculation in the entire loop can be computed one time at app start or when the level changes and cached for subsequent calls.

You just need an x[2 * estimatedPokemonLevel] array and a y[2 * estimatedPokemonLevel] array. And then the loop that tries to determine the arc position just needs to loop over it.

I'd work on this, but looks like a lot of people are working on this and things are moving fast. So, if anyone else wants to fix this, go for it. Otherwise, I'll get to it eventually.

**Comment by farkam135** [comment]
I'll go ahead and get this resolved, thanks!

**Comment by farkam135** [comment]
Fixed in commit 39e52ec644cc99a63cb1dd656e77426e5dc27006!
