### ISSUE TITLE
Clipboard values for mIV% differs from %CP vs maxIV reported in UI

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#530]
I'm assuming mIV% in clipboard and %CP vs maxIV in the UI are the same thing based on the description in the app.

Trainer level 26.
Here's an example Pokemon (you could just change the values in your app to test this):
Gastly
CP 450
HP 45
Level 21.0
Mystic appraisal: Caught my attention, HP, incredible

UI shows IV min/avg/max: 73/74/76
%CP vs max IV: 94.8%
Clipboard ends up with 93 for mIV%.

**Comment by nahojjjen** [comment]
94.8% is for Gastlys evolution haunter - the next evolution of a pokemon is automatically selected in the evolution and power up info.

93.3% is for Gastly.
94.5% is for Haunter
95.7% is for Gengar.

When a pokemon evolves, its base stats increases, so the difference between high and low IVs becomes smaller, so the % differs. I suggest running the %CPvsMAX as a "max ev" variant of the token.

**Comment by sarav** [comment]
Ah, thanks. Makes sense.
