### ISSUE TITLE
[Request] Copy IV% IVA-IVD-IVS info to clipboard when there's a single result.

### ISSUE THREAD

**Issue by donaldta** [farkam135/GoIV#534]
I like the copy to clipboard option where it gives the IV range to the clipboard when there are multiple possibilities.  However, I think this feature would be vastly improved if it copies the specific stats to the clipboard when GoIV resolves the calculation to a single result.  For example, "100 15-15-15" would be copied to the clipboard if a perfect IV was found or "80% 14-11-11" as another example.

**Comment by Blaisorblade** [comment]
Have you seen the new version on master from @nahojjjen ? It allows configuring the format string graphically.

The only missing feature (already planned) is that you can't customize "single combo" and "multiple combos" separately, so for multiple IV combos it picks one, but I think that ends up being useful when there's a few combos.

**Comment by nahojjjen** [comment]
#562 makes this possible. So should be in future release.
