### ISSUE TITLE
Testing results on master + PR #503, TODOs for release

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#535]
Since we're nearing a release, I took a look at the current state.

Noticed a few odd things, which I think have nothing to do with #503:
- Some user corrections were off (probably was my doing), I had a Vaporeon nick mapped to Spearow. Given the code, I must have done that at some point, and forgot when user corrections weren't used as much.
- Eevolutions can be mapped to random pokemons because they're recognized based on the nickname, without using the candy family. That's as expected from what I proposed, it's hard to fix, and gets worked around via user corrections.
- A Nidoking was mapped to Nidoqueen, but that didn't happen after relaunching and the code for Nidoran gender guessing is there also for candies.

I also don't know
- what happened with Android 4.4? @thearaks @DJCrapsody . If the bugs aren't fixed yet, we could include a warning in the changelog.
- IIRC there were a few other bugs which we could fix like #477.

**Comment by DJCrapsody** [comment]
The crash on 4.4 was fixed in #506, and was merged quite some time ago.

**Comment by nahojjjen** [comment]
> Some user corrections were off (probably was my doing), I had a Vaporeon nick mapped to Spearow. Given the code, I must have done that at some point, and forgot when user corrections weren't used as much.

I think a lot of nickname corrections were mapped wrong when the candy was cropped partially wrong, I cant reproduce this, so I dont think it's a problem.

**Comment by Blaisorblade** [comment]
OK, sounds like we should close this (I've also seen work on Eevolutions). I wasn't sure whether to file the issue in the first place, but last time I had such an issue it turned out IIRC I should have done a report to be sure.
