### ISSUE TITLE
Going back to Google Play (Discussion)

### ISSUE THREAD

**Issue by NightMadness** [farkam135/GoIV#541]
I think its time we apply GoIV to Google Play.
1. We see other apps in play store calculating IV, at least one is using GoIV code.
2. We are open source.
3. We will reach a much bigger audience.

What do you think?

**Comment by nahojjjen** [comment]
I think it's a good idea, and I've discussed with farkam about putting it back in google play... So it's in progress.

**Comment by nahojjjen** [comment]
In case someone stumbles onto this issue, it was resolved and the link is here: https://play.google.com/store/apps/details?id=com.kamron.pogoiv

**Comment by patkan** [comment]
I can't find the app in the german play store. Clicking on the link, Google tells me that the app is not available in my country. Is there maybe something wrong with the area settings in the projects settings in Google Play?

**Comment by nahojjjen** [comment]
We've actually been removed from the playstore again since this thread was resolved
