### ISSUE TITLE
Allow configuration of what is copied to clipboard

### ISSUE THREAD

**Issue by coldwaterq** [farkam135/GoIV#55]
I like to just add the average of the stats after the name, so it would be nice to be able to configure this to happen instead of the range being copied.

Some other potential formats that people may want to copy are:
The three stats concatinated with colons between them
ex. 01:15:09
The three stats just concatinated but defaulting to two numbers
ex. 011509

**Comment by max1c** [comment]
Why was copy on scan removed completely? There should be an option to turn it on/off.

**Comment by rpgrca** [comment]
For the copy to clipboard option, I'd like different wildcards. I rename my Pokemon as "85.Eevee" with 85 being the IV average, that way when I sort by number I immediately know which copy of the Pokemon I should evolve or power up, and when sorting by name I know which ones I haven't rated yet. So, in my case I'd find useful being able to set my clipboard to something like "%avg.%name" to get the Pokemon name and formatting done immediately.

**Comment by Blaisorblade** [comment]
> Why was copy on scan removed completely? There should be an option to turn it on/off.

Now that we have settings at all, we have one for this. (There were problems for some users).

**Comment by Blaisorblade** [comment]
Generally: I think this is not the most urgent issue, but it could be be nice for advanced users, though we don't want to have an infinite amount of settings. I don't have a strong opinion either way.

And we'd need to allow specifying all the different things people might want. I'm thinking of something like an actual Java format string, but that's not easy for non-programmers. Supporting something better is not so easy.

Ideas? Somebody willing to figure it out and take up the task?

**Comment by rpgrca** [comment]
I've taken a few Java courses and was modifying my git copy to support this, but I'm a C# guy with zero Android knowledge. Just wildcards and replacing the data.

**Comment by oskomonzon** [comment]
I think we can present the user with a few cherrypicked options, like:

MaxIV.MinIV.Pokename
Atk.Def.HP.Pokename
AvgIV.Pokename

and so on... then a "custom" one for the technical users that want to do some wildcard tweaking.

We can even work in a new activity to set 'em with ease in further iterations. But I won't call that a priority.

**Comment by Eccenux** [comment]
> MaxIV.MinIV.Pokename
> Atk.Def.HP.Pokename
> AvgIV.Pokename

That could be option is an single select-type (not yes-no checkbox) setting. Also for `Atk.Def.HP.Pokename` that should be average values too or maybe even avg(att+def), avg(HP).

I can implement this select if you agree on that.

**Comment by Silly105** [comment]
I cant really help to decide which way is most helpful for the majority of users, but wouldnt miss to link to this idea: 
[https://www.reddit.com/r/GoIV/comments/5046mp/proposal_special_unicode_characters_for_copy_to/](url)

The Reddit user "Glurak" proposed a way to shorten the number of needed characters for saving pokemon IVs by using of the unicode character set of circled numers. PoGo has a full unicode support, so a name like "Eevee ⑬⑫⑮" would only need four additional characters. 
As the space for naming a Pokemon is limited to 12 characters, this could be a way to keep more of the actual name.

I cant do much java or android programming, but if this custom naming feature is going to be implemented, using those charakters instead of written numbers seems quite trivial. Please let me know if there is some work which can be done without knowing much of that Java-Fu. :)

**Comment by thearaks** [comment]
@Silly105 I really like that format with Unicode circled number characters.
In my use case, I would configure something like this:
Weedle⓯⓮⓯㊾

**Comment by Blaisorblade** [comment]
This Unicode-based convention is so cool (and so not-doable-by-hand) that I'd switch to it if implemented, over whatever scheme I'm using.

For anybody doing this: please don't add the code to `Pokefly.java` but somewhere else. Looking at `addToRangeToClipboardIfSettingOn`, maybe this could go in `IVScanResult` (only the String-generating part, not the clipboard-setting part)?

**Comment by Eccenux** [comment]
@thearaks  That would be great but are there Unicode numbers above 50? I haven't found e.g. 51. Seems like it don't exist: http://graphemica.com/search?page=2&q=circled+number

So it seems like IV (and e.g. attack DPS) would be feasible, but not IV as percentage.

**Comment by Blaisorblade** [comment]
@Eccenux made a very good point. I'm fine with using circled numbers for IV *if possible*, but maybe some users would be annoyed at the inconsistency.

**Comment by Silly105** [comment]
It is correct that there are no unicode symbols for numbers above 50. That is why I had thought of using only the three stats - personally I wouldn't need a percentage value if I can see those stats.
But indeed there are quite a few possible use cases - some users may want to put in the attack DPS, as mentioned above, another idea was to note, how far off 100% each pokemon is - so 0 would be a perfect one and those with values over 50 are crap anyway...

Finding a way to satisfy all users or at least a majority seems quite impossible to me. That is why I would implement this feature only if there is some kind of configuration dialoge. That way a user could decide what to add to clipboard and how.

But I am afraid it will be a hard task to keep such a feature balanced between the very different use-cases of casual users and those with programming experience - if that is possible at all.

**Comment by Blaisorblade** [comment]
@Silly105 I realize that finding a balance is hard, but if the choice is between nothing and a pretty cool compromise, I think having the latter is better.

And right now consensus seems for not having too many options. I've thought about having a page of advanced settings, but I haven't tried pushing that.

> But indeed there are quite a few possible use cases - some users may want to put in the attack DPS, as mentioned above, another idea was to note, how far off 100% each pokemon is - so 0 would be a perfect one and those with values over 50 are crap anyway...

The more common value used is the "actual" percentage, not the reverse, even though that takes one char more.

**Comment by Eccenux** [comment]
Having thought of that a bit more I think we could add an option to copy 0-45 value instead of 0-100% for total IV. Anyway here is an implementation of number formatter in Java:
https://github.com/Eccenux/UnicodeNumbers/tree/master

**Comment by Eccenux** [comment]
I don't think you need many options. Just 3 popular and custom for all the rest.
> Copy to clipboard
> -------------------------
> All IV values (e.g. ⓯⓮⓯)
> Sum of IV values (⓪ to ㊺).
> IV in percentage (0 to 100).
> Custom: __________________  (?) <- help button

Possible custom values would standard options:
* {UnicodeAtt}{UnicodeDef}{UnicodeSta}
* {UnicodeSum}
* {IV}
...and:
* {Att}{Def}{Sta} -- as above but simple numbers instead of Unicode.
* {Pokename} -- pokemon name.

Then just implement some class for clipboard string formatting. The class would take the string and IV values and simply replace all known "{Placeholder}" parts with specific values.

**Comment by nahojjjen** [comment]
I think that the hardest part about implementing user-modifiable clipboard options is the input where the user decides how he wants it. Should it be a popup? An input box? If we only present a couple of options in a list, that would be decently simple, but if we give the user the option to manually build their own custom string, it's difficult.

**Comment by rpgrca** [comment]
As a preview, it could just be a textbox in the settings, just below the one enabling copying to the clipboard.
Note that it's something most will probably enable and configure once, so with good documentation it should just be enough. Maybe poll to see which formats are the most required to add as default, but anyone interested in IV is slightly more advanced than a casual user, and will probably understand how to write a clipboard template.

**Comment by jef-pearlman** [comment]
Just noting that you'd likely need two settings, one to use if the individual IVs are known, and one if there's still a range of possibilities.

**Comment by Eccenux** [comment]
> 

I think that the hardest part about implementing user-modifiable clipboard options is the input where the user decides how he wants it. Should it be a popup? An input box? If we only present a couple of options in a list, that would be decently simple, but if we give the user the option to manually build their own custom string, it's difficult.

That's how things are done for date format. Usually you have a few popular options and an input box to type in whatever weird thing you need. Specifying custom format always requires more work, but for most people predefined options would be fine anyway.

**Comment by MMitsialis** [comment]
Hi,
I am not a coder, but heavily involved in IT. My thoughts:
1. Form without function is meaningless. 
2. Form follows function. 

So what function is the copy to clipboard? 
1. Record of our Pokémon. 
2. Export of Pokémon for analysis 
3. A means to make decisions on Pokémon 

For items 2 and 3 the IVs are critical, hence the app. To perform the analysis the attribute values are meaningless without the object to which they refer.  Therefore is we are copying to clipboard the Name,  IVs and possibly other attributes are key. 

I would suggest is a structure choice methods similar to how tv episode naming is implemented in most HTPC/MP3 systems would be beneficial. A look at Sickbeard,  TheRenamer, MP3Tag would be a good base to work from. 

From the way GoIv works, I perceive multiple attributes are available. It detects the name and other attributes, which would then be available as object properties that can be accessed and transferred to other functions.

**Comment by Blaisorblade** [comment]
> So what function is the copy to clipboard?

A few other goals might be conceivable, but we're focusing on simply pasting the copied text as new Pokemon nickname in some form, since that's the only way to attach annotations to a Pokemon.

**Comment by nahojjjen** [comment]
This issue was resolved in #480 

Specific issues and additions to the feature are discussed in other issue postings.
