### ISSUE TITLE
New Feature: Add a message/popup/notification when text is copied to the clipboard.

### ISSUE THREAD

**Issue by NightMadness** [farkam135/GoIV#551]
What do you guys think of adding a new feature to let the user know with a message (could be toast, open to ideas) when clipboard is copied with what was copied.

Something like "`Copied to clipboard: Pid151515.`".
if there is room we can instruct on how to disable the clipboard setting.

I think this will also ease the concerns of #511, at least will let user know we are "taking over" the clipboard.

**Comment by Blaisorblade** [comment]
I wouldn't object to a short-duration toast, it's really easy to do and not very intrusive.

But depending on the scenario there might be little point:

1. for people who know well the feature, it makes next to no difference (or do I miss something?).
2. for people who don't know the feature, it'd help discoverability greatly. So we could enable the clipboard feature by default.

The message should be carefully designed for the 2nd scenario, to suggest users they could rename the pokemon with the text — something like "Copied Pid... to clipboard for Pokemon renaming, configure/disable on Description" (we should also have a useful default then).

There's no fixed size limit to the text, but you don't want to have too much to read in a toast.

This helps a tiny bit with #511, but not for people who know about the feature, or who want to copy the text only in some cases—#532 is better there.
