### ISSUE TITLE
Preparing GoIV for pokemon generation 2

### ISSUE THREAD

**Issue by nahojjjen** [farkam135/GoIV#556]
When Pokemon Go releases gen 2, GoIV should be ready.

What needs to be done for GoIV to be gen-2 ready?

We need to add all:

- [x] pokemon names to the string list in order
- [x]  pokemon devolutions
- [x] candy costs for the new pokemon (**Unknown, but can be guessed**)
- [x] base stats for the new pokemon

Are there any other things which Ive missed?

Do we want to wait with adding these pokemon until pogo is updated, or can we start implementing this now?

**Comment by NightMadness** [comment]
I was thinking about it too.
I think we can at least start a branch and add gen2 pokemon names. 

How do we get IV stats to calculate? Will it be same as the DS game?

**Comment by nahojjjen** [comment]
What do you mean iv stats? they range from 0 to 15

**Comment by nahojjjen** [comment]
If you mean base stats then they follow a formula from the original games https://pokemongo.gamepress.gg/pokemon-stats-advanced

**Comment by NightMadness** [comment]
Perfect! LGTM. I cant think of any other thing to add to the list.

**Comment by nahojjjen** [comment]
For documentations sake, if anyone else is reading this thread: We've created the data for this in a google drive folder, and we're ready to add the data to the app when needed.

**Comment by nahojjjen** [comment]
#608  added this information (except the devolution information)
