### ISSUE TITLE
Slightly tweak battery saver mode

### ISSUE THREAD

**Issue by rhari991** [farkam135/GoIV#56]
Instead of making the user take a screenshot when he/she is on the pokemon screen, maybe we could just add a button on the screen or in the notification that takes the screenshot on press ? Then save the screenshot in a known location, and scan it.
The functions for this are already present, so it should be a minimal change.

**Comment by nahojjjen** [comment]
You cant programmatically take screenshots on android 4, and the screenshot mode was mainly done for android 4 support afaik

**Comment by rhari991** [comment]
Oh I see

**Comment by farkam135** [comment]
Unfortunately as nahojjjen mentioned we cannot take screenshots on non-rooted devices.
