### ISSUE TITLE
HP add a 5, example 140 hp =1405 hp

### ISSUE THREAD

**Issue by empalador** [farkam135/GoIV#560]

**Comment by nahojjjen** [comment]
This is being worked on in #547

**Comment by empalador** [comment]
No, yesterday with 3.2.0 not happenig this, and today with 3.3.0 happened, i have spanish language, check it plx!! thxx

**Comment by MARTINI1** [comment]
Same here and same, I have Spanish

I leave pictures of the error

![screenshot_20161118-133751](https://cloud.githubusercontent.com/assets/23555838/20433094/72d97aec-ada2-11e6-8e0c-2c00f9b71cf5.png)
![screenshot_20161118-134148](https://cloud.githubusercontent.com/assets/23555838/20433095/72d9a44a-ada2-11e6-99dc-06d73ab46917.png)
![screenshot_20161118-134227](https://cloud.githubusercontent.com/assets/23555838/20433093/72d8f45a-ada2-11e6-814b-133677b1a016.png)
![screenshot_20161118-134239](https://cloud.githubusercontent.com/assets/23555838/20433096/72da2168-ada2-11e6-896c-5f9c391bfae2.png)
![screenshot_20161118-134244](https://cloud.githubusercontent.com/assets/23555838/20433097/72df41e8-ada2-11e6-858b-8344638ff8aa.png)


In case of eevee the only thing that fails is life but in others when it is below 1000 candies also fails in the candies and in the life that puts a 5 of more and the candies as a random number of more

On the other hand take the opportunity to comment, I still with an error from the previous version (3.2 and the new 3.3) that when starting the goiv with the pogo running, the pogo frozen and I have to restart it...

And I have already cleaned goiv data and it does not solve anything, I have already become accustomed to close pogo and start goiv and pogo the pull but the bug will still be there :(

**Comment by nahojjjen** [comment]
I think you're misunderstanding, we're aware that 3.3 has the error, and we're working on a fix for a future release in #547

**Comment by MARTINI1** [comment]
And you're also working on the candy bug?

Because this is new feature to the new version 3.3 and has an error similar to life bug

Are you working with the error that leaves the pogo frozen when the goiv starts? I thought that with the new version it would no longer exist but the bug still continues :(

**Comment by nahojjjen** [comment]
@MARTINI1 

The black screen bug is being worked on here #558 and is being discussed here #492 

I haven't seen the candy bug before, so I haven't worked on it.

**Comment by suloku** [comment]
Also spanish, hp and candy number recognition fails. Is it only spabish related?

**Comment by nahojjjen** [comment]
@suloku should be solved here #561
