### ISSUE TITLE
Translation in calculation screen have to be 1 lined

### ISSUE THREAD

**Issue by chrisi51** [farkam135/GoIV#567]
please change the german translation in the calculation screen ... i mentioned it in 3.2 and the problem still exist: http://imgur.com/a/EM79b
Please use "Verschiebe den roten Punkt mit dem Slider" instead. I guess, it should be understandable for germans.

**Comment by NightMadness** [comment]
Created PR #569

**Comment by chrisi51** [comment]
hopefully that works... can you make a release with that?

**Comment by NightMadness** [comment]
Hi @chrisi51 can you confirm issues is fixed?
