### ISSUE TITLE
The ?%-?%-?% result does not factor refining the possibilities with overall appraisal phrase. 

### ISSUE THREAD

**Issue by donaldta** [farkam135/GoIV#568]
While using the appraisal refining feature, the minimum and maximum IV range associated with overall phrase should replace the ?%-?%-?% (min-avg-max) summary when there are "too many IV combinations".  Each team's overall appraisal phrase will break down each Pokemon's minimum to maximum IV range into four separate possibilities.  This should be reflected after using the appraisal refining feature even if the IV calculations were skipped in the getIVPossibilities routine.
.

**Comment by nahojjjen** [comment]
This issue should no longer exist after #604 , as "Too many IV combinations" has been removed.
