### ISSUE TITLE
App seems to stop working on S7 edge

### ISSUE THREAD

**Issue by nahojjjen** [farkam135/GoIV#57]
https://www.reddit.com/r/GoIV/comments/4y7bgi/200_released/d6lq9nl?context=3

**Comment by CaptorOfSin** [comment]
I doubt this is related to S7 edge. I have one and it's working for most pokemons.
However! i did debug and whenever it fails to read the CP, cptText will be "", which is a non parsable int.

this row:
pokemonCP = Integer.parseInt(cpText);
is throwing a NumberformatException, and after this the app basically stops working, the IV button dissapears, and pressing Stop will make it crash.

A simple:
 try {
            pokemonCP = Integer.parseInt(cpText);
        } catch (NumberFormatException ex){
            pokemonCP = 0;
        }

Should fix this particular problem though..
This is easy to reproduce using e.g. a gastly which is blocking the CP label as part of it's animation.

**Comment by nahojjjen** [comment]
From the crash reports given by Crashlytics it looks like you were right. I implemented basically the fix you suggested in #75  (changed default pokemonCP to 10 instead of 0 ) and it seems to have fixed it.
