### ISSUE TITLE
New stats/CP formula causes all scans to fail

### ISSUE THREAD

**Issue by nahojjjen** [farkam135/GoIV#570]
POGO updated which has resulted in pokemon having new CP.

We dont know if this is because the CP calculating formula changed, or the formula to calculate the new pokemon base stats is new.

**Comment by NightMadness** [comment]
Maybe these screen shots will help

![screenshot_20161121-172201](https://cloud.githubusercontent.com/assets/22281828/20503132/419bfb20-b00f-11e6-86f0-c83bd73f7dd6.png)

##old value
![screenshot_20160924-220048](https://cloud.githubusercontent.com/assets/22281828/20503134/41ab0200-b00f-11e6-9d36-4b43d70f493d.png)

**Comment by nahojjjen** [comment]
fixed in #571
