### ISSUE TITLE
Iv calculation incorrect after the cp change update

### ISSUE THREAD

**Issue by butterfist** [farkam135/GoIV#572]
Hi, I noticed that after the latest server update that change a lot of Pokemon's cp the app can't correctly check IVs.  I think that maybe a message in the app would be appreciated by those who might erroneous transfer a good pokemon.

So I'd like to suggest anyone who's transferring Pokemon's with bad IVs to hold their fingers for a while.

**Comment by nahojjjen** [comment]
Fixed here: #571 

Will try to push update soon.
