### ISSUE TITLE
New CP update 

### ISSUE THREAD

**Issue by RovingSpirit** [farkam135/GoIV#574]
Pretty self explanatory, is it possible to have this updated to calculate level up/iv info?

**Comment by NightMadness** [comment]
Code was updated. 
please update @ https://github.com/farkam135/GoIV/releases or at the google app store

**Comment by arthung47** [comment]
Foremost, thanks for your work and your reactivity.
I have an issue with the lastest release: installation failed.
I have a HTC820 with Android 6.0.1.

Thanks for your help

**Comment by nahojjjen** [comment]
@arthung47 unfortunately this is an issue caused by us changing the package name last patch - we've  reverted that change this patch.

Please manually uninstall the old version before installing the new one.

**Comment by arthung47** [comment]
thanks, my issue is fixed.
