### ISSUE TITLE
Add movesset classification

### ISSUE THREAD

**Issue by vmwinckler** [farkam135/GoIV#576]
Based on https://pokemongo.gamepress.gg/ put on display two options: 
- Attacker, Defender or Both
- Rank for this.
Example Dragonite (https://pokemongo.gamepress.gg/pokemon/149):
Dragonite: Dragon Breath / Dragon Claw = Attacker A
Dragonite: Steel Wing / Dragon Pulse = Defender A
Dragonite: Dragon Breath / Dragon Pulse = Both B

In "string name" i suggest add:
Attacker = Sword unicode icon + Word for Rank (or number ex.: 1º, 2º...)
Defender = Shield unicode icon + Word for Rank
Both = "Sword over Shield" unicode icon (or other) + Word for Rank Attacker/Word for Rank Defender

**Comment by vmwinckler** [comment]
It is possible, this app was able to: https://play.google.com/store/apps/details?id=com.orangefish.app.pokemoniv&hl=pt_BR

**Comment by vmwinckler** [comment]
"Poke Genie for IOs" has too: https://itunes.apple.com/us/app/poke-genie-smart-iv-calculator/id1143920524

![image](https://cloud.githubusercontent.com/assets/1237277/20947714/9fa34856-bbf7-11e6-8368-39ac07b83ec9.png)

**Comment by nahojjjen** [comment]
Implementing something like this would certainly be possible, but require that

1. the ui is changed (easy to do)

2. accurate moveset information is collected

3. we agree on a way of representing the moves

4. someone takes it upon themselves to keep the moveset data up to date

5. the ocr information for movesets is acquired from the user screen

**Comment by vmwinckler** [comment]
- for first time, copy data from pokemongo.gamepress.gg (easy with node or php, java i dont know)
- second moment, create self calc. pokemongo.gamepress.gg has all calcs and orientations.

**Comment by nahojjjen** [comment]
> for first time, copy data from pokemongo.gamepress.gg (easy with node or php, java i dont know)

It'd be good to have their permission to scrap the data  if we were to go that route

**Comment by sarav** [comment]
We keep talking about this many times and it always comes down to keeping the data up to date and getting their permission. If think we should stop worrying about keeping it up to day because gamepress themselves don't seem to be updating the classifications often. They generally do it mostly only when Niantic does some rebalancing. Also, if we show a tiny "last updated on <date>" that should still work well for most people than not having this ability at all.

Let me try contacting the website for permission.

**Comment by sarav** [comment]
I mailed them asking for permission. We'll see what they say. I also pointed them to the github and Play Store links of GoIV.

**Comment by nahojjjen** [comment]
Okay 👍

**Comment by sarav** [comment]
No reply so far ☹️
