### ISSUE TITLE
Add default appraisal option to settings

### ISSUE THREAD

**Issue by vmwinckler** [farkam135/GoIV#578]
Whenever I do a classification, I fill in the additional data but it is my rule that I only classify pokemons above 80% IV, so the initial message is always the same. My suggestion is to have an option where we can mark what we want as default to run the app so we do not need to select at startup, but this would be optional, if it is not filled or reset at a later time, everything would look as it is.

**Comment by crd** [comment]
I had an alternative suggestion: Populate the dropdown with something rather than nothing by default. It would be interesting to see the stats but like you I only ever bother determining IVs for my top-level mons.

**Comment by TripSixes** [comment]
Another take on this idea is to reverse-engineer the Results list to determine we can objectively identify any of the Appraisal answers.  The app could then have those pre-selected, and the user would only have to appraise/check the ones that are not exact.  For example.. if the results list shows a ton of IV's, but all of them have HP=15, and none of them have Att/Def at 15, then we can pre-select the HP checkbox, as well as pre-select the top-tier Stat answer.  Same thing for the IV% Range.. if all possible values are above 81%, then we can go ahead and select the top-tier IV Range as well.

**Comment by nahojjjen** [comment]
Im closing this issue as this feature would interfere with the auto-appraisal marking.

If there's more discussion or arguments for this, please add a comment or open a new issue.
