### ISSUE TITLE
Metapod IV is broken after new CP update

### ISSUE THREAD

**Issue by NightMadness** [farkam135/GoIV#579]
Initally reported by NGPriest, Metapod does not have calculated IV correctly.

**Comment by luponec** [comment]
I'm using offline version and actually I have problem not only with Metapod. 
I have issue on quite all pokemons giving me "no combination found" and the few  ones which give me no error are reported with different values compared to other online calculators and in contrast with values suggested by  team leader appraisal.
For example a bulbasaur my team leader says is "a wonder", it is evaluated just  58% max  by GoIV

**Comment by nahojjjen** [comment]
@luponec update goiv to the latest version and check your trainer level :)

#583 fixes metapod issue

**Comment by luponec** [comment]
I already had that version and trainer level was correct . The issue was not on GoIV anyway and I've updated my previous comment. 
I've found an app that interact with screen and that was the cause. 
Sorry for my mistake. Regards and thanks for the  great app.
