### ISSUE TITLE
You can press the checkbox to toggle battery saver / screen capture when it's already running

### ISSUE THREAD

**Issue by nahojjjen** [farkam135/GoIV#58]
You can press the checkbox to toggle battery saver / screen capture when GoIV is already started, but it doesnt actually change how the app behaves.

I think the notification should tell the user if its running screenshot / live mode, and the checkbox to toggle the modes should either be grayed out, or change the mode when pressed.

**Comment by farkam135** [comment]
Not a big issue, if someone wants to grey it out they can, but closing this issue.
