### ISSUE TITLE
Compute IVs without user interaction

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#588]
I think @nahojjjen mentioned something like this in chat or in another issue. Can't find one if there is.

The idea is to have the calculation done automatically and display the value in the floating button instead of "IV". We can let the user pick which **one** of the following values show there: Min IV, Avg IV, Max IV, %maxCP, etc.

The biggest problems when trying to implement this are:

1. The Candy and Stardust count graphic that covers the CP value as soon as a pokemon is caught. But this shouldn't be an issue when generally scrolling through Pokemon in the storage. So, it'd still be useful. And for the CP being obscured, we could have a one time retry with a 1 second delay (or however long that animation is).

2. OCR failing sometimes. But this doesn't seem to happen often these days. So, again the feature would still be pretty useful. And if it fails, we can just display "??".

Thoughts?

If we do this, we could even try be more efficient and reuse the screengrab that was used to decide if the button should be displayed.

**Comment by NightMadness** [comment]
I think this is a great idea. It is funny because I was thinking about doing something similar. I started to write a test code and I don't know if what I did so far will help at all with your vision. 

Raw test code: https://github.com/NightMadness/GoIV/tree/pokePreview

The problem I faced was that the IV button sometimes doesn't disappear while _scrolling through Pokemon in the storage_ so we may need another timer running to check if the user swiped to a different pokemon; Since we cache the image shouldn't take that much more CPU.

If scan failed (like for ghastly) we can scan again. Maybe we can make a separate PR for generally rescanning (if CP scan failed and meets certain criteria) at a quicker speed to catch him when he is lower on the screen.

I was thinking that we can use a version of the clipboard designer to design text to be displayed and in addition of having the GoIV button text change, display floating text somewhere at the top of the screen. 

As long as the IV button is showing the text will show, even while scrolling.
When IV button disappears the text should as well.

if scanning failed having ?? sounds good to me, We can also change the color of the GoIV button to let users know that we are at "active scan" mode.

```
    /**
     * setIVButtonDisplay
     * Receiver called from MainActivity. Tells Pokefly to either show the IV Button (if on poke) or
     * hide the IV Button.
     */
    private void setIVButtonDisplay(boolean show) {
        if (show && !ivButtonShown && !infoShownSent) {
            windowManager.addView(ivButton, ivButtonParams);
            ivButtonShown = true;

            Bitmap bmp = screen.grabScreen();
            if (bmp == null) {

                bmp = screen.grabScreen();
                if (bmp == null) {
                    Toast.makeText(this,"no screenshot again?!",Toast.LENGTH_SHORT).show();
                    return;
                }
            }
            ScanResult res = ocr.scanPokemon(bmp, trainerLevel);


            Pokemon pokemon = pokeInfoCalculator.get( corrector.getPossiblePokemon(res.getPokemonName(), res
                    .getCandyName()).pokemonId);
            if (pokemon == null) {
                Toast.makeText(this,"no pokemon found for " + res.getPokemonName() ,Toast.LENGTH_LONG).show();
                return;
            }

            IVScanResult ivScanResult = pokeInfoCalculator.getIVPossibilities(pokemon, res.getEstimatedPokemonLevel(),
                    res.getPokemonHP().or(0),
                    res.getPokemonCP().or(0));
            if (ivScanResult != null || ivScanResult.getHighestIVCombination() != null) {
                try {
                    Toast.makeText(this, "Best IV: " + ivScanResult.getHighestIVCombination().toString(), Toast
                            .LENGTH_LONG).show();
                } catch(Exception x) {
                    Toast.makeText(this,"something calculated wrong for" +  res.getPokemonName() + "/n" + x
                            .getMessage() ,Toast
                            .LENGTH_LONG)
                            .show();
                }
            }
            else {
                Toast.makeText(this,"No result for " +  res.getPokemonName() ,Toast.LENGTH_LONG).show();
            }


        } else if (!show) {
            if (ivButtonShown) {
                windowManager.removeView(ivButton);
                ivButtonShown = false;
            }
        }
    }

```

**Comment by sarav** [comment]
I didn't read the code. But the IV button remaining display when scrolling between pokemon does not mean it's not rescanning when you stop at the new pokemon. There's just some delay between you touching the screen and the rescan happening. Long story short, ignore the fact that the button doesn't disappear -- it'll work fine for all the pokemon if you get it to work for the first pokemon.

As for retrying multiple times -- I'd not want that. GoIV uses to scan every 750ms and that used to kill the battery. We don't want to keep rescanning on fails. And Ghastly will keep failing for many reasons -- the CP could be obscured, the level could be obscured, etc.

I'm not opposed to the a floating text, but the problem is that it would block useful parts of the PoGo UI. The location of the IV button is pretty much the only "free" spot in the UI. If we just display the info in the button, the settings for it doesn't need to be as complicated as the Clipboard template selection. It just needs to be a single choice from a list box or a radio box option list.

**Comment by sarav** [comment]
I made comments on that commit in your branch. The only reason I'm not doing this is because I didn't want to deal with the UI stuff. But I guess I could toast the result and let the UI experts handle the rest.

**Comment by NightMadness** [comment]
Thanks for commenting @sarav!

I wrote the code to to see if there is a direct path to the OCR helper I can utilize without significant refactoring, which there is :smile:. Off-course significant cleanup and refactoring and is needed to make code mature enough for a GoIV PR. 

Toast is definitely good and we have great UI people at GoIV.

**Comment by nahojjjen** [comment]
I did mention the idea of having the IV button show a % indicator - currently many users seem to go through the in game appraisal to see whether the pokemon is trash or worth analyzing - but the appraisal screen is slow. If we could make the iv button show an estimate quicker than the appraisal is, I think we could make tossing pokemon easier for many people.

**Comment by nahojjjen** [comment]
Implemented
