### ISSUE TITLE
Auto scanning the appraisal text

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#589]
I saw some user talk about it on reddit in some old post and @DJCrapsody saying it's not trivial because the app would need a lot of rewrites. But I'd imagine a lot of stuff has been refactored since then. Now that the screen scans are based on touch, we only need to scan the screen for new appraisal text when:

1. The appraisal option is expanded
2. A touch happens.

We could even count the number of touches to narrow down the words to scan for. For example, we can even ignore the first 3 taps (tap menu, tap appraise, tap again to ignore the "I'll appraise Pokemon for you") and then start scanning for wonder/caught/etc. Then the next few taps will be for atk/def/hp. We can even count the total number of taps to figure out the maximum number of atk/def/hp that's the highest IV values.

What's preventing us from doing this as of today?

**Comment by NightMadness** [comment]
Nothing is preventing us from doing this.
We should already have translations of all the phrase in each (or most) of the languages.

**Comment by vmwinckler** [comment]
+1

**Comment by nahojjjen** [comment]
Ive made an unfinished implementation
https://www.youtube.com/watch?v=69sKYoR57SQ

Its currently based on scan intervals (scans every 250 ms), but I believe transitioning it to be touch based would work way better - Ive got several ideas on what to do, just have not done them yet.

**Comment by sarav** [comment]
Perfect! I was just lazy about dealing with the UI updates. I can help with making this touch based if you put up a pull request.

**Comment by nahojjjen** [comment]
added pr #600 

I'm trying to be very careful and add absolutely minimal amounts of code to pokefly... We really need to refactor that.

I think it'd make sense to just add a method "autoAppraise.screenTouched" in pokefly when the user touches the screen, and let the autoAppraise object handle the rest.

**Comment by nahojjjen** [comment]
@sarav are you working on it?

**Comment by sarav** [comment]
@nahojjjen -- no, but I took the day off today to run some errands. I'll try to do this today.

**Comment by nahojjjen** [comment]
There's no stress, just wanted to know if you're gonna do it eventually or if i should look into it.

**Comment by MarcLandis** [comment]
I have a working version that scans on touch. I am still playing around with the delay as the text animation is quite annoying.

**Comment by MarcLandis** [comment]
Here is my version: https://github.com/MarcLandis/GoIV/commit/dc7409f18847f6aa46ac31b071e197e36d47680e

**Comment by sarav** [comment]
Let me try to give it a shot by the end of this year. I think I'll get a few days to work on this. I don't plan on using or needing thread sleeps or new threads. We'll see.

**Comment by nahojjjen** [comment]
We've discussed this a bit in discord, and I used System out prints to see what the actual limiting factors are to the whole ordeal - and we've noticed that the actual ocr module takes around a second to scan, which is difficult to get around.

**Comment by sarav** [comment]
Already implemented by someone.
