### ISSUE TITLE
App starts in russian mode if phone is russian

### ISSUE THREAD

**Issue by nahojjjen** [farkam135/GoIV#59]
Which doesnt work, because Pokemon go isnt released in russia, all names are in english. So the OCR doesnt work - the app should still run the english language or at least ocr english pokemon names until the app is released in russia.

https://www.reddit.com/r/GoIV/comments/4y7bgi/200_released/d6lqei7?context=3

**Comment by farkam135** [comment]
Fixed in commit bde40d6ec75cac33f9f84a18535ffb366a1d6227 will be included in 2.0.1
