### ISSUE TITLE
Automatically update trainer level by stardust OR leveled up trainer detection

### ISSUE THREAD

**Issue by NightMadness** [farkam135/GoIV#590]
Is it possible to reliably figure out the _trainer level_ by the **stardust** and **guessing Pokemon Level** (position on the ARC)?

Is it possible to reliably figure out if user has _leveled up_ on IV scan error by a initiating a **new scan with trainer level +1** and see if it is successful.

Or is #326 still the better option?

**Comment by nahojjjen** [comment]
Stardust gain varies too much based on events and user behavior to be used for estimating exp gain & level. 

>Is it possible to reliably figure out if user has leveled up on IV scan error by a initiating a new scan with trainer level +1 and see if it is successful.

We could do a quick check for if there are results for level  +1, and Toast "Is GoIV and PoGO trainer level in sync?" or something similar to remind the user.

I've somewhat dropped #326 as leveling slowed down tremendously at level >20, and I simply do not encounter the problem often enough to wanna implement advanced scanning techniques. Id forgotten I had issued an issue for the feature though :)

**Comment by nahojjjen** [comment]
Since #326 already exists for automatically updating the level by ocr, and updating the level by estimating exp gains probably wont happen, I'm closing this issue.
