### ISSUE TITLE
3.3.1 Cannot install

### ISSUE THREAD

**Issue by amcsi** [farkam135/GoIV#595]
Trying to upgrade from 3.3.0, it asks my phone to enable unknown installations, it says that the App doesn't ask for any permissions it asked for last time, but then it says something along the lines of "The application wasn't installed" with a grey x to the left of it.

I've also tried uninstalling the old GoIV app and installing GoIV again, but the latest version straight away and I got the exact same issue.

**Comment by amcsi** [comment]
Closing this. Was able to solve this by removing the data from the previous GoIV installation that seemed to have still been lingering, then uninstalling it again.

**Comment by NightMadness** [comment]
you can try the google play version as well https://play.google.com/store/apps/details?id=com.kamron.pogoiv

**Comment by NightMadness** [comment]
Thanks 👍 for closing.
