### ISSUE TITLE
[Request] Guide for getting a build environment ready

### ISSUE THREAD

**Issue by skaforey** [farkam135/GoIV#60]
I know Java very well, but my experience with Android is much lower....it would be helpful if there were some sort of guide for getting the environment setup.

For instance, do you use  Eclipse or Android Studio? Which tools/add-ons (if any) are required.  I would love to start contributing to the project where I can, but I need to have some sort of idea on how to get a build environment setup.

Thanks in advance!

**Comment by nahojjjen** [comment]
What I did:

Download and install Android studio.
https://developer.android.com/studio/index.html

Install the SDK for the relevant android versions from within android studio
(press the sdk manager button in the toolbar, an android face above a box with a down arrow)

Open the project

You might get errors, it either gives you an option to fix, or gives you an error code like "cant find alpha 0.4 etc. This is usually a module which you dont have installed, which you can get through the sdk manager. 

Try to follow these instructions, and when you run into some problem, leave another comment.

**Comment by nahojjjen** [comment]
I'm assuming you know how to use github to get your own branch of the project

**Comment by skaforey** [comment]
Yes, I'm familar with Git and Github.  Thanks for the instructions, I will try it now :)

**Comment by mattaereal** [comment]
I used to build it via cli. But downloading android studio, opening the project, letting the sdk manager to download all the needed modules, and then selecting a hardware profile in which to emulate with a desired android version would do.

I may add it to the FAQ more detailed.

**Comment by sarav** [comment]
I got anroid studio set up and even compiled and loaded the apk. So, compilation works. But compilation takes about 1 whole minute. Seems quite a bit for such a tiny piece of code. I feel like my set up isn't good.

Also, why is it building a debug apk every time and not something similar to what's being released? But I still don't seem to actually be able to "connect" with the app on the phone to allow stepping through it. This is slowing down the experimentation and development a lot!

**Comment by nahojjjen** [comment]
Android studio generates debug apks, not release apks, when you're coding. If you want a release apk, you need to generate one (there's an option for that in the android studio menus.)

Android studio includes  hotswapping, so after the first compile, you can often skip big parts of the compilation as android studio just swaps small parts of your code.

**Comment by sarav** [comment]
Hot swap seems more related to running than building. But as I said, I can't get Android Studio to successfully push and run the apk on device. It gives some error (haven't bothered figuring that out yet)

**Comment by Blaisorblade** [comment]
I've added a PR to put these infos in the repo.
BTW, are there any restriction on which SDK version should I use? I'm using the default, that is the SDK for Android 7.0.

**Comment by nylonee** [comment]
So on this note (somewhat), how are you guys testing the GoIV functionality locally? I imagine you can't exactly pull up the Pokemon GO app within an emulator...

**Comment by Blaisorblade** [comment]
I test with Android Studio+USB cable+smartphone with Pokemon GO on the pokemons I already have. I also use snapshots from master on the go. I'm an Android newbie though, not sure that's the best setup.

**Comment by nahojjjen** [comment]
I run it on my phone

**Comment by mattaereal** [comment]
Running an APK inside an emulator requires patience and way too much cpu usage and ram.

I use the common setup, AS + USB + Smartphone. It deploys automatically the app to your phone, and you can open it for further debugging.
