### ISSUE TITLE
Screenshot method consistently fails to identify Pokemon and HP

### ISSUE THREAD

**Issue by Nincodedo** [farkam135/GoIV#601]
Using screenshots, the Pokemon and their HP are consistently identified wrong. Using screen capture works perfect every time.

http://imgur.com/a/oMVvx

First two are screen capture. Last 3 are screenshot. I am using GoIV 3.3.1 and a Nexus 5X on Android 7.0.

**Comment by nahojjjen** [comment]
should be fixed in #605
