### ISSUE TITLE
Problem with IV calculating after CP changes

### ISSUE THREAD

**Issue by Woo-Cash** [farkam135/GoIV#602]
I have a Metapod, CP 248, HP 72, lvl 22, Appraisal Good (3/4) / Att+HP / 15. It should have IV 15/3/15. Unfortunately GoIV shows me No possible combinations even without choosing appraisal. Level dot is in correct place (I counted). I have quite many Metapods and Nidorans which GoIV can't calculate.

**Comment by nahojjjen** [comment]
reported in #579 and fixed in #583 

Thank you for reporting the issue, but it has already been solved in the dev version, and the fix will be included in the next release.

**Comment by Woo-Cash** [comment]
Oh, sorry, I didn't check closed issues. Thanks for answer.
