### ISSUE TITLE
Problems with scanning

### ISSUE THREAD

**Issue by kkanden** [farkam135/GoIV#613]
I have the option to scan with screenshots set on because if i don't have it on my phone is so laggy that i can't do anything with it (HUAWEI P8 Lite). So if i take a screenshot only cp is scanned correctly and it always says that my pokemon is Alakazam or Onix, HP and candies are not even scanned and its level is not correct. It all started happening after the cp changes update.

**Comment by nahojjjen** [comment]
Should have be fixed by #605 which is included in next release.

**Comment by nahojjjen** [comment]
Will reopen if reports of problem appearing on next build happen.
