### ISSUE TITLE
Move launch delay value to user settings

### ISSUE THREAD

**Issue by voltaek** [farkam135/GoIV#615]
With the latest PoGo update, that game is running more sluggish (for me at least), and taking longer to be ready to use when switching back to the app. The current 3000 value of POGO_LAUNCH_DELAY_MILLIS is no longer sufficient to prevent blackscreen/freezing up PoGo when I start GoIV.

I'd like to see the value moved to a user-adjustable setting so everyone can adjust it to fit their needs. If your phone is faster or if the game gets optimized, users can lower the delay, and vice versa. A slider or number picker in the settings section of the app should work.

**Comment by voltaek** [comment]
I'd like to clarify that while usually I get a black screen, I've also been getting PoGo freezing when starting/stopping GoIV.

Neither of these were happening before the 0.51.0 update, but the black screens were happening before that with an earlier version of GoIV. So basically, GoIV had it solved for short time before 0.51.0 came out.

**Comment by nahojjjen** [comment]
The delay is a pretty hack-y solution (which doesnt even seem to solve all problems) so I dont know if we want to build too much on it.

**Comment by voltaek** [comment]
I still think a solution where we only OCR to do an actual evaluation is the best option. If we can not have whatever running in the background that is breaking PoGo, that would solve the issue, too.

I'm not willing to fully restart PoGo just to scan one 'mon that I caught so I can tell people I'm playing with if they're worth catching, so I've given up with GoIV in it's current state. I've been using Calcy IV which doesn't seem to interfere with PoGo at all (no stuttering/freezing the game on startup/stopping), but its workflow of having to scan, appraise and remember the data, and then leave PoGo to plug in the appraisal info is less than ideal and it's interface is not great. I'd like to be able to switch back to GoIV, but it needs to work without breaking PoGo first.

Calcy IV does use the floating button (a la Facebook Messenger) that I suggested we implement a bit back, which I know isn't the most straight-forward thing to get working (there must be a library we could use?), but I still think best solves the "when to scan" issue and would hopefully further reduce battery life consumption (since we wouldn't be scanning each screen tap).

**Comment by TripSixes** [comment]
In recent days I've stopped and started GoIV numerous times with no Pogo stopping, freezing, stuttering.   The PoGo issues I'm seeing lately all seem to be PoGo only.. I get them even if GoIV isn't running.  Things like the light blue screen and the dark screen after loading is complete.. 

How do we go about finding out what is causing your issues?

I like the idea of having a "battery saving" mode that offers a permanent button with only OCR to check IV.

**Comment by voltaek** [comment]
Okay, so I did a whole bunch of testing, and found some interesting things.

First, if I restart my phone, start up PoGo, and start GoIV, PoGo will full freeze or blackscreen. Every time, no matter what. Tried force stop, clearing cache, and clearing data of PoGo and/or GoIV. Tried full reinstall of GoIV. No dice.

Second, if I start up GoIV first and then PoGo, then GoIV will run and scan as expected, but pausing GoIV from the notification causes a ~5 second full lock pause of PoGo, and will lock up or blackscreen PoGo if you try to restart it from the notification/app.

Third, and this is the interesting bit, is if I have PoGo running, start up Calcy IV (the other app I've been using in the meantime), and perform at least one scan of a 'mon (doesn't work if you don't do a scan, which briefly runs screen sharing), then stop Calcy IV, and go start GoIV, it'll start up just fine. And every time after that, GoIV will start just fine, too, with PoGo already running or not, until I restart my phone. GoIV also doesn't cause PoGo to stutter anymore, and can be paused and restarted from the notification like normally expected.

Now, quick side note: It seems if you swipe GoIV out of your running app tray, the notification doesn't go away and GoIV continues to run. I believe I'd read that swiping the GoIV app away in the tray was supposed to stop the service/notification and all related GoIV things, so this might be a bug we should look into, and might also be somehow related to this weirdness I'm seeing.

Anyways, so I think the place to look at is the screen sharing. Calcy only turns it on for a couple seconds when you tap the floating scan button, and then turns the screen sharing right back off. It seems like something is getting configured, setup, or initialized properly by Calcy that then let's GoIV run correctly afterwards. But whatever Calcy is doing is cleared out when restarting the phone.

And in case you're curious, starting GoIV and then starting Calcy and then scanning with Calcy will stop the screen sharing and even though GoIV is running. Obviously this is not the intended use, but it shows that one can interrupt the other's screen sharing access.

**Comment by TripSixes** [comment]
What version of GoIV do you have at this time?

Also, a disclaimer.. I'm extremely new and green on this project.. so, please take anything that I say with a grain (or maybe a few hundred grains) of salt.

Regarding the notification .. for my version of GoIV, and on my Moto Droid Turbo (6.0.1), I am not able to swipe away the notification.  It is persistent.  Thus, I'm not sure if what you see is expected, or maybe was the way it was in a prior version.. or maybe different phone model/version is allowing it.

I definitely agree that the screen capture / GoIV / PoGo interaction is causing some issues.  I also know that @nahojjjen  has been testing a few things to see if tweaking the start-up sequence will result in a more stable experience for both GoIV and PoGo.

And the information about how GoIV behaves differently after Calcy runs is also quite interesting...

I too have tried to do some extra testing since yesterday.  In addition to GoIV, I've also had a Speedometer overlay app installed for quite some time.  Today, I suspected that "any" overlay might be interacting with PoGo negatively.  I've gone ahead and disabled my Speed app for now, and will continue to test PoGo launching with and without GoIV to see if there are any conclusions to be made.

**Comment by voltaek** [comment]
@TripSixes

I have 3.3.2. And no worries, I've not done any direct development code-wise here as I'm not familiar enough with Java or Android development yet, but I develop in several other languages and platforms professionally, including iOS app development occasionally.

Concerning other overlay apps, I had these same issues before I installed the other overlay app, so I don't think that having it is the root issue. 

In regards to when I was taking about swiping GoIV away, I was talking strictly about the app itself out of the app multitasking view, not the notification. If GoIV is running, I also cannot swipe the notification away until it is paused.

**Comment by TripSixes** [comment]
Thanks..  and about swiping, I gotcha now.  I would agree that swiping away the app should logically stop the service and clear the notification.

**Comment by sarav** [comment]
@voltaek if you just want to check one Pokemon, just start GoIV in screenshot mode for that one time?

**Comment by nahojjjen** [comment]
This issue is no longer applicable, as launch delay has been removed entirely.
