### ISSUE TITLE
GoIV crashes if baby is not detected automatically

### ISSUE THREAD

**Issue by TripSixes** [farkam135/GoIV#624]
It would seem that GoIV crashes whenever the automatic Pokemon detection fails to detect one of the babies.  If the baby name has not been modified, then it seems to detect properly, and calculates IV without issue.  But if there is any name that prevents it from auto-detecting, then GoIV crashes.  This even occurs if the pokemon is guessed wrong (Cleffa guessed as Clefairy) and then correct the Pokemon to Cleffa.

Looking into the code, I can't seem to pinpoint why the results are different depending on whether the auto-detected name is successfull, or if manually corrected by the user.

What "does" work for me every time, is to wipe out any name customization, then run GoIV.  Since GoIV is able to detect the pokemon correctly (without user edit), the IV calculation is successful.

Edit: Furthermore.. the app crashes once again when I go back into the main app and select Stop/Start.  Upon trying to start (after the crash above), GoIV crashes once more.

**Comment by TripSixes** [comment]
After some testing, it appears as though this issue is related directly to the babies and their evolved forms not being connected.  I've updated integers.xml and tested with them connected and the IV Calc works perfectly.  The two I was having problems with before (Cleffa & Igglybuff) now identify correctly.

In addition, if I type Cleffa into the input field, it no longer crashes.

I'll submit the updated integers.xml via pull request tomorrow.  (Added all relevant data for baby devolutionNumber and evolutionCandyCost).

**Comment by nahojjjen** [comment]
Sorry for late reply, for documentations sake, I'll mentioned that this is fixed by #630

**Comment by TripSixes** [comment]
PR #630 merged into master for version 3.4.  Closing this issue.
