### ISSUE TITLE
[Suggestion] Max CP absolute difference display

### ISSUE THREAD

**Issue by suloku** [farkam135/GoIV#629]
Currently GoIV displays the % of perfection for the pokémon compared to a perfect IV pokémon for that species. I find this is not really useful, as different species with the same % have different absolute CP values.

A 0% psyduck for example is a ~84% perfect CP-wise, which might seem missleadingly high. In contrast, seeing the absolute CP difference  for the current selected level (and evolution) would be way more useful and still would fit the screen as only up to 3 characters are needed (since maximum difference should be around 400-500, at least for current max level cap).

For example (I'm making up the numbers), I wouldn't care if my 73% snorlax at level 40 only had 70 CP less than a 100% snorlax at level 40, but I might consider saving my candies for a higher % snorlax if that difference was 200 CP. On the other side, if the species doesn't have substantial CP difference even a 50% pokémon might be worth evolving if you encounter it at a high level.

I don't say to remove the %, but adding the absolute CP difference would be extremely useful in my opinion. Also, it's easy to implement and fits in the current display, so that's why I think this should be added.

**Comment by nahojjjen** [comment]
> Currently GoIV displays the % of perfection for the pokémon compared to a perfect IV pokémon for that species. I find this is not really useful, as different species **with the same %** have different absolute CP values

Im not sure I follow - are you talking about iv% or perfection%?

**Comment by suloku** [comment]
Sorry I didn't make that clear, I'm referring to the "% CP vs max IV" percentage displayed in the advanced information tab. What I mean is that I would find useful that it also displays the actual CP value as the difference between a perfect IV pokémon and the calculated pokémon for the selected level.

I.E., if "% CP vs max IV" is 92% for my dragonite and it corresponds to 3318 CP at level 40.5 and a perfect IV dragonite would have 3607 CP, display the difference between the two: 289.
As you can see, even if my dragonite has a "% CP vs max IV" of 92%, the actual CP difference is pretty substantial, even though 92% seems to be a high value.

Am I making more sense now?

**Comment by nahojjjen** [comment]
I think I understand what you mean now.  I'd like to avoid adding more info to the powerup estimate, to avoid cluttering & the user having to scroll, but I see how adding the numerical difference could be useful.
Could the info be added in a good & clean way on the same row as the % info?

**Comment by suloku** [comment]
On my device and with reference from the other rows, there are enough characters to add it in the same row, this formats would fit with no problem: 

"% CP vs max IV        100% (-0000)"

Also, it mimics the cp and hp gain, which are also shown inside parenthesis. I put a negative sign in the example for character amount, but I'm not sure a sign is needed in this case, but if a sign is used, I guess te minus makes more sense, since anything but a 100% IV pokemon is "worse".

**Comment by nahojjjen** [comment]
#633

Sorry for the slow update, Ive been busy with university the last week
