### ISSUE TITLE
Should swiping GoIV from Recent Tasks stop the Pokefly service?

### ISSUE THREAD

**Issue by TripSixes** [farkam135/GoIV#631]
As mentioned by @voltaek in issue #615 

> It seems if you swipe GoIV out of your running app tray, the notification doesn't go away and GoIV continues to run. I believe I'd read that swiping the GoIV app away in the tray was supposed to stop the service/notification and all related GoIV things, so this might be a bug we should look into, and might also be somehow related to this weirdness I'm seeing.

Opening up this issue for discussion.

Should the Pokefly service (and related notification) be stopped when the user swipes away the GoIV MainActivity from the Recent Tasks?

I dug around a little bit last night to familiarize myself with how it's working today.  Since we have different activities (MainActivity vs Pokefly), the answer to @voltaek's statement above is that the GoIV that shows up in the Recent Tasks is not directly related to the Pokefly service that is started.  Thus, when you swipe away the MainActivity, it is merely calling onDestroy for that activity and not for Pokefly.

Reading many posts and discussions about Android's implementation of the Recent Tasks, swiping things away, apps being Stopped vs apps being Destroyed, .... seems there's no real guarantee that your "onDestroy" will be called if a user swipes away an app from Recent Tasks.

With that in mind, I am testing the addition of some Pokefly service cleanup within the onDestroy of the MainActivity.  So far the change appears to be performing as expected.

    public void onDestroy() {
        LocalBroadcastManager.getInstance(this).unregisterReceiver(pokeflyStateChanged);
        LocalBroadcastManager.getInstance(this).unregisterReceiver(showUpdateDialog);
        LocalBroadcastManager.getInstance(this).unregisterReceiver(restartPokeFly);

        if (Pokefly.isRunning()) {
            stopService(new Intent(MainActivity.this, Pokefly.class));
            if (screen != null) {
                screen.exit();
            }
        }
        TODO: What if !Pokefly.isRunning()?
        super.onDestroy();
    }

If I swipe away GoIV in recent tasks while Pokefly is running, it seems to successfully stop the service (and casting), and clear the notification.  Subsequent launch of GoIV shows the correct state with "Start" being the text of the launch button.

As indicated by the TODO, I'll need to add an else for what to do if Pokefly is not running. ie: clear the Notification.

Comments? thoughts? areas of concern? better way of achieving this?

Thanks!

**Comment by nahojjjen** [comment]
This behaviour seems better than the one we currently have imo, and the method you've posted seems small and neat. I don't know how we want goiv to handle onDestroy when it's not running, do you have any  suggestions?

**Comment by TripSixes** [comment]
I've had this code in my test build for a few days and it seems to be working fine.  I don't think I've added the not running option yet.  Since the service isn't running, I think the only thing to do would be to clear out the notification for the user..  will submit a pull request soon with this change.

**Comment by nahojjjen** [comment]
Sounds good

**Comment by sarav** [comment]
Ah, I came to open this issue. This didn't happen before and looks like it had snuck in again somehow. So, is this fix not in the latest app in the play store? That app seems to be published on Jan 25th and this commit seems earlier than that, but I'm still having this issue where swiping GoIV from recents kills Pokefly.

**Comment by TripSixes** [comment]
The change introduced the kill of pokefly upon swipe away.  It was thought to be what would be expected when swiping the app away from recents.

**Comment by sarav** [comment]
No. We intentionally made the change to not do that. I often do "close all" to kill apps before I start PoGo. Also, Android sometimes kills the Activity (but not Pokefly) when memory is too low. So, tying Pokefly to the Activity kills the service unnecessarily.

Think of it this way -- just because you swipe away gmail doesn't mean it stops downloading new email. GoIV should behave the same way. We used to tie Pokefly service to the Activity a long time ago when we didn't have the "Stop" option in the notification -- because without that there'd be no way to kill the service in that case. After the notification was updated we intentionally removed this behavior.

Could you please revert this change and make a submission please?

**Comment by sarav** [comment]
Reverting this change as the Activity gets killed without swiping on phones with "low" (2 GB) memory.
