### ISSUE TITLE
IV button not appearing on Samsung S3 CyanogenMod13 (6.0.1)

### ISSUE THREAD

**Issue by adam-uk** [farkam135/GoIV#635]
Hello, I use this great app on another device, but I'd really like to get it working on the S3 too.
Happy to provide logs etc if you tell me how to do it. The screenshot/share option works, so that's a start.

Samsung S3 GT-I9305 CyanogenMod13 (6.0.1) 
GoIV 3.3.2

Thanks.

**Comment by TripSixes** [comment]
You might try taking a screenshot and uploading that here, unedited.   From what I understand, the app has many screen profiles that help it detect the expected pixels in the expected locations.. maybe it's just a bit off.

From a fresh install, do you get all the expected permission pop-ups?  Screen overlay, storage, draw over other apps.. 

And lastly, do you get the notification indicating that the service is started?.. even without button appearing?

**Comment by adam-uk** [comment]
I just reinstalled to double check. Yes to 'Allow photos media etc' and allow
drawing over other apps. Press start - 'GoIV will start capturing everything that's displayed on your screen'. Press 'Start Now'...starting...running. The service does start, I can see it in the status bar and notifications.

If PoGo is already running, it turns the screen black like it does on my other device (known issue, but an indication of what's going on)

I've hopefully got the many display optimisations disabled.

![screenshot_20170122-213108](https://cloud.githubusercontent.com/assets/7096262/22186258/bbc52b4a-e0ea-11e6-86d3-4ad344402360.png)

**Comment by TripSixes** [comment]
And just to be sure.. even if you're on the screen, then touch again (not on a button) .. GoIV still doesn't make the button appear?  It scans the screen once per second for 3 seconds to look for matching pixel colors. .. I guess that's assuming that the screen scan service is working as expected to begin with.

**Comment by adam-uk** [comment]
Yep, unfortunately it still doesn't appear.

I have found an app that is able to do screen recording on the play store 'Game Screen Recorder', it shows the familiar message:

'Game Screen Recorder will start capturing everything that's displayed on your screen'. 

That at least suggests the 'display api' is sort of functional (I think).

**Comment by TripSixes** [comment]
Ok.. so, after some pixel-level analysis of your posted screenshot, it would seem that your "white" area is actually a mix of 2 different white pixel colors.  GoIV looks for an RGB of 250,250,250.  Your screenshot has a mix of 250,250,250 and 249,249,249.  The closest pixel that I can find that is 249,249,249 is about 1 pixel off of where I "think" GoIV is scanning your screen (I assume there are margins of error involved in screens/pixels/math-rounding/etc).

I'd like one of the others to weigh in on this, but I think the solution would be to simply add that other white as an alternative "true" value for detecting the Pokemon detail screen.

`    private boolean scanPokemonScreen() {
        @ColorInt int[] pixels = screen.grabPixels(area);

        if (pixels != null) {
            boolean shouldShow =
                    ( pixels[0] == Color.rgb(250, 250, 250) || pixels[0] == Color.rgb(249, 249, 249) )
                            && pixels[1] == Color.rgb(28, 135, 150);
            setIVButtonDisplay(shouldShow);
            return shouldShow;
        }
        return false;
    }
`

**Comment by adam-uk** [comment]
Thanks for looking into this. I would be happy to try a test build with either this candidate solution, or just some logging if possible to see if it's managing to scan anything at all on my quirky sw. Thanks!

**Comment by TripSixes** [comment]
@adam-uk Have you had a chance to update to 3.4 and try it out to see if screen detection is working for you now on CM13?

**Comment by adam-uk** [comment]
I didn't realise it had been updated! I've just tried it but unfortunately it didn't work.  New appraisal feature on my other device is good though!

Any ideas moving forward?

**Comment by TripSixes** [comment]
Darn.  I don't have any ideas.  Others on reddit seemed to report the same thing as you for CM13.

**Comment by sdziengw** [comment]
Having the same problem on an S7 (SM-G930U) running Android 6.0.1. Stock. Will post an image as soon as I can figure out how to do it from my phone... or when I get a chance to sit down at a real computer.

**Comment by sdziengw** [comment]
I forgot to mention I'm running GoIV v3.4.  Here's the screen shot I promised.
![pokemon go_2017-02-07-06-29-29](https://cloud.githubusercontent.com/assets/25609943/22696857/9b5ffa9e-ed1d-11e6-8e25-ac2accfcb21d.png)

**Comment by TripSixes** [comment]
Curious.. any reason why there's no status bar?

**Comment by sdziengw** [comment]
I took the screen shot with samsung game tools.  It cuts the status bar off.  I could post one created using the old power+home button combo if that would be better.

**Comment by sdziengw** [comment]
Old fashioned button press screen shot with status bar.
![screenshot_20170207-102538](https://cloud.githubusercontent.com/assets/25609943/22697610/fbf3ee86-ed1f-11e6-8922-511ef94ccd6c.png)

**Comment by TripSixes** [comment]
Yes, that would be preferred.  GoIV calculates pixel points based off of percentage of entire screen size.

**Comment by sdziengw** [comment]
Posted a proper screen shot above

**Comment by EnviousElitist** [comment]
I'm also having an issue with it appearing.  I'm using a BLU R1 HD with Android 6.0.  

![screenshot_20170218-235803](https://cloud.githubusercontent.com/assets/6107786/23099508/ef37ba04-f636-11e6-999d-7e866c91e09b.png)

**Comment by sdziengw** [comment]
Worked around this on my s7. Turns out samsung game tools was the problem. It prevented go iv from properly locating the level arc.  After I disabled game tools the problemost went away.

**Comment by nahojjjen** [comment]
This issue should have been fixed by the scan-recalibrate feature introduced in 4.0.0

If the issue persists, please open a new issue.
