### ISSUE TITLE
META issue: Gen 2

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#647]
Issues found so far:

- Blissey is not considered an evolution of Chansey. Have to manually search it and pick it for "Check IV" to work.

**Comment by TripSixes** [comment]
Since we didn't have the exact candy cost yet for those evolutions, then they were not linked, so as to not confuse before Gen 2 was actually released.  Now we need to add in all missing candy costs and link all these Gen 1 to Gen 2 evolutions.

The only Gen 1 to Gen 2 that were previously linked were the ones that we already knew candy costs.. such as eeveelutions.

**Comment by TripSixes** [comment]
There also has been some rebalance done.. Lapras is now nerfed.. and no longer calculating accurately,  not sure which others.. I'm sure there's a list somewhere.

**Comment by TripSixes** [comment]
I'm going to try to submit a PR today with updates to base stats, candy cost, evolution links, etc.  
I've found the following, which seems to be accurate based upon the latest game master.
https://battlecalculator.com/pokemon-go/pokemon-go-max-cp-hp

Currently comparing to GoIV current values to see what can be updated.

**Comment by sarav** [comment]
Snubbull/Granbull definitely has some issue. I'm getting -1 as candy cost when I scan a snubbull and the "evolution info" has picked granbull. I don't see any Snubbull or Granbull fixes in the commits you have here. Did I miss it?

Scanned Snubbull's settings: CP 644, HP 82, Level 22 (don't need appraisal to get the -1).

**Comment by sarav** [comment]
Ah, you are only doing Gen1 -> Gen 2. Ok. And I'm guessing you aren't done yet.

**Comment by TripSixes** [comment]
Correct.  Until this update, we had no idea what any of the Gen2 candy costs to evolve would be.  The first PR submitted was just to get the gen1->gen2 links and candies updated.

I'm about to submit a new branch/PR that will build more on the larger Gen2 base stats and candy cost updates that need to be made.

I'm seeing about 8 gen2 pokemon that have at least a 1-digit delta in base stats from current GoIV values (ex: Qwilfish seems to have a defense base stat that is -18 from the current GoIV value).  PR to follow.

**Comment by TripSixes** [comment]
Until I find a verifiable source, I've started a sheet based upon what I've seen from my catches in the game.

https://docs.google.com/spreadsheets/d/1nbJuKqhpd14337ZWrZMFYGW52hS9R0rtPlnDe904r7A/edit?usp=sharing

If you've caught any not on my list, please update.

**Comment by TripSixes** [comment]
The following PRs have been submitted:
#648 - Links the cross-generation pokemon and updates their evolution candy cost.
#649 - Updating base stats based on latest game master.
#650 - Update evolution Candy Cost for all Gen2 pokemon. (still need to confirm a few 'mons)
