### ISSUE TITLE
Not working on Android 6.0.1 with 720x1080 screen

### ISSUE THREAD

**Issue by cbig6464** [farkam135/GoIV#65]
Can anyone please confirm whether this app is working on either Android 6.0.1 or a device with a 720x1080 screen? I get no IV button at all on my Samsung Galaxy Note 2 runnning CyanogenMod 13.0 (Android 6.0.1). I tried it with at least 20 different pokemon. Screenshot mode doesn't work either. The GoIV notification never changes after starting either. I know some coding, so if there's anything else I can do to diagnose this or if anyone can point me to the exact file/function where the OCR might be failing, it will be much appreciated.
![chariz](https://cloud.githubusercontent.com/assets/21017520/17761053/074d0ef6-64d2-11e6-8df3-beab132adb7f.JPG)

**Comment by farkam135** [comment]
I actually have a 720x1280 device i'm testing with (Moto X 1st gen). I'll look into why the IV button isn't showing up, for the screenshot mode where does your phone store the screenshots?

**Comment by cbig6464** [comment]
It stores them into /sdcard/Pictures/Screenshots/Screenshot_YYYYMMDD-HHMMSS.png. Thanks

**Comment by minidmnv** [comment]
I have a similliar problem on my Galaxy S3. The problem might be in 
`mImageReader = ImageReader.newInstance(rawDisplayMetrics.widthPixels, rawDisplayMetrics.heightPixels, PixelFormat.RGBA_8888, 2);
                mProjection.createVirtualDisplay("screen-mirror", rawDisplayMetrics.widthPixels, rawDisplayMetrics.heightPixels,
		                rawDisplayMetrics.densityDpi, DisplayManager.VIRTUAL_DISPLAY_FLAG_PUBLIC, mImageReader.getSurface(), null, null);`

After some logcat analysis, but i'm not sure. I'll try to check this later.

**Comment by cbig6464** [comment]
I may have found the reason this is not working on my phone. The Note 2 has the Mali-400 GPU which is older than what most current phones have. When it renders 3D graphics, it uses a compressed pixel format (probably 16bpp instead of 'true color' 24 bpp). You can see the difference if you look very closely or extremely amplify a screenshot's contrast. 
Here's a darkened screenshot from my phone:
![a](https://cloud.githubusercontent.com/assets/21017520/17786168/a78048e6-6551-11e6-963d-caad7d956e2c.png)
And here's a darkened screenshot from what I assume is a newer phone:
![b](https://cloud.githubusercontent.com/assets/21017520/17786181/b793503e-6551-11e6-8bf4-6300ee4a6523.PNG)
You can see that my phone screenshot has visible dithering artifacts, due to the compressed pixel format output. They are visible in the white information box, and a little bit on the white arc in the top left corner.

So, the first problem may have to do with how the screen is captured. This line of code specifies a pixel format: `mImageReader = ImageReader.newInstance(rawDisplayMetrics.widthPixels, rawDisplayMetrics.heightPixels, PixelFormat.RGBA_8888, 2);` Perhaps for my phone, which renders in a compressed pixel format, a different pixel format needs to be specified in the function call.

The second problem may be the dithering is throwing off the OCR algorithm. In this case the image should be posterized first (number of colors reduced e.g. convert to a 4bpp / 16 color image) to remove the GPU dithering artifacts before processing it.

If there's anything I can do to help diagnose this further, please feel free to ask.

**Comment by farkam135** [comment]
@cbig6464 nice catch, please create a new issue with this as it is different from it just not working on 6.0.1 720p
