### ISSUE TITLE
Skarmory scan returns wrong results

### ISSUE THREAD

**Issue by DanySK** [farkam135/GoIV#654]
I gave a Skarmory a scan. If used without additional appraising information, this result is returned:
![scan](https://lh3.googleusercontent.com/7lQ6jn1_xHvHqbdYjrjO2UR6iXcnaMGbCSNzy1IBkbEb6Ma-JEBxPAuibEusIMoX3JxdCTyG58dCxMELMOCsQ4sCNTLl7gyPxdXGhWY8vH_lwonci2P2ngSOfV7VV2TNzaH-R7apiQicfl3z8JAAnC3IKmDYNIdmTyIygkgMD6ZVtO3Hqgn_yv91xBchSLnZdIA8p-sLklyh_n1MAPxjnY7wEh147pj_ena7cjyUyOfEfzdezg9ktBDNMaY2_DuhOQzLLVj5lGTnRdndXoLXBUWVPAPsIrngbiagnrbAbNYqUCsDFKbgm8CaAESrdu80BIwhX_OMmsjBQs98uaFyJqbjUpAQOW2wa6IldODfOn0wowP2xADsqfUsTtOmpHEDoGBz5MJqg1xIxHRUn10MKE8GFodDJDeZN3G3E2OzjQkAjIu4zuEm09YZh8pbgwsZPAHi9Lujrim6ZSO7CuEg9ILaqQNDLbQPcu4Y3LSwjgxZbIf-MTH4LVquh0-6vv7D2gzrtciVLMLysHcCLcO3Y9X1AEvLeWQ9V-Cr9huy8_KoAQ8lWnO3cnc2OssnCLUVci06tTjneFPnRwG3YcJNru4QwnO_jTSZUyk6Nmy_IMwe1tjwDbCd8fch63tfZdfBfAgmajSzHTSwMNnOuGiEbMTNCSgd-Gy_VssgTbE0-a4=w858-h1525-no)

When correct information about the appraisal is added, however, the scan fails: the former result must be incorrect:
![scan1](https://lh3.googleusercontent.com/FEm1_pt8W5kENfye5mPt2WYidugWnX38jGeHrIODXAh7sxvBRHYJ21W0vmKBnmI0eSr1q04rTJe-joj5pXvvvU_LNgP1fpEn2ETNgryeRqOQ6EuHv-QSP4GSqfwj8ulYzG4l-ls8KoeRl2mb245xclq2AJPCRxMaG2wOZlpfBrWyOoYT0Kpia-8MDOttIkxGY4oK1MQmyJz1BxZbGuIia8ws03AGwQ9AKmnFuCTEikINjlz4mKAI5CSema5snsVcnlRZXZK4M-Sps6laAahgYCrx6f7_GC7LrTEr1VvDyUVQIpD40uZmfjrs40Ersb1kGItiJcgTN8e1O7ul6JhJqucG5l6K5wR4GITZwDEYPEdwvq1KDC5bg29wLh84IYSxe3GJy0Y2-YrpIA-QYd0tZobd9U1yEbIQPs4zfh1HWw1EHL7CQiEnQmy_jONxyhaoWNvR2hm8CuK4Etlhw45QNGwN-mPK6JtaW1J2E44RI7aDD_4tbtlQHqFBVzE0nBBC_aZ9ZOd256lLuN09w2nHi_pmaIPxMFBEnnPkc0c4rqNL1G83b3F4w3YqtZzGoTeMF_6g3WxnHw4LwbcbcXEHvIhhKcRaKYzhuLUxx816QYu2UjO6-jHWGT8wcDWHFzdbk7agJI8PNimsWt6i6ifmPqtClfMLuHytq6xrKVj2XNE=w858-h1525-no)

![scan2](https://lh3.googleusercontent.com/1FatR3MwCdcLWXLrKea3Wji2Dyd1PQIIfatQ6TVsrmCVFCCWwAkBi4-E1bHjF2j6ERnChEqPwZhRobBAZC5IZ0HuMTsFYEp4lOclE-1o1OCrXsqQqupz2fDnhlGQQTrLNTFxUckZFDBlD1tzaSZdHqfz3sY8aeBUX7r0jiwxNoVYfopdztj6THJplcN7rZT145iGsHmvtWLQ6ksCd9oudFnXUC025B_2hsp58f36tLIWT2CiUyUTSxaID72_mXp7jwMaaIvjjb9BaoIGIr91whIOezlF1P5eMZsU1N0jC72Xgsc9NFXoGxljuoQxMcFEDkEYpINm30ij-Mli02n0MSTWWTgxAA2HRDUSiIVH1vZ54ZeTL6A2ADOSRLy_VlaLuu-jDECvX-EGockDC__3F3JN8oZgd8KGakxHkYavfFREOn5V57xe1D6YxtjVizrv_AJfdefPq0EdeyRwL8qDGlumpzY5woANVpw25Z9Sfdsv5EytErq6fKhP05PSJ7PQ9VOCZOWpKT3E7XNf3eXszdMZTFlwjFIjnunHM3MCcroXISfGRmPOPCY7phDurYa80ajHoaElfFJmqfbTRZQU3vKKA2OdAB0s0JYqnU_kSlVvFjqXV9zM_W76WkNOlIa6ZHBG6n6rIdnvxM-aJ-E8KWqMBRVQ2uQd3tnzlPtfB48=w858-h1525-no)

[Link to all the screenshots](https://goo.gl/photos/mz3nbZaVjLjiZcpV9)

**Comment by TripSixes** [comment]
Fixed by #649.  Base stats update will resolve this issue.
