### ISSUE TITLE
Auto appraisal phrases for Italian (and others)

### ISSUE THREAD

**Issue by TripSixes** [farkam135/GoIV#655]
Requested on reddit via:
https://www.reddit.com/r/GoIV/comments/5q6hdl/goiv_340/ddxyl99

This reference post is now 6 months old.. but may be a starting point.  There was a wording change sometime in September/October for English, so some of these translations may be old now.
New Update's Pokemon Appraisal Other Languages

https://www.reddit.com/r/TheSilphRoad/comments/4z5jpx/new_updates_pokemon_appraisal_other_languages/

**Comment by thearaks** [comment]
Auto appraisal is working for italian language and my PR #706 improves it.
I don't know the status for other languages though!
