### ISSUE TITLE
GoIV buggy and game freezes on Pixel XL when triggering GoIV

### ISSUE THREAD

**Issue by endigo9740** [farkam135/GoIV#659]
I'm running a Pixel XL, fully updated on Android version 7.1.1, build NOF26V. Here's my steps to reproduce:

* Start both Pokemon Go and GoIV
* Enter my Trainer Level (29) and team (Instinct)
* Tap "Start" in GoIV
* Receive two toasts for GoIV starting/running respectively

**The following occurs:**
Game freezes (aka all interaction/animation stops like it's a screenshot), the IV button overlay does not appear, notification shows GoIV running.

I am able to get a single IV scan working like this by doing the following:

* Switch back to GoIV and tap "Stop"
* Tap "Start" again, which auto-switches to Pokemon Go in it's frozen state
* (Note: sometimes have to stop/start multiple times before it works)
* Overlay appears with data filled in automatically and calculations work.

However, I'm then unable to interact with Pokemon Go any more and must restart to check another Pokemon.

Please let me know if there's any other information you need, or anything I should test. Thanks!

**Comment by TripSixes** [comment]
Pokemon Go doesn't seem to like the screen overlay service starting or stopping while it is running.  

The short term suggestion I have is to disable the auto launch of Pokemon go, ensure Pokemon go is not running, then start GoIV and wait until it shows running, then finally launch Pokemon go manually.

This should allow Pokemon go to behave normally and the GoIV service running and displaying the button as expected. 

Attempts to resolve the freezing issue are still ongoing.

**Comment by endigo9740** [comment]
This works perfectly, thank you so much! I'm now able to use the app as intended.

**Comment by JayXon** [comment]
I also have this issue, it's quite annoying.
Recently I found out [another IV app](https://play.google.com/store/apps/details?id=tesmath.calcy) that doesn't have this issue, at least for me, maybe you guys could figure out what they did? I think it might because they are not recording at all time, which I think is a good choice because it saves battery life.
But I still prefer GoIV because the UI of that app is a disaster.

**Comment by JayXon** [comment]
I think this is fixed in 3.6.0 (probably same cause as the black screen issue).

**Comment by nahojjjen** [comment]
Yea, this sounds like one of the alternative errors that occurred related to the black-screen issue, which was fixed in 3.6.0. Closing - if the issue appears again, please make a new issue.
