### ISSUE TITLE
Make Pokespam show up only for Pokemon with 12 candies for evolution?

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#661]
I keep Pokespam generally disabled because it makes the UI even more crammed in and adds yet another edit box that I had to fix when I hit the "next/tab" key in the keyboard that pops up when I edit the OCR values before I get the "Done" key.

I was wondering if we should make the Candy count/Pokespam show up only for Pokemon with 12 candies for evolution. I doubt anyone is using Pokespam on those that need 25 candies to evolve (Rattata an exception?).

@NightMadness and others, is there interest in this?

**Comment by NightMadness** [comment]
Sure, ill take a look

**Comment by sarav** [comment]
No, I'm asking if you'd use it in that configuration or not. I'm not suggesting another setting for it. Well, you and others in general. Coding it up myself should be too hard.

**Comment by sarav** [comment]
*shouldn't

**Comment by NightMadness** [comment]
Is there a place to put pokespam that wont cram the ui? 

We can move the "done" button to a diffrent edit box. 

We can also hide pokespam if certain conditions are met.

**Comment by caviyacht** [comment]
I use it all the the time for every type of Pokemon, not just 12 candy ones.  I feel like this needs to be a config switch if you want to only show for 12 candy evolutions.

I will agree that the UI is getting a little crowded.

**Comment by nahojjjen** [comment]
We've made pokefly disabled by default (It's a useful feature, but most of the time / for most users, it's clutter), which decreases the importance of dynamically hiding pokespam.

If anyone has more arguments to add, please comment so I can re-open the issue.
