### ISSUE TITLE
Add movesets info

### ISSUE THREAD

**Issue by Gurvynyk** [farkam135/GoIV#662]
Found some similar issue threads 
https://github.com/farkam135/GoIV/issues/576
https://github.com/farkam135/GoIV/issues/245

And what was the final result ? 

Is it possible just add one more tab (screen / button to call screen) with movesets info for currently scanned pokemon ? 

For example - I have scanned Vaporeon - GoIV shows info for IV and in detailed screen also shows best combination for Attack and link or button to open full list (ordered desc. by DPS) ? 

Lot's of another soft is good but searching / listing some pokemon in another app is way longer then just scan with IV and open exact Movesets list for scanned pokemon.

**Comment by Gurvynyk** [comment]
Also would be perfect to add to CopyClipboard Presets ability to select Attack Range (A / B / C / D) to rename pokemons with best attack with starting A and put them into the list start...

**Comment by sarav** [comment]
As mentioned in the other threads, the biggest problem is keeping it up to date. None of us devs want to manually maintain and edit it. 

I contacted game press for permission to use their data. Didn't get a response.
