### ISSUE TITLE
Incorrect detection of some "baby" evolution lines

### ISSUE THREAD

**Issue by TripSixes** [farkam135/GoIV#667]
Pokemon within the following evolution lines are not being correctly identified when GoIV scans and attempts to figure out which Pokemon it is looking at.

Magby -> Magmar
Smoochum -> Jynx
Elekid -> Electabuzz

The other baby evolutions (Pichu, Cleffa, Igglybuff) do not seem to be affected.

The root cause seems to be that the "getBestGuessForEvolutionLine" method is using the list of "BasePokemons" when attempting to "getNicknameGuess".

    private ArrayList<Pokemon> getBestGuessForEvolutionLine(String input) {
        //candy name will only ever match the base evolution, so search in getBasePokemons().
        PokeDist bestMatch = getNicknameGuess(input, pokeInfoCalculator.getBasePokemons());
        return pokeInfoCalculator.getEvolutionLine(bestMatch.pokemon);
    }

The comment in the code predates Gen2, and thus at that time, it was safe to assume that the candy name would always be the base (or lowest) pokemon in a given evolution line.

With Gen2, Niantic has introduced babies and has not yet updated the candies associated with them (and may never update them).

This issue needs to fix the list of Pokemon that is sent to getNicknameGuess so that it includes all valid "candy" name Pokemons.

**Comment by TripSixes** [comment]
Resolved by #668 

APK with these changes: https://goo.gl/6KsyCo

**Comment by nahojjjen** [comment]
Since #668 was merged Ill mark this as fixed and close
