### ISSUE TITLE
Nidoran♂ not properly detected

### ISSUE THREAD

**Issue by SunMar** [farkam135/GoIV#67]
Hi,

Great app! This is going to save me so much time :).

At first I thought the calculator didn't properly get my stats, but it turns out it doesn't detect the male symbol of Nidoran♂.

![image](https://cloud.githubusercontent.com/assets/8324268/17765868/96cd873a-6528-11e6-89f5-6d13bc2f8469.png)

Here you can see that it incorrectly auto-selects Nidoran♀ instead of Nidoran♂.

My device is a Galaxy S7.

On a side note, is there somewhere information on how GoIV calculates the IV and stats? I was wondering how it determines the min/max for each IV Att/Def/Sta and how it determines the possible combinations?

**Comment by farkam135** [comment]
I'll be working on improving this more. As for the calculation of IV you can check it out in this function https://github.com/farkam135/GoIV/blob/e614236c5d101dace63ba977294bf05f6d44787c/app/src/main/java/com/kamron/pogoiv/pokefly.java#L406-L526

**Comment by SunMar** [comment]
Great! Thank you :).

**Comment by nahojjjen** [comment]
I tried making a fix in #90
