### ISSUE TITLE
Bug: CP vs max IV stat not updating

### ISSUE THREAD

**Issue by aleksre** [farkam135/GoIV#673]
I've identified two bugs related to the '% CP vs max IV' stat.

The first is that the absolute value in parenthesis does not update when using the level slider or changing evolutions, inconsistent with every other stat on the same view. The percentage should obviously stay the same, but the actual CP should increase as the level increases. As it stands, it is also not so clear what this value represents. Is it the difference in CP at the scanned level or at max level? I guess it's at the scanned level?

The second is that the calculation seems to break down at lower levels. My perfect IV Espeon at level 3 is apparently 99.9% (-3) compared to max IV... Screenshot: http://imgur.com/a/BCEpL

After powering up a few times it now shows the correct 100% (0), so perhaps there is a rounding error in the calculation?

**Comment by nahojjjen** [comment]
% CP vs max IV 
Is always based on if your pokemon was level 40, compared to the same pokemon with max ivs at level 40, so the estimation does not change when you change the slider. This is perhaps not intuitive behavior, but its currently the intended implementation. I agree that this is very unclear currently, but it'd very difficult to cram all the information about this in the little space we have. We could discuss if this behavior is really for the best tough. Would it be better to show the difference for every level? When we discussed creating the feature, most people wanted to know how the IVs would affect the potential of the pokemon, not the current value.

The second issue seems to indeed be a bug, but as you said it seems to be a problem with the low leveled pokemon causing a rounding error, I'll look into that, and see if i can find a good solution... However it does not seem to cause very big errors.

**Comment by aleksre** [comment]
I see. I guess that makes sense, but I would argue that having it change according to the level slider like the other stats would be much more useful.  If a level 30 player is trying to decide if he should invest stardust in a high IV pokemon or not they may be interested to know how far away its CP will be compared to perfect IVs at _their_ max level, and not at level 40. Or if you want to compare one high IV pokemon to another lower level, but higher IV pokemon (or similar IV but higher attack), it would be useful to be able to compare them the same level to see how far away each of them are to max CP.

Btw, I think the label '% CP vs max IV' is understandable as it is. I just think it should scale with the slider :P
