### ISSUE TITLE
Missing default string for English

### ISSUE THREAD

**Issue by fireashes** [farkam135/GoIV#678]
warning: string 'clipboard_modifier_add' has no default translation.
warning: string 'clipboard_modifier_description' has no default translation.
warning: string 'clipboard_modifier_edit' has no default translation.
warning: string 'clipboard_modifier_max_evo' has no default translation.
warning: string 'clipboard_modifier_no_token' has no default translation.
warning: string 'clipboard_modifier_scroll_tokens' has no default translation.
warning: string 'clipboard_modifier_tokens' has no default translation.
warning: string 'token_base_stat' has no default translation.
warning: string 'token_base_stat_1stat' has no default translation.
warning: string 'token_base_stat_includeIV' has no default translation.
warning: string 'token_category_IVinfo' has no default translation.
warning: string 'token_category_basicstats' has no default translation.
warning: string 'token_category_evaluationscores' has no default translation.
warning: string 'token_category_pokemonname' has no default translation.
warning: string 'token_category_separators' has no default translation.
warning: string 'token_cp_percentile' has no default translation.
warning: string 'token_cp_perfection' has no default translation.
warning: string 'token_cp_tier' has no default translation.
warning: string 'token_hex_iv' has no default translation.
warning: string 'token_hp' has no default translation.
warning: string 'token_hp_max_lvl' has no default translation.
warning: string 'token_iv_average' has no default translation.
warning: string 'token_iv_maximum' has no default translation.
warning: string 'token_iv_minimum' has no default translation.
warning: string 'token_iv_percentage' has no default translation.
warning: string 'token_level' has no default translation.
warning: string 'token_level_double' has no default translation.
warning: string 'token_level_truncated' has no default translation.
warning: string 'token_max_evo' has no default translation.
warning: string 'token_name' has no default translation.
warning: string 'token_name_length' has no default translation.
warning: string 'token_separator' has no default translation.
warning: string 'token_unicode' has no default translation.
warning: string 'token_unicode_empty' has no default translation.
warning: string 'token_unicode_filled' has no default translation.

**Comment by nahojjjen** [comment]
Is this warnings for the french translation?

**Comment by fireashes** [comment]
Yes. There are some texts that appear in French only. They don't have equivalent in default language

**Comment by nahojjjen** [comment]
Well the warning message says that they're not in use, which wont make the application crash or anything. It does however mean that someone didnt refactor or fix strings properly (might have been me? Though i think someone else altered token strings recently). 

Besides potentially missing some translations, this should not cause any major issue, although the dead text  should still be removed (or reconnected to the proper string connectors).

**Comment by nahojjjen** [comment]
This issue was resolved on release (3.5.0?) I cant remember. It's solved now.
