### ISSUE TITLE
Option to skip refine

### ISSUE THREAD

**Issue by SunMar** [farkam135/GoIV#68]
Hi,

Since GoIV generally detects my Pokemon correctly it might be nice to have an option available that skips the check whether the stats are correct. I'd rather have it immediately pop up with the possible IV's and just show the CP/HP/Pokemon it detected with a button to go back to refine if it's incorrect, rather than first having to tap the Check IV button each time.

**Comment by farkam135** [comment]
This is pretty risky since how would you know if it pulled incorrect data? In most cases you will get no possibilities but if it's off by a couple hp or 0.5 level your IVs might be really messed up. Maybe when a settings menu is added this might not be too bad to have.

**Comment by SunMar** [comment]
Yeah I understand not everyone would want this and is also very much depends on the detection, but as an optional setting it might be nice. If the popup with the calculates also displays the CP and HP it detected I can use that to double check if they're correct. Since they are >90% of the time it'll save an extra step :).

This is a really amazing app!!

**Comment by cdsimpkins** [comment]
try having the "detected" stats at the top of the popup for users with this enabled, and an edit button if the stats are wrong?

**Comment by Blaisorblade** [comment]
If we get settings this could surely be implemented, but many of us are still unhappy with the guessing heuristics.
