### ISSUE TITLE
OCR: 70 / 70HP detected as 7 (Yanma)

### ISSUE THREAD

**Issue by mewio** [farkam135/GoIV#685]
A few times, GoIV has dropped the trailing zero on HP scans. For example, 70 HP would scan as 7. Here's a screenshot of one affected pokemon.

![screenshot_2017-06-04-10-40-52](https://cloud.githubusercontent.com/assets/26984568/26764473/58559a50-491c-11e7-89a8-3ad242a43792.png)

**Comment by mewio** [comment]
The OCR seems to read 38 and 88 HP as 8 a lot of the time, too.

**Comment by nahojjjen** [comment]
The new CP-scanning algorithm in 4.0.0 should solve this issue.

If the issue persists, please open a new issue.
