### ISSUE TITLE
Level arc missaligned

### ISSUE THREAD

**Issue by canavan** [farkam135/GoIV#689]
The current PoGo releases hide the status bar on my phone (Andorid 4.4.2). This results in additional "free" space on the top of the game's screen, that is usually not used efficiently, e.g. the red notification bars are approximately twice as high, but the text is at the bottom. In the details page for the mon, there's additional background above the CP and the level arc. GoIV still correctly detects the level unless the dot is hidden behind the mon. 

Manual adjustment however is somewhat cumbersome, because the position of the arc the red adjustment dot moves on does not coincide with the default position of the in game arc (in the default scroll position all the way up). One can either guess if the horizontal alignment is correct, or attempt to scroll vertically in the game in an attempt to align the arcs.

Possible solutions: 

1 use the initial detection of the arc position for the red dot's arc
2 add up to three helper marks on screen (e.g. arrows/triangles at the ends or the arc and a horizontal line the top of the arc) to assist in finding the correct scroll position so that the arcs lign up.

**Comment by TripSixes** [comment]
A few things here...

Can you provide a screenshot of what you're talking about?   My version of PoGo has no extra space at the top, and has not done anything to remove the status bar.  I saw someone else mentioning that their device supported "full screen mode" and that turning that off would allow GoIV to work properly.

You mention size of Pokemon and provide Togepi and Togetic ... But these two are basically the same size.  The difference I see between then is that Togepi has an evolve button, which pushes the moves and move types off of the screen.  Togetic can't evolve further, so the button is not there which shifts up the moveset info.  

Level Arc.. I think this sounds like a symptom of the extra space issue.  Once I see a screenshot for that I might be able to comment on what is going on with the Arc in your situation

**Comment by canavan** [comment]
>  The difference I see between then is that Togepi has an evolve button.

It just happens that unevolved mon are typically smaller, so my casual check led me to the incorrect assumption that size might be to blame.

Screenshots enclosed. The first one showing the misaligned red dot has been composed from the following ones in Gimp, and while I believe it to be accurate, I cannot guarantee it.

![goiv_arc_missaligned](https://user-images.githubusercontent.com/490051/27762330-489ee972-5e70-11e7-8570-2bf2074c9b40.png)
![goiv](https://user-images.githubusercontent.com/490051/27762328-489dad6e-5e70-11e7-8a74-bd1db9099d96.png)
![togepi](https://user-images.githubusercontent.com/490051/27762326-489d8820-5e70-11e7-9cbd-4ed1ebbad7eb.png)
![togetic](https://user-images.githubusercontent.com/490051/27762327-489da440-5e70-11e7-8fa9-771cca2178fa.png)
![togetic_error](https://user-images.githubusercontent.com/490051/27762329-489de48c-5e70-11e7-815d-8441da1bb497.png)

**Comment by TripSixes** [comment]
Thanks for the screenshots.

What type of phone do you have?

I do not believe that the "hidden status bar" is a result of any change within Pokemon Go.  I think it is a function of a "Full Screen Mode" that your phone/device is enforcing while running Pokemon Go (Gaming Mode?).

If you can find a setting to disable that so that the Status Bar and Navigation Bar show on-screen while running Pokemon Go, then GoIV should be able to scan and align everything properly.

**Comment by canavan** [comment]
I'm stuck with Android 4.4.2 on this phone, I haven't changed any settings and no updates except for Pokemon Go 0.63.4 have been installed as the problem appeared. It's actually a known bug in PoGo:

https://www.reddit.com/r/TheSilphRoad/comments/6fjx83/0634_hides_ststus_bar_for_android/

**Comment by TripSixes** [comment]
Ok.  Thanks for the link.

In that case, there's been some discussion between the devs about adding capability within GoIV to detect the layout/resolution/sizing of the app in a sort of "calibration" mode.  This is still in discussion and not yet to a point for testing.  I think this would help in your case, as long as GoIV were able to adjust it's scan points/etc based upon what you're actually seeing on your screen.

**Comment by canavan** [comment]
Just to clarify again: automatic detection usually works flawlessly, it only fails if the mon covers the dot on the arc, or some white background object (like the bolbs in the screenshot) are on or too close to the arc. Therefore, I'm under the impression that the arc position is already correctly detected, just that the results aren't correctly transferred to the methods/objects that handle manual adjustment.

**Comment by nahojjjen** [comment]
This issue should have been fixed by the scan-recalibration feature introduced in 4.0.0

If the issue persists, please open a new issue.

**Comment by canavan** [comment]
I'd like to test the recalibration feature. I wasn't able to run the developer version, because it kept crashing. I'm on Androif 4.4.2, and therefore run GoIV in screenshot mode. I don't see the re-calibration feature anywhere in  4.0.1. Can you tell me how to activate it?

**Comment by nahojjjen** [comment]
True, you cant use recalibration in android 4. Sorry.

**Comment by thearaks** [comment]
Hi @canavan,
I'm sorry, but the recalibration feature is only available on Android 5.0+.
As far as I know there are very little devices pre-Android 5.0 with "uncommon" screen aspect ratios, therefore, recalibration should not be needed.
Can you please tell me which device are you using?

**Comment by canavan** [comment]
The device is a Kyocera KC-S701 with a 720px × 1280px screen. The problem described here is mostly cosmetic, since the automatic level detection usually works. It's just that when it doesn't work, the fact that the red dot on the display is shown in the incorrect position turns manual adjustment into an educated guess.

**Comment by nahojjjen** [comment]
#782 should have enabled recalibration for screenshot mode. It might potentially solve / affect this problem.

**Comment by canavan** [comment]
I don't see any changes with 4.1.0. Level detection still works as good as it possibly can, but the displayed red dot is still missaligned.

**Comment by thearaks** [comment]
Have you tried with a recalibration?
You can start it from the GoIV notification!

**Comment by canavan** [comment]
In screenshot mode (the only available mode on android 4.4)? Can you provide screenshots or detailed instructions where I could find that notification?

**Comment by thearaks** [comment]
In the latest version (4.1.0) we added recalibration also for screenshot
mode.

Just start GoIV then open a Pokémon (Pidgey is perfect) then pull down the
system notification shade from above and in GoIV notification you'll see 2
icons: press the "rectangle" one.
Then the notification shade automatically close and you can get a
screenshot of your favorite Pidgey.
As soon as the screenshot is taken, the auto calibration will start!

Il 19 ott 2017 10:28 PM, "canavan" <notifications@github.com> ha scritto:

In screenshot mode (the only available mode on android 4.4)? Can you
provide screenshots or detailed instructions where I could find that
notification?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/farkam135/GoIV/issues/689#issuecomment-338028427>, or mute
the thread

**Comment by canavan** [comment]
Thanks. I had seen the new icon, but I actually haven't read the text. It took me 3 attempts to get a successful calibration - the first attempt complained that it was unable to find anything the second was stuck for multiple minutes at "finding the green marker pixel", and the third (and fourth) attempt were quick and spot on. 

The red dot, while prettier than before thanks to the white border,  is still misaligned when refining the scanned data.

**Comment by thearaks** [comment]
Can you provide another screenshot?
Thank you!

**Comment by canavan** [comment]
![goiv-410-misaligned](https://user-images.githubusercontent.com/490051/31794630-43212eba-b523-11e7-8169-ee4174b5b5ff.png)

**Comment by canavan** [comment]
Working correctly on the same phone with 5.0.8 - although that one always crashres on recalibration, therefore, I cannot tell if any successful recalibration may throw off the arc again.
