### ISSUE TITLE
Add auto updater

### ISSUE THREAD

**Issue by jehy** [farkam135/GoIV#7]
Hi! It's really simple to make auto update for your application with github. If you want, you can assign this issue to me and I will make appropriate pull request.

**Comment by coldwaterq** [comment]
Are you going to make it check for a new apk, or a new commit to GitHub? And require the apk to be part of GitHub? I just ask because I was thinking of building a personal version so I don't have to trust others and would like to be notified when I need to pull an update.

**Comment by jehy** [comment]
Checking for a new commit on github won't do any good - user needs the last apk version, not the latest source. If you just want to be notified of source updates, you can  star a repository.

For getting the last release apk on github (best way of updating), you can use gihub api like this: http://stackoverflow.com/questions/34745526/java-get-latest-github-release

**Comment by coldwaterq** [comment]
I didn't realize that was possible. Thanks for teaching me something new.

**Comment by rhari991** [comment]
You can have a look at [this project](https://github.com/rhari991/PokeScanner), it has a working implementation.

**Comment by jehy** [comment]
Yup, auto updater in pokescanner was good. Just checkout the last version just before author deleted all files.

**Comment by rhari991** [comment]
Oh yeah, sorry, I forgot my fork was an older version

**Comment by chuparCh0pper** [comment]
@jehy https://github.com/farkam135/GoIV/releases is live, waiting fro your pull request :wink:

**Comment by pace6666** [comment]
Good idea!!

**Comment by jehy** [comment]
Here's my pull request:
https://github.com/farkam135/GoIV/pull/83

**Comment by jehy** [comment]
Merged!
