### ISSUE TITLE
Google Nexus 5, arc is not aligning automatically.

### ISSUE THREAD

**Issue by Okloks** [farkam135/GoIV#70]
Not aligning automatically:
https://s3.postimg.org/4qbqy8sqr/Screenshot_20160818_162652.png
https://s4.postimg.org/lgvv86sp9/Screenshot_20160818_162705.png

No manual line up:
https://s3.postimg.org/nqtzurn43/image.png
https://s3.postimg.org/72bydz4mr/image.png

1080*1920
Android 6.0.1
Screen brightness adjusting is disabled
Battery saver is off
Player level is correct
Tried to make full factory reset with clean install - no results

On earlier GoIV builds (don't remember, which, maybe 1.2.1) arc worked correctly (that version was with old align icon). But in one day it stopped working.

**I noticed that low CP pokemons autodetect good. If arc is above half, detecting fails, almost always.**

**Comment by nahojjjen** [comment]
I cant see the photos, i get 


404. That’s an error.

The requested URL was not found on this server. That’s all we know.

**Comment by Okloks** [comment]
Fixed links

**Comment by farkam135** [comment]
Is this only the autodetect or if you manually move it does it not line up either?

**Comment by Okloks** [comment]
@farkam135, both
autodetect not working
correct aligning not working => completely defferent results in two nearest arc positions

**Comment by nahojjjen** [comment]
Pokeball icon is trademarked, so it was removed

**Comment by Okloks** [comment]
@nahojjjen, but how? You rebuilded old versions of this app?

**Comment by nahojjjen** [comment]
The existance of the pokeaball icon does not change the underlying logic of the application

**Comment by Okloks** [comment]
I see, this is widespreaded problem.

**Comment by mattaereal** [comment]
Still happens to me on Moto 2nd edition, Marshmallow. Exactly the same. Most of the automatic alignments are done but I have to manually correct the offset. And neither manually correcting will position the red dot over the white one.

**Comment by nylonee** [comment]
On a Google Nexus 5, I don't have the same issue. The arc aligns most of the time, except with things like Gastly where the smoke covers the arc sometimes.

**Comment by Okloks** [comment]
@nylonee, what firmware you have installed?

Just made full factory reset, installed latest Pokemon Go APK and GoIV, nothing changed.
App working incorrectly.

**Comment by nylonee** [comment]
I'm using vanilla Android 6.0.1, same thing as you.

Just wondering, is it happening on all your pokemon, or on just those two? The hypno background looks like it'd mess with OCR a bit, and I know the OCR doesn't work as well on water-type backgrounds

**Comment by Okloks** [comment]
Autodetect works well:
Abra
Bellsprout
Bulbasaur
Clefairy
Dewgong (but shows no possibilities, WTF?!)


Autodetect not works:
Caterpie
Charmander
Cloyster (pokemon overlaps the arc)

**Comment by Blaisorblade** [comment]
Thanks for the reports. I think these all are symptoms of the same issue which we're now tracking as #175. Marking as duplicate.
