### ISSUE TITLE
GOIV no buttons on BLU R1 HD

### ISSUE THREAD

**Issue by shogunnix** [farkam135/GoIV#705]
BLU R1 HD. Installed 3.6, granted all permissions, tried many different settings, button never showed.

![screenshot_20170725-005140](https://user-images.githubusercontent.com/6028211/28557097-8046949a-70d8-11e7-9ee4-ee2a6291a4d5.png)

**Comment by nahojjjen** [comment]
Are you  running in screenshot mode?

Did you give GoIV permission to draw over other applications?

Have you tried restarting your phone?

**Comment by nahojjjen** [comment]
Closing due to lack of response - either way, the screen recalibration feature which will be in 3.7.0 should solve this issue if it's due to a strange screen configuration.
