### ISSUE TITLE
Failed to read CP value: the higher digit gets trimmed more often than not

### ISSUE THREAD

**Issue by thearaks** [farkam135/GoIV#708]
I am using a Xiaomi Mi 6 (1080x1920 resolution) and the game is set to italian language.
So CP is translated as PL.

`OcrHelper.getPokemonCPFromImg` method fails to recognize the CP value correctly.
Since it always trims the first two characters of the OCR'd string, it erroneously removes the higher digit of the CP value if the CP acronym is detected as a single character.
As a consequence, it's often impossible to have a working quick scan, while the normal scans require a manual correction to add the missing digit.
This might have been introduced when the `tess-two` library was updated to v7.0.0.

Here are some examples:

![image](https://user-images.githubusercontent.com/5188791/28739230-90df0b4c-73f9-11e7-97de-9629bba6d69d.png)
Gets OCR'd as **H2976**

![image](https://user-images.githubusercontent.com/5188791/28739134-9df3d318-73f8-11e7-9283-e7a71d8b6eea.png)
Gets OCR'd as **H1193**

![image](https://user-images.githubusercontent.com/5188791/28739218-603a9f42-73f9-11e7-9637-8cca7841df07.png)
Gets OCR'd as **H654**

Sometimes, instead for the character "H", the acronym PL gets mistaken for an "m"!

We need to find some smarter way to clear out the CP acronym from the OCR output since we can't rely on the assumption that tesseract always recognizes the correct amount of characters anymore.

**Comment by TripSixes** [comment]
I wonder if we can just do a regex removal of any non-numerical 0-9 characters.. ?

String value = string.replaceAll("[^0-9]","");

**Comment by thearaks** [comment]
In that method, there's this comment:
```
* Always remove the two first characters instead of non-numbers: the "CP" text is 
* sometimes OCR'ed to something containing numbers (e.g. cp, cP, Cp, c3, s3, 73, 53 etc),
* depending on backgrounds/screen sizes, but it's always OCRed as two characters.
```

I don't know how much of that is still true, since I never had the chance to see the CP letters erroneously read as numbers, but for sure is not true the last sentence: in my case PL is OCR'd as a single character, not 2.

**Comment by nahojjjen** [comment]
I havent checked what things OCR as right now, but I remember that we used to have a method that removed numbers, and it consistently produced errorous result on my S7 as the CP was OCR'd as C7.

Could we maybe make an algorithm that checks the "height" of the characters?
From what i can tell, the "cp" text is always smaller than the numbers, so if we could somehow crop away the cp text by checking the height or something?
