### ISSUE TITLE
add opt-out for crashlytics

### ISSUE THREAD

**Issue by hlplulustg** [farkam135/GoIV#71]
There should be an opt-out opportunity for users regarding crashlytics. Like a checkbox 'use anonymous data for crash analysis' on the start screen with a link to crashlytic's privacy policy below.

**Comment by nahojjjen** [comment]
I agree. Here's a list of things that should be in a settings menu so far:

Auto launch pokemon go on start
Remove screenshots automatically when battery saving mode is active
Bypass input tweaking, show results instantly
Copy range to clipboard after scan
(sub option)Change clipboard copy order
Opt out of anonymous crash reports

**Comment by rpgrca** [comment]
For the copy to clipboard option, I'd like different wildcards. I rename my Pokemon as "85.Eevee" with 85 being the IV average, that way when I sort by number I immediately know which copy of the Pokemon I should evolve or power up, and when sorting by name I know which ones I haven't rated yet. So, in my case I'd find useful being able to set my clipboard to something like "%avg.%name" to get the Pokemon name and formatting done immediately.
