### ISSUE TITLE
Suggestion: allow IV% to be shown as superscript in rename feature

### ISSUE THREAD

**Issue by Reedyn** [farkam135/GoIV#717]
Enable IV% to be shown as suberscript and subscript.

For example **Charizard⁹¹** is much more readable than **Charizard91** and takes up same amount of characters, without using a separator.

**Comment by thearaks** [comment]
I don't have a strong opinion on this, it might be helpful for someone even if it's just a different number formatting.

I proposed a solution in #720 so this can be tested and evaluated.
My current implementation only add superscript numbers to IVPercentageToken but we could think on how to refactor the token system and apply this option to every numeric token.

**Comment by lramati** [comment]
This was merged, so somebody should probably close the issue :)
