### ISSUE TITLE
Some troubles with scan

### ISSUE THREAD

**Issue by braja1718** [farkam135/GoIV#750]
I noticed that the autoscan always identifies male nidoran as the female nidoran, leading to incorrect scans. Also, I noticed that for the level arc, as the ball gets close to the end of the arc (meaning higher level) the autoscan has trouble accurately determining the level of the pokemon. For example, I am level 31 and I have a level 30 tyranitar, but the autoscan thinks it is level 30.5

**Comment by thearaks** [comment]
Hi @braja1718,
thanks for your report!
Level scanning should have been improved in the latest GoIV version (4.2.0) while Nidoran gender detection will be fixed in the next one!
We are currently preparing the release so it won't take long.
