### ISSUE TITLE
Change ExtCPTier from Range AA-ZZ to 99-00%

### ISSUE THREAD

**Issue by fireashes** [farkam135/GoIV#761]
Option to show string name="token_msg_extendedCP" value in (99-00)% instead of AA-ZZ.

This token gives you an idea of how powerful this monster can become, by measuring the maximum possible CP the monster can obtain (considering the maximum possible IV from the scan) and confronting it to the maximum CP of the most powerful IV 100 monster. Values are provided in the AA-ZZ range.

**Comment by DanySK** [comment]
Hi, the ExtCPTier was purposely made in the AA-ZZ range in order to be *way* finer than the 00-99. I can see no good reason to switch to numbers, and I personally am against such change.
It would be better maybe to add another CPTier in 00-99, without changing the current AA-ZZ implementation.

**Comment by nahojjjen** [comment]
If you'd like to continue adding arguments for why the token should be changed, or why a token should be added, please comment so I can re-open the issue. As of now, no discussion is taking place so Im closing the issue.
