### ISSUE TITLE
Crash on calibrate

### ISSUE THREAD

**Issue by Kred88** [farkam135/GoIV#763]
When i click on calibrate, goiv crash. can't use new version v4.0.0 on OnePlus 2

**Comment by thearaks** [comment]
Hi @Kred88,
A bugfix release is coming soon!
Please wait for the new version (probably named 4.0.1) and then report us if the issue persist and, if not, close this issue.
Thank you!

**Comment by Kred88** [comment]
Still waiting for this because can't use anymore your app! :(

**Comment by nahojjjen** [comment]
The crash should have been fixed with 4.0.1. Please comment if the crash persists.
