### ISSUE TITLE
Space no longer allowed in Clipboard configuration

### ISSUE THREAD

**Issue by kirchwitz** [farkam135/GoIV#767]
GoIV allows to customize what goes into the clipboard buffer (intended to set the name of the Pokemon). Besides the predefined items, a "custom separator text" can be entered via keyboard. In previous versions, giving a single space was just fine.

With GoIV 4.0.0, a single space gets rejected (like nothing was entered at all). Spaces are not totally forbidden, they can still be used between other characters, but not for itself. GoIV is running on Android 4.4.4, in case that matters.

Would be really nice to have that feature back again. Thanks a lot in advance!

**Comment by nahojjjen** [comment]
This should have been fixed in version 4.0.1, please comment if it didnt.

**Comment by kirchwitz** [comment]
Space character works great now, thanks a lot for the really quick fix!
