### ISSUE TITLE
Background task crashes on Start

### ISSUE THREAD

**Issue by kirchwitz** [farkam135/GoIV#768]
Running GoIV 4.0.0 on Android 4.4.4, the main app starts just fine, I can set my trainer level, my team and also change Settings. But when I finally hit "Start" to launch the background task, it bails out with "Unfortunately, GoIV has stopped."

The main app still seems to run fine but starting the background task always results in the same Android error condition. Worked fine with GoIV 3.6.0.

There's no other information displayed about what goes wrong. So that's all I can report right now. Please let me know if there's a way to get you more details about why it won't launch properly.

**Comment by thearaks** [comment]
Hi Andreas,
Unfortunately there's a bug that make GoIV 4.0.0 crash on Android 4.4. We're aware of it and we've already written a fix that's included in the next release.
It will be a bugfix release, probably named 4.0.1, and should come very soon.
Thank you for your report!

**Comment by nahojjjen** [comment]
4.0.1 is released. Did it fix your issue?

**Comment by kirchwitz** [comment]
Yeah, the brand-new version 4.0.1 works great! The background process starts fine now and runs as expected. Thank you very much for that amazingly quick solution!
