### ISSUE TITLE
How is the timer task not garbage collected?

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#77]
How does [this timer task](https://github.com/farkam135/GoIV/blob/master/app/src/main/java/com/kamron/pogoiv/MainActivity.java#L367) not end up garbage collected when we return from the onActivityResult() function? All those variables seem like local variables.

The app clearly works. So, I'm very confused.

**Comment by cdsimpkins** [comment]
mProjection is a field of MainActivity, not onActivityResult.

**Comment by sarav** [comment]
The URL isn't correct now due to code updates. I'm asking about the new timer created around that line.

**Comment by cdsimpkins** [comment]
from the [Documentation](https://developer.android.com/reference/java/util/Timer.html)

> After the last live reference to a Timer object goes away and all outstanding tasks have completed execution, the timer's task execution thread terminates gracefully (and becomes subject to garbage collection). However, this can take arbitrarily long to occur. By default, the task execution thread does not run as a daemon thread, so it is capable of keeping an application from terminating. If a caller wants to terminate a timer's task execution thread rapidly, the caller should invoke the timer's cancel method.

**Comment by sarav** [comment]
Ah, looks like Timer has a non-standard behavior. Thanks.
