### ISSUE TITLE
[Request] See potential CP without powering up

### ISSUE THREAD

**Issue by skaforey** [farkam135/GoIV#78]
Right now, it shows what the CP would ble if you powered your current mon all the way to the maximum.

I would like to see what the pokemon would likely be evolved without powering up, not after.  Perhaps this could be one of the options?

**Comment by Paxtez** [comment]
This could also be a low-tech version to narrow down which option is the correct one.

For each possible IV Combo it could show CP/HP After level, so you could level it and then see which combo it is.

**Comment by Blaisorblade** [comment]
This overlaps with #92.
