### ISSUE TITLE
Feature request: trainerlevel cap cp range / max cp range / evolution range  / powerup cost

### ISSUE THREAD

**Issue by hlplulustg** [farkam135/GoIV#8]
I suggest adding the cp ranges at trainerlevel cap, at max level cap and additionally the corresponding ranges after possible evolutions to the results window. Additionally I suggest calculating the powerup cost up to trainerlevel cap and max cap.

Assuming the set trainerlevel is 25 and the identified pokemon is level 21 it would look something like this:

IVs of your lvl 21 [...] can be:
[...]
[...]
[...]
Min: [%] Avg: [%] Max: [%]

CP at lvl 26.5: [...] - [...]
Cost: [...] stardust [...] candy

CP at lvl 40.0: [...] - [...]
Cost: [...] stardust [...] candy

Can be evolved into [...].
CP at lvl 21.0: [...] - [...]
CP at lvl 26.5: [...] - [...]
CP at lvl 40.0: [...] - [...]

Can be further evolved into [...].
CP at lvl 21.0: [...] - [...]
CP at lvl 26.5: [...] - [...]
CP at lvl 40.0: [...] - [...]

**Comment by nahojjjen** [comment]
Looks like this would be a lot of text and take a lot of space, but it would be pretty cool to have this info hidden beneath a "more info" button or something similar.

**Comment by hlplulustg** [comment]
Guys I just figured that I haven't setup anything. Can someone look at my code and check if it's correct? If not maybe use it for implementation yourself :-D

Wrote some lines for CP at cap and max, dust and candy cost at cap and max, and some adjustment to the average value.

In `pokefly.java` in function `private String getIVText()`:

First new variables:

`int sumIV = 0; // new, better average precision`
`int averageSum = 0; // new, better average precision`

`int lowAttack = 15; // new for cp at cap and max`
`int lowDefense = 15; // new for cp at cap and max`
`int lowStamina = 15; // new for cp at cap and max`
`int highAttack = 0; // new for cp at cap and max`
`int highDefense = 0; // new for cp at cap and max`
`int highStamina = 0; // new for cp at cap and max`

`double capScalar = CpM[(int) ((trainerLevel + 1.5) * 2 - 2)]; // new for cp at cap`
`double maxScalar = CpM[(int) (40 * 2 - 2)]; // new for cp at max`
`int cpMin = 0; // new for cp at cap and max`
`int cpMax = 0; // new for cp at cap and max`

Next the inner for-loop is adjusted. `sumIV` is used for a more precise average percentage in the end. When comparing a combination the the single IVs have to be saved for later CP calculation. This has to be done not only when the percentage is lower or higher but also if it equals and the attack IV differs (the weight matters in later CP calculations iirc).


	if (cp == pokemonCP) {
		++count;		
		sumIV = attackIV + defenseIV + staminaIV; // new
		int percentPerfect = (int) Math.round(((sumIV) / 45.0) * 100); // changed to sumIV
		
		if ((percentPerfect < lowPercent) || ((percentPerfect == lowPercent) && (attackIV < lowAttack))) { // changed to account for same % but lower attackIV
			lowPercent = percentPerfect;
			lowAttack = attackIV; // new
			lowDefense = defenseIV; // new
			lowStamina = staminaIV; // new
		}
		else if ((percentPerfect > highPercent) || ((percentPerfect == highPercent) && (attackIV > highAttack))) { // changed to account for same % but higher attackIV + else
			highPercent = percentPerfect;
			highAttack = attackIV; // new
			highDefense = defenseIV; // new
			highStamina = staminaIV; // new
		}
		
		averageSum += sumIV; //changed, more precise than rounded %
		//averagePercent += percentPerfect;
		
		if (count <= 8) {
			returnVal += "\n" + String.format("%-9s", "Atk: " + attackIV) + String.format("%-9s", "Def: " + defenseIV) + String.format("%-8s", "Sta: " + staminaIV) + "(" + percentPerfect + "%)";
		}
	}

The following else clause needs to be adjusted to calculate the average percentage based on the sumIV.

    else {
        averagePercent = ((averageSum / (45 * count)) * 100); // new
        returnVal += "\nMin: " + lowPercent + "%   Average: " + averagePercent + "%   Max: " + highPercent + "%";
    }

Now the `getMaxReqText()` needs a parameter so we can calculate the cost up to different levels. The first check isn't needed anymore.

getMaxReqText() needs a parameter now.

    private String getMaxReqText(double goalLevel) {
        // double goalLevel = Math.min(trainerLevel + 1.5, 40.0); not needed anymore
        ...
    }

Finally the line 

    returnVal += "\nTo max level:\n" + getMaxReqText();

can be replaced by

    // for trainerlevel + 1 cap cp except when trainerlevel is over 38, max is sufficient then
    if (trainerLevel < 38.5) {
        cpMin = (int) Math.floor((baseAttack + lowAttack) * Math.sqrt(baseDefense + lowDefense) * Math.sqrt(baseStamina + lowStamina) * Math.pow(capScalar, 2) * 0.1);
        cpMax = (int) Math.floor((baseAttack + highAttack) * Math.sqrt(baseDefense + highDefense) * Math.sqrt(baseStamina + highStamina) * Math.pow(capScalar, 2) * 0.1);
        returnVal += "\nCP at lvl " + (trainerLevel + 1.5) + ": " + cpMin + " - " + cpMax + "\n" + getMaxReqText(trainerLevel + 1);
    }

    // for max level cp
    cpMin = (int) Math.floor((baseAttack + lowAttack) * Math.sqrt(baseDefense + lowDefense) * Math.sqrt(baseStamina + lowStamina) * Math.pow(maxScalar, 2) * 0.1);
    cpMax = (int) Math.floor((baseAttack + highAttack) * Math.sqrt(baseDefense + highDefense) * Math.sqrt(baseStamina + highStamina) * Math.pow(maxScalar, 2) * 0.1);
    returnVal += "\nCP at lvl " + 40 + ": " + cpMin + " - " + cpMax + getMaxReqText(40);

Would be nice if someone could take a look at the code, I assume there are many errors though :-D
From this point on the class `Pokemon` needs an attribute like `evolution` being 0 or the pokemonnumber he evolves into. With that information the evolution ranges are basically the same as above based on the gives base stats of the evolution #.

**Comment by hlplulustg** [comment]
I actually don't think it's that much space. A scrollable text would be a solution.

**Comment by nahojjjen** [comment]
>From this point on the class Pokemon needs an attribute like evolution being 0 or the pokemonnumber he evolves into. 

issue #24 also needs this field to figure out evolution lines.

**Comment by hlplulustg** [comment]
As I currently don't have a working environment for implementing/testing someone would need to follow up on this. The part above should work (I hope ;-)) for the non evolution cp ranges and costs.

The structure for implementing evolution lookup needs to be in line with #24.

**Comment by nahojjjen** [comment]
Me and hlplilustg is currently working on this over discord
