### ISSUE TITLE
Notification not shown on Pixel XL Android 8.0

### ISSUE THREAD

**Issue by MichaelTong** [farkam135/GoIV#804]
Just updated to 4.1.0, but it seems notification is not working in this version. So I can't do calibration either

**Comment by nahojjjen** [comment]
We've identified the issue, it's due to how oreo handles notification channels. We're working on a fix. #806 might solve it.

**Comment by thearaks** [comment]
Closing the issue since notifications in Oreo has been fixed adding a GoIV notification channel as requested by the latest Android APIs!
