### ISSUE TITLE
All White Buttons

### ISSUE THREAD

**Issue by canavan** [farkam135/GoIV#809]
With 4.1.2, all buttons are white text on white background. Using a Kyocera Torque 701 with Android 4.4.2.
![goiv-buttons-all-white-4 1 2](https://user-images.githubusercontent.com/490051/31855018-806b2606-b6a2-11e7-9c84-f3f4368697d1.png)

**Comment by kirchwitz** [comment]
Same here on Samsung i9305, the background is white and the button text is only some percent darker but still white basically. Very difficult to read. Changing brightness of the device doesn't really help much. Thankfully, from previous versions of GoIV I do remember where the buttons are located and what they mean. But a new user might be somewhat lost.
