### ISSUE TITLE
Bug: GalaxyS8+ Nidoran Female read as Nidoran Male

### ISSUE THREAD

**Issue by rla123** [farkam135/GoIV#812]
GoVI 4.1.2., Galaxy S8+, not full screen, reset scan (on the attached nidoran).

GoIv consistently reads female nidorans as male nidorans. This is NOT a problem on the Galaxy S7 (and presumably every other phone...)

screenshot of a faling nidoran female attached.

![screenshot_20171028-182928](https://user-images.githubusercontent.com/16549338/32139083-2e8ce18c-bc0e-11e7-87ed-3b8b7a223551.png)

![pokemon go_2017-10-28-17-29-51 002](https://user-images.githubusercontent.com/16549338/32139048-3ca30158-bc0d-11e7-8b3e-e4c590f7b05d.png)

**Comment by endigo9740** [comment]
I get the same issue but reversed - males are read as female. Every other Pokemon seems to work except the male nidoran for me

**Comment by thearaks** [comment]
Hi everyone,
Thanks for the reports!
Gender detection has been added in #828, and will be used to correctly recognize male/female Nidoran!
It will be included in the next release.
There are still a couple of features that need to be written and then we'll make a release; you'll need to recalibrate the screen to enable gender detection!

**Comment by nahojjjen** [comment]
Since the gender detection has been remade, Im closing this issue.
