### ISSUE TITLE
Gender in clipboard configuration

### ISSUE THREAD

**Issue by kirchwitz** [farkam135/GoIV#816]
Hopefully I didn't miss an already existing option, but in the clipboard configuration I'd really like to have an additional item that represents the Pokemon's gender, "male" or "female", and something neutral, e.g. a space character, if the Pokemon doesn't have a gender.

I was thinking of something like Nidoran which already supports gender symbols in the Pokemon's name by default. Niantic seems to use the Unicode symbols ♂ and ♀. GoIV might use the same symbols as they are known to work on all devices because they are required for Nidoran.

Reasons for the gender attribute are the evolve process and the Pokedex which encourages all players to catch/evolve all possible genders of each Pokemon towards full completion.

I realize that this is not high priority (for regular game play the gender doesn't matter at all) but some players care about the gender, and this would make a wonderful addition to GoIV which already features a really cool clipboard configuration.

**Comment by nahojjjen** [comment]
We've at some point discussed scanning the gender symbol to make the nidoran scan more accurate, it'd make sense to add gender as a symbol if we do implement a scanfield for the gender symbol.

**Comment by kirchwitz** [comment]
Version series 4.3 (currently installed 4.3.1) now comes with a nice gender token for the clipboard configuration. That's totally great and makes a wish come true! Really thanks a lot for this new feature!

I've scanned some Pokemon, but the gender token always seems resolve as "male", even for female ones (eg, a female Krabby), and also for gender-less like Porygon.

Everything else scans fine (and for me very reliable) as usual. 

I'm running Pokemon app on Android 4.4.4 (Samsung) which is quite old. Maybe the layout is a little different depending on Android version. If it is helpful to provide you with a screenshot or additional device information please just let me know what you need. I'm always happy to help.

**Comment by thearaks** [comment]
Hi @kirchwitz thank you for your feedback!
Have you run screen calibration after upgrading from 4.2.x to 4.3.x?
It is needed to better detect the gender symbol area!
Let me know if it helps,
Mattia

**Comment by kirchwitz** [comment]
Just to be sure, I've re-done the screen calibration several times with different Pokemon, and it always looks very accurate, especially the area with the gender symbol has been correctly recognized (indicated with properly positioned red box). I saved the results and stopped the background process and then restarted it as per the instructions. I guess there's not much room to do it wrong. :-)

Calibration only fails if the Pokemon cannot be evolved into anything (eg, last or none evolution) but I guess that's normal because there's no evolution information to be scanned.

As far as I can tell there are no problems scanning all the other information (type of Pokemon, level, CP, health etc.) to calculate IV values.

It's just that the gender is always recognized as male. Or maybe it's scanned correctly and only the new Gender placeholder (Basic Stats) for the clipboard configuration somehow gets the result wrong?

**Comment by thearaks** [comment]
Hi @kirchwitz,
I tried on my test devices and the gender gets detected correctly with GoIV 4.3.1.
Could you please post here 3 screenshots (one for each gender and another for no gender) uncompressed (PNG format) and in their original resolution?
I also need the exact smartphone model.
Then I'll be able to set up some automated tests to run the code against your specific case!

**Comment by kirchwitz** [comment]
Yes, of course, I'll try to post the three images here, all taken by the device "as is" (unmodified). The smartphone model is a Samsung Galaxy S3 LTE (GT-I9305), Android 4.4.4 (by Samsung), screen resolution is 720 x 1280 pixels (16:9 ratio, ~306 dpi). If you need more information or want me to test something just let me know.

![makuhita_female](https://user-images.githubusercontent.com/832928/34456364-7b68f97a-ed94-11e7-8cda-c17ec7b9e647.png)
![makuhita_male](https://user-images.githubusercontent.com/832928/34456365-7b8784ee-ed94-11e7-82ac-1dc879985b5f.png)
![porygon_genderless](https://user-images.githubusercontent.com/832928/34456366-7ba2a13e-ed94-11e7-8e02-e72d2aa85c57.png)

**Comment by thearaks** [comment]
Hi @kirchwitz,
thanks to your help the gender detection will be improved in the next release.
Thank you very much and happy new year!
