### ISSUE TITLE
Error with the 3rd powerup on Lvel 37

### ISSUE THREAD

**Issue by JoseLSegura** [farkam135/GoIV#817]
The last update of PokemonGo bring the possiblity to power-up the Pokemons to level 40. In order to get the L38 still able to power-up his Pokemons to the new maximum, Niantic has enable a third power up on the level 37.

After the 3rd power up is performed, the Pokemons are not propertly detected by GoIV because the "point in the arc" go further the theorically possible.

In other word, before the update a level 37 trainer only can power up his Pokemon to level 38.5. Now, he can power up to level 39.

**Comment by nahojjjen** [comment]
This should be fixed in 4.3.0

Create a new issue or comment here again if the issue persists.
