### ISSUE TITLE
Unable to scan Eevee 32,5 level as 31 level trainer

### ISSUE THREAD

**Issue by gradha** [farkam135/GoIV#819]
Hi, the scanner is having trouble with high level Eevees for me, which might be a result of the recent weather update. My level is 31:

![01](https://user-images.githubusercontent.com/101927/33796661-710077f2-dcf9-11e7-990b-34e3655e43c3.png)

I found an Eevee which reports as 32.5 and the level dot seems incorrectly placed.

![02](https://user-images.githubusercontent.com/101927/33796664-7e9286ee-dcf9-11e7-8cc1-028902d7c6b7.png)

On the other hand, normal pokemons scan fine:

![03](https://user-images.githubusercontent.com/101927/33796667-86603c2c-dcf9-11e7-8ab9-deae1e02c879.png)

**Comment by nahojjjen** [comment]
The dot seems to be incorrectly placed on higher levels ever since niantic updated so you could level your pokemon 2 levels higher than your trainer, instead of 1.5.

Could you test this apk https://drive.google.com/open?id=1p31CzvFfNsGaByfQgbrHD7VL5Nps6UXl and see if it solves it for you?

**Comment by gradha** [comment]
The APK matches better the dot but for some reason is still unable to calculate IV values for this pokemon. Trying manually to reduce the level and recalculate IV fails too, as if this particular Eevee is out of its expected range.

![2017-12-09 20 44 22-2017-12-09 20 46 47](https://user-images.githubusercontent.com/101927/33798943-471579dc-dd22-11e7-8ace-de91068f81a3.png)

**Comment by ravemir** [comment]
Same here, but I'm level 29, trying to scan level 31.5 Pokémon. Increasing level to 31 gets a scan, but only if I don't use appraisal improvement.

Going to test the new APK to see if it helps.

**Comment by ravemir** [comment]
Nope: just like @gradha, dot placement is better, but still doesn't return a rating.

Is there anything else I can do to help?

**Comment by nahojjjen** [comment]
#822 tries to give a possibility to scan pokemon thats "outside range".

When a pokemon is caught in weather, it seems to be able to be higher level than a trainer can manually power up a pokemon. In that case, the actual level is higher than the level-arc dot can show. So the eevee might be higher level than 33. The #822 branch allows you to manually select any level between 1-40.

**Comment by gradha** [comment]
Before resorting to manually selecting the level, maybe it would make sense to automatically try each level increasingly until a valid match is found, and if so, display the result with the disclaimer that the pokemon level is above the trainer's level and thus can't be detected accurately.

**Comment by pkiel** [comment]
I have the same problem with the dot. Sometimes GoIV tells me that a wild Pokémon is level x.5.
The dot is not placed correctly. The following pictures are made of a wild-catched Venonat.

This is what GoIV suggest to me:
![image](https://user-images.githubusercontent.com/21021281/33967194-b88ec850-e062-11e7-8f35-32412b529fe1.png)

This is the real level after manually press the minus button:
![image](https://user-images.githubusercontent.com/21021281/33967201-bf108358-e062-11e7-83ad-3828f0a8fa70.png)

This is my calibration screen:
![image](https://user-images.githubusercontent.com/21021281/33967239-e8b92b24-e062-11e7-818b-3c24b8aa5993.png)

Phone: Huawei P9 lite
Trainerlevel 37.

**Comment by pkiel** [comment]
Update to my problem:

I found this link in the subreddit: https://www.reddit.com/r/GoIV/comments/7j5wm4/running_into_issues_when_scanning_higher_level/dr4mkpj/

This version helped me to fix my problem. Thanks.

**Comment by thearaks** [comment]
Hi @pkiel,
Have you installed the latest version (4.3.1)?
It should include the fixes for this issue.
If you can confirm it's solved, please close this issue, thank you!

**Comment by pkiel** [comment]
@thearaks Looks good and seems to be fixed! Thanks a lot and I wish you a happy new year.

P.S. I cannot close it :)

**Comment by thearaks** [comment]
Happy New Year to you!
I'm closing it ;)
