### ISSUE TITLE
Every mon is Alakazam or Mew since 4.3.2

### ISSUE THREAD

**Issue by Head0r2k18** [farkam135/GoIV#851]
After updating to 4.3.2 every monster is seen as Alakazam or Mew.
It also doesn't enter the HP or candy

Trying to recalibrate displays following errors:
Unable to locate gender
Unable to locate candy name
Unable to locate candies amount
Unable to locate evolution cost
Unable to locate power up stardust cost
Unable to locate power up candy cost

![screenshot_20180116-111330](https://user-images.githubusercontent.com/35487515/34983657-8ec762a0-faae-11e7-8184-189150e67fac.jpg)

**Comment by thearaks** [comment]
Hi @Head0r2k18, have you tried recalibration with a Pidgey instead of a Bulbasaur?
The results are the same?
Have you sent an email to the developers with the recalibration error report through the app?

**Comment by Head0r2k18** [comment]
I did in fact report through the app. However I didn't use a Pidgey for calibration and now its working fine. I would have never guessed this does matter since i tried other non-evolved monsters.

Issue will be closed.
