### ISSUE TITLE
Move ratings

### ISSUE THREAD

**Issue by celandro** [farkam135/GoIV#864]
Move ratings would be really useful to help users choose which moves are best.

I can provide an implementation that works against a static set of data (downloaded at release time). The exact format of this data is really up to you.

Id suggest letter grades generated based off the Best Attack Movesets and Best Defense Movesets from this page:

https://www.pokebattler.com/pokemon/names/BLISSEY/levels/30/opponents/levels/30/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=OVERALL&weatherCondition=NO_WEATHER&view=GROUPED&dodgeStrategy=DODGE_REACTION_TIME&seed=1512696886801

compared to the max overall scores from these pages:

https://www.pokebattler.com/rankings/attackers/levels/30/defenders/levels/30/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=OVERALL&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME

https://www.pokebattler.com/rankings/defenders/levels/30/attackers/levels/25/strategies/DEFENSE_RANDOM_MC/DODGE_SPECIALS?sort=OVERALL&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME

Note that for defensive scores, you need to invert the overall rating as the pages are intended to show different things.

**Comment by nahojjjen** [comment]
For documentations sake, this is getting discussed in the discord channel, and we're aiming to add in move ratings for the 5.0.0 release.

**Comment by nahojjjen** [comment]
Move ratings are added, although the feature should be expanded in the future
