### ISSUE TITLE
IV button pressed wrong ends up in crash/hang.

### ISSUE THREAD

**Issue by mattaereal** [farkam135/GoIV#89]
If you press the IV button when you moved/scrolled just even a bit the pokemon screen you want to check out, it kinda hangs, and disappears for following use. If you go back to the app and press stop, it crashes.

**Comment by mattaereal** [comment]
Another scenario is when you just transferred a pokemon, open nother one, and click the button for IV calc without waiting for the "Transfer complete" to disappear. Anything that involves not being able to have a clean view.

**Comment by nahojjjen** [comment]
It sounds like the integer parse issue that causes crashes if the ocr finds "" as a string, Ive solved that in #75.
