### ISSUE TITLE
Back button missing on results screen (to go back to scan correction dialog)

### ISSUE THREAD

**Issue by jamesl1001** [farkam135/GoIV#898]
I downloaded the latest 5.0.0 update and it looks great! The inclusion of the move sets is a nice addition. Good job!

The only issue I have is that the Back button has gone from the results screen to go back to scan correction dialog.

I have the "Enable scan correction dialog" and "Expanded appraisal opened by default" options switched off so that the results screen shows immediately.

In 4.3.3 I can then tap the Back button to go back to the scan correction dialog and/or appraisal dialog, however in 5.0.0 I cannot.

Thanks!

**Comment by thearaks** [comment]
Fixed in 5.0.1!
