### ISSUE TITLE
'Expanded appraisal opened by default' shouldn't override 'Enable scan correction dialog'

### ISSUE THREAD

**Issue by JayXon** [farkam135/GoIV#903]
If 'Enable scan correction dialog' is set to false and 'Expanded appraisal opened by default' is set to true.
in 4.x it will show iv directly
in 5.0 it will show appraisal first

I set it this way because I want a result right away and if I need to further nail it down I hit back and do appraisal, level and cp are usually correct so the scan correction dialog is rarely used.

**Comment by thearaks** [comment]
This should be fixed in 5.0.1 that was release some minutes ago.
Could you please test the latest version and let us know if the problem persist?
Thank you!

**Comment by JayXon** [comment]
5.0.1 fixed it, thanks!
