### ISSUE TITLE
Can't turn off movesets tab

### ISSUE THREAD

**Issue by Agilo3** [farkam135/GoIV#908]
Hi,

I don't see an option for disabling the Movesets tab. Could this be added?

Thanks!

**Comment by nahojjjen** [comment]
Hey, why do you want this option?

**Comment by Agilo3** [comment]
It's not useful information for me, as I mainly use Gamepress for moveset info when I need it. It's just bloat to me. Being able to turn it off saves an extra tab space on top too.

We're also able to turn off other features like evolve count, or are able to adjust behavior like automatically opening the appraisal screen by default. An extra toggle for turning off the moveset info tab doesn't seem like an overly big request. 😄

**Comment by thearaks** [comment]
Unfortunately it's harder then it might look from the outside.
It would require a change to the settings (update the key-values definitions, update the translations for the preference title and description), adding the logic to avoid loading the moveset data and avoiding using it everywhere it is used at the moment to avoid nasty crashes (scan result UI, clipboard rename string generation, ...), and the scan result UIs shoud be changed accordingly to remove the tab.
In my opinion it's a medium-difficulty task, with lower priority compared to other tasks we have to implement...

**Comment by nahojjjen** [comment]
Im closing this issue, I understand why you want it, but unfortunatelly the downsides are bigger than the pros.

The freed up tab-space would not give you anything but more blank space, which is aestetically pleasing, but not valuable enough to warrant the added code complexity for handling another possible UI combination.
