### ISSUE TITLE
Tweak to the helper text 'can be evolved into ...'

### ISSUE THREAD

**Issue by Paxtez** [farkam135/GoIV#92]
It seems like it would be more useful to show the CP of the evolved version at it's current level, instead of (or in addition to) the CP at it's max level.

I think the question 'if I evolved this, how strong would it be?' would be a much more common than 'if I evolved this and then upgraded it to my max level, how strong it would be?'

Especially since you can evolve it, and then check it again to check it's max CP.

**Comment by nahojjjen** [comment]
The entire result screen needs a visual overhaul, im working on sketches.

**Comment by nahojjjen** [comment]
Here's the latest sketch I did:
http://imgur.com/a/dRv5J

**Comment by Paxtez** [comment]
That looks good to me! The only thing I see missing is the number of combinations.  Maybe 'Click to see X combinations' or something.

**Comment by rpgrca** [comment]
What I liked from the original version was that it didn't cover the Pokémon image, so it was a nice way to share to people who couldn't identify them by name. Wish it was back somehow.

**Comment by Paxtez** [comment]
The growth section is supposed to be collapsible, more images they made:

http://imgur.com/a/VIbQU

**Comment by rpgrca** [comment]
Would like the name to be fully visible as well, but that one looks fine enough if it's not possible.

**Comment by farkam135** [comment]
Included in #162
