### ISSUE TITLE
Level arch missaligned v2

### ISSUE THREAD

**Issue by FloppyKing** [farkam135/GoIV#921]
https://github.com/farkam135/GoIV/issues/689

I'm experiencing a very similar issue to the issue linked above, but it appears to be in an opposite direction from that issue since my arch is too low instead of too high.  I'm on Android 6.0.1 and PoGo 0.101.1 and GoIV 5.0.3, so unlike above I CAN recalibrate and the calibration marks the arch position correctly.   Automatic scans seem to be detecting the correct level, but when I have to make manual adjustments for Pokemon that cover the arch the red dot indicator doesn't line up to the in game arch.  It's like the arch position is shifted down by the height of the black bar shown on the top of the calibration image.  This makes it very hard to correctly set level when manual adjustments are required.

**Comment by FloppyKing** [comment]
Successful calibration image:
![screenshot_2018-05-08-10-41-23](https://user-images.githubusercontent.com/26074248/39768617-76da1cc4-52af-11e8-8553-df217cd495fd.png)

Arch minimum:
![screenshot_2018-05-08-10-45-27](https://user-images.githubusercontent.com/26074248/39768625-81d7d684-52af-11e8-8272-dcdb822de744.png)

Arch maximum:
![screenshot_2018-05-08-10-45-22](https://user-images.githubusercontent.com/26074248/39768662-97e83a40-52af-11e8-93ac-2db8ef0543b5.png)

Actual level position:
![screenshot_2018-05-08-10-45-59](https://user-images.githubusercontent.com/26074248/39768676-a2d9c77a-52af-11e8-8b24-2ecb57f6367b.png)

Not that I AM scrolled all the way up.

**Comment by FloppyKing** [comment]
Can't it use stardust required for leveling up to do level calculation when arch isn't visible?

**Comment by Jaap-Jan** [comment]
Seconded. With v5.0.3, calibration seems succesful, but detected level circle does not align with the actual level and GoIV cannot detect the monster's name and quick scan almost always shows '?'. This is a regression over 4.3.3.

**Comment by FloppyKing** [comment]
yeah i was getting frequent '?' in my quick scans, but i assumed it was a separate issue.  Having not tried recent previous versions of GoIV i assumed it just didn't perform well.  I had since switched to CalcyIV since the big draw for me using GoIV was the quick scan and it didn't seem to work reliably.  I'm still holding out hope that these issues can be resolved so i can give GoIV another chance.

**Comment by kribjo** [comment]
Level arc scan failing here too with 5.0.3. I just came from 4.3.3 where I had no problems. Now I just get ? mark scans and have to manually adjust the arc. Though it looks like it is set just right, but if I bump it 0.5 levels (for the handfull of 'mons I've tested) so it displays a bit off it works like it should.
I have recalibrated several times, with no problems detected.

**Comment by fredkilbourn** [comment]
getting this issue too on my note 3

**Comment by FloppyKing** [comment]
I just tried v5.07 since it got added to app store and I'm not getting the frequent ? In quick calc, but the arc for manual adjustments is still misaligned, so must have been separate issues.

**Comment by Jaap-Jan** [comment]
Both issues seem to be fixed for me with v.5.0.8. Quick Scan works and the arc is no longer misaligned.

**Comment by FloppyKing** [comment]
I agree.  This can be marked as resolved.
