### ISSUE TITLE
Quick scan add to exports

### ISSUE THREAD

**Issue by doeiqts** [farkam135/GoIV#924]
I love that there's the export option to PokeBattler on the move tab, but I'd love to be able to export more quickly by having an option to have every Pokemon that is quick scanned to be added to the export queue. 

This way I can just do a search in Pokemon Go and then quickly swipe through all those Pokemon to have them added to the export queue.

**Comment by nahojjjen** [comment]
Ive added it to the backlog as a plausible feature to add.
