### ISSUE TITLE
Add Alolan Pokemon

### ISSUE THREAD

**Issue by ThiefOfBagEnd** [farkam135/GoIV#925]
With the recent release Alolan Exeggutor, it's obvious the slightly different stats of Alolan Pokemon are not programmed into GoIV causing incorrect IV calculations or the complete inability to calculate IVs for Alolan Pokemon.

**Comment by ThomasMldr** [comment]
Game version 5.0.6 works for me, uploaded about an hour ago.

**Comment by ThiefOfBagEnd** [comment]
Yeah new version works great. I'll close the issue

**Comment by AlbertCalvet** [comment]
Mine still isn't working on 5.0.7. I read on the reddit channel that there were some issues with locales. Mine is set to Spanish, FWIW.
