### ISSUE TITLE
Changing Share Button + Arc is slightly off.

### ISSUE THREAD

**Issue by EmteeAK** [farkam135/GoIV#928]
So I have a couple problems. I have a Samsung Galaxy S5.

1) I went to share (The "<" with 3 dots on it looking thing) from the app and it prompted me where I want to share to and I chose Discord. I just wanted to try it out and now I can only share to Discord. I have Re-Installed and Cleared the App Cache/Data from my phone and it still defaults me to Discord. Is there a way I can share to somewhere else?

2) Here are some screenshots. https://imgur.com/a/FUxGsHb
The arc for checking IVs are always below where it should be. For most of my pokemon the app does a good job estimating the lvl gauge, but I have ran into a situation where I had to guess multiple levels to determine the IV. I have recalibrated multiple times and nothing has changed.

**Comment by nahojjjen** [comment]
For 1. 
How to clear the default apps is different between different android versions and phones, but you should be able to google "how to clear default app samsung s5" and your android version to clear it. Its usually somewhere under settings -> apps. We're just using the normal android share api, so we dont have any control over how the OS/phone maker has decided to handle defaults.

For 2, this issue has a thread here: #921 , so I'm closing this as a duplicate. Thanks for your feedback!
