### ISSUE TITLE
Clipboard doesn't work

### ISSUE THREAD

**Issue by Limero** [farkam135/GoIV#932]
I just started using GoIV and it's great, but I can't get the clipboard feature to work.
"Copy smart nickname to clipboard" and "Show clipboard preview popup" is enabled, so I can see what is supposed to be put in the clipboard, but nothing is put there when I paste. CalcyIV's similar feature works as intended.

I'm using the latest version from the Playstore (5.0.7) on a OnePlus 5T running LineageOS 15.1. I have tried disabling privacy guard without any difference.

**Comment by nahojjjen** [comment]
Are you attempting to paste clipboard names after quick-scanning the pokemon, or pressing the iv button?

We've disabled clipboard info on quick-scans because it became too spammy (among other problems), so you need to press the iv button and 'ok' for the information to be put on your clipboard.

**Comment by Limero** [comment]
That does work. The description about the setting should however be clearer about that. "Automatically add scanned information to your copy & paste clipboard." sounds like it's done without any button presses.

Is there any way to detect when the keyboard is opened? Because the nicest solution would probably be to put it in clipboard when the "Set Nickname" screen is up or the keyboard is open. Renaming with the current solution is too cumbersome, requiring button in bottom left corner to be pressed, "Check IV" to be pressed, the window closed with X and then you can rename.

**Comment by BarbaraHeck** [comment]
Would it be possible to make this optional as to whether or not the quick scan goes to the clipboard?

**Comment by nahojjjen** [comment]
I've made a change that rephrases the english formulation on the setting, and added a toggle to enable clipboard copying on both iv previews and scans, which might be included in the next update.
