### ISSUE TITLE
Issue Scanning HP of 80

### ISSUE THREAD

**Issue by ThiefOfBagEnd** [farkam135/GoIV#938]
Scanning pokemon generally works, except when the pokemon has an HP of 80. It fails to scan the HP and I have to enter it manually.

**Comment by nahojjjen** [comment]
Could you supply some more information, such as your device resolution, what resolution you're playing PoGO with (lowered resolution with samsung gametuner?). A screenshot could be helpful.

**Comment by ThiefOfBagEnd** [comment]
Device Info
Phone: Samsung S7 Edge
Android: 7.0 Nougat
Resolution: 1280x720 (720p)
Resolution for Pogo: 720p (and game tuner is a flaming piece of garbage imo)
GoIV version: 5.0.7
PoGo version: 0.105.1
But I've noticed it on previous version of PoGo and GoIV.
I'll try to get you a screenshot shortly.

**Comment by ThiefOfBagEnd** [comment]
Here's a SS:

**Comment by ThiefOfBagEnd** [comment]
It looks like system font size and resolution might play a role.  When I increase the font size or resolution. The issue is resolved.

**Comment by canavan** [comment]
I have that problem too. It seems to occur only, but consistenly with HP=80. Using Android 4.4.2 on a Kyocera TC-S701, with a 1280x720 screen.

**Comment by ThiefOfBagEnd** [comment]
@canavan see the post above from @thearaks. At 720p the ppi  (pixel density) is too low for OCR (image recognition) to work reliably . Try a higher resolution or bigger font setting. I'm closing the issue because there's nothing the developer can do about the OCR library he's using, other than change it, but this is hardly a reason for that. Also I meant to close it weeks ago, but I just forgot.
