### ISSUE TITLE
2.1.0: Frequent crashing and less usable than prev version (6.0.1 on Note4)

### ISSUE THREAD

**Issue by Eric678** [farkam135/GoIV#94]
v2.1.0 crashes every 2-3 scans when I hit the IV button. Also when the scan fails it is almost always interference with the CP value, and to manually fix, the active touch area is now tiny, and need to get exactly at the end of the bad string, and then the edited field is covered up by the popup numeric keypad so one cannot see what one is typing.  Much larger touch sensitive area and pre-blank the field would be much more user friendly.  Had to go back to v1.3.0 as its only problem for me was a double hit on any key caused a crash - much less frequent!
Great app - would like power up IV refine.  Many thanks.

**Comment by farkam135** [comment]
Hopefully @nahojjjen got those crashes fixed in his last commit.
