### ISSUE TITLE
bug: name3 appraisal is correct but becomes evolved name when copied to clipboard

### ISSUE THREAD

**Issue by rla123** [farkam135/GoIV#940]
Galaxy S8+, GoIV 5.0.7 downloaded from Play store.

GoIV appraises correctly. However, if I set Name3 instead of Name5 I get the Evolved name copied to the clipboard instead of the correct unevolved name

E.g. appraise Kra[bby] becomes Kin, Mag[ikarp] becomes Gyr, Fee[bas] becomes Mil

Works fine if I use Name 5.

I have rebooted, reinstalled, cleared cache, etc. Its very repeatable. but interestingly not 100%of the time.

Thanks

p.s. how about adding Name4 in addition to 3 and 5

**Comment by nahojjjen** [comment]
Almost every clipboard token exist in two variants, one evolved, and one unevolved. You can toggle between them with one of the buttons in the clipboard ui. (Star? Crown? Cant remember)

Have you made sure that you didnt have that toggle on when you created the clipboard setting?

**Comment by rla123** [comment]
Yes, you are absolutely correct. I had no idea what the star key did and didn’t knowingly use it.

 

Sorry for wasting your time.

**Comment by nahojjjen** [comment]
While the problem you reported wasnt real, it's still an indication that the UI / hinting of the evolution type clipboardtoken is not clear enough.
