### ISSUE TITLE
Store pokemon stats

### ISSUE THREAD

**Issue by americodls** [farkam135/GoIV#95]
Would be nice to have the possibility of store stats obtained from GoIV and get snapshots of individual pokemons stats.

I think that would need an ID to monitor different individuals of the same specie. 

Maybe changing the name of pokemons would the work.

I have an `Clefable` and change her name to `Clefable.Z3` where `Clefable` is the original name of the pokemon and the `Z3` is the unique identifier that allows identify the pokemon as an individual.

So, we can monitor the evolution through the time of our favorite pokemons and generate statistics.

**Comment by nahojjjen** [comment]
I'd like a more fleshed-out sketch of the feature you're suggesting, I don't really understand what the result you're asking for would look like.

**Comment by rpgrca** [comment]
Maybe he wants something similar to what this spreadsheet offers?  https://docs.google.com/spreadsheets/d/1wbtIc33K45iU1ScUnkB0PlslJ-eLaJlSZY47sPME2Uk/copy

**Comment by americodls** [comment]
Yeah. I want store a history of my monsters. I will draft some diagrams and
mockups to be more clear.

Em 20 de ago de 2016 15:51, "rpgrca" <notifications@github.com> escreveu:

**Comment by farkam135** [comment]
Closing, don't think we will be getting in a store feature anytime soon, right now a lot of people seem satisfied with renaming and we have been working hard to make renaming the go to option of being organized.
