### ISSUE TITLE
Arc misalignment

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#96]
I'm interested in fixing arc misalignment issues, but the code that calculates arc math has some magic values. Where do they come from?

Given the max possible pokemon level, is the arc not evenly split across all possible levels (and +.5 ones)? If it is, getting the arc to align properly shouldn't be an issue at all. If it's not evenly split, is there some documentation someone can point me to on how the math is done between the angles to levels?

**Comment by farkam135** [comment]
it's not evenly split it's based on the CpM. Right now the issue seems to be coming from an inconsistency in trainer levels so from level 20-29 you subtract the degree by 0.5, from 30-? you add 1 degree, and from the screenshots i have seen if looks like 1 degree is also added to trainers level 10-19? This is what i'm currently looking into but I need more info on trainers and whether or not their arc is properly aligned, I was actually going to start a google forms for this. Since this theory is completely busted if a level 15 trainer comes out saying the arc is perfect while another says it's misaligned.

**Comment by sarav** [comment]
I feel like there's some radius or arc center error too. Maybe floating point rounding errors? The red dot moves farther out from the center if I take it to the higher pokemon levels and aligns well with the arc when I take it to the lowest level.

**Comment by farkam135** [comment]
With images I received from users I was able to check the formula for arc center and radius with the following resolutions:
1. 1440x2392
2. 1440x2560
3. 1080x1776
4. 1080x1920
5. 540x960
6. 720x1184
7. 720x1280
8. Just in the last commit 480x800
If there is a resolution not listed above it has not been tested but is probably a rounding issue and just needs to be adjusted by 1.

**Comment by sarav** [comment]
Mine is 720x1280. Trainer level is 25. Problem was also there for level 24. Here are example screenshots.

![minlevel](https://cloud.githubusercontent.com/assets/247061/17829906/348ee47e-6672-11e6-9c53-8eff5ccf19af.png)
![maxlevel](https://cloud.githubusercontent.com/assets/247061/17829905/348f00f8-6672-11e6-84fa-a1954591ff22.png)

**Comment by farkam135** [comment]
That looks fine, how does it look aligned over the pointer?

**Comment by sarav** [comment]
Look at the circle on the 2nd picture. See how it's off center from the arc line? Compare it to the first pic. The center of the red dot lines up with the arc line nicely. It's not a huge issue, but it lacking the polish and it should be fixable. I think it's floating point arithmetic error. If you can explain some of the constants in the code, I might be able to take a look.

**Comment by farkam135** [comment]
I believe that's more of a red dot size issue, the formula I believe was pulled from the game files but if you reference a line i'll let you know if it's a constant I know of. Heading to bed now but i'll check it out in the morning!

**Comment by mattaereal** [comment]
I went from 16 to 17 without having the arc aligned. I have always had to position the arc one point before the real arc of the pokemon in order to get some data.

**Comment by sarav** [comment]
The red seems fine on the left, so I think it's not the size of the read dot. Going to the constants, [in this line](https://github.com/farkam135/GoIV/blob/3abdf1b18fc8bea84c64cf0910a5c7125d61e020/app/src/main/java/com/kamron/pogoiv/MainActivity.java#L302), where does 0.094 and 202.037116 stand for?

I understand the CpM[pokelevel] / CpM[trainerlevel] is deciding how far the arc should go while taking into account the uneven scaling as the pokemon levels up. But I don't get those two constants. Actually, I'm even more confused about the CpM values. Nevermind.

**Comment by farkam135** [comment]
The CpM values were pulled from the game. The 0.094 is the first multiplier (CpM[0]), I just pushed a commit to use CpM[0] instead. As for where the 202.037116 came from, i'm not entirely sure. I'm playing around with it to see what that could be.

**Comment by Blaisorblade** [comment]
In #152 @Remiscan identifies a root problem and proposes a promising solution.

**Comment by farkam135** [comment]
Closing move discussion to #152 since there is a proposed solution.
