### ISSUE TITLE
Move Sets do not take in account "Same Type Attack Bonus"

### ISSUE THREAD

**Issue by esauvisky** [farkam135/GoIV#960]
The move set lists don't consider *Same Type Attack Bonuses*, which in turn makes some pokemons with Best Offense movesets appear like they are worse than they could be.

Good example is _Arcanine_, see example below:
![image](https://user-images.githubusercontent.com/18354658/43044220-cdc6de56-8d78-11e8-861b-6ffcd5b711e8.png)

**Comment by nahojjjen** [comment]
Hmm, we get all moveset information from pokebattler simulations, so there's nothing we can change in the code to fix this; I'll ask celandro about it.

**Comment by thearaks** [comment]
I think that Pokebattler score already takes in account of STAB but, since it is based on the performance of a moveset against the Pokémon best opponents, a move without STAB could still be better on those opponents.
We need celandro confirmation ayway!

**Comment by celandro** [comment]
It certainly does take into account bonuses.

Attacker move ratings are calculated by how well Arcanine does against the top 24 defenders as a gym clearer.

 Defender move rankings are based on how well Arcanine does vs. the top 5 best Arcanine counters.

Wild charge is one of the best moves in the game and it's not resisted by many of the top 24 defenders.

**Comment by celandro** [comment]
A raid specialist rating might be what op is looking for where having the same type makes more sense.
