### ISSUE TITLE
Lucky Pokémon

### ISSUE THREAD

**Issue by ThomasMldr** [farkam135/GoIV#962]
Not recognized when it is a Lucky Pokémon, part of the data is shifted down.

**Comment by Presac** [comment]
Dust being halved might would probably be a problem too.

**Comment by Ultraboss77** [comment]
I have a lucky meltan, it is recognized as but can not be rated !

**Comment by mokahless** [comment]
Wasn't this issue fixed a while back? Why is it still open?

Pretty sure the Meltan issue is unrelated to it being lucky and about 10-20% of my Meltan aren't calculated properly.
