### ISSUE TITLE
Clipboard renaming token for appraised & unappraised

### ISSUE THREAD

**Issue by RudeySH** [farkam135/GoIV#978]
I'd like to be able to add a symbol to the clipboard output based on whether the Pokémon is appraised. Being able to use a different symbol for unappraised is a must for me too.

CalcyIV has an icon for appraised but not for unappraised.

**Comment by nahojjjen** [comment]
I think this is a good idea, lemme see if I can do something like this...

**Comment by nahojjjen** [comment]
Okay yea, seems possible. What symbol would be good to indicate non-appraised/appraised?

**Comment by RudeySH** [comment]
Ideally the symbol could be configurable by the user. I'd like to use a question mark for unappraised. Using an exclamation mark for appraised seems like the perfect fit, being the opposite of a question mark, but that symbol might already have a different meaning. CalcyIV uses § (section/paragraph symbol) for appraised.

**Comment by nahojjjen** [comment]
why'd you have to suggest the alternative that takes most effort on my part :(

Ive added it to my  'todo' batch for various clipboard QOL improvements.

**Comment by AbcentMineDead** [comment]
My suggestion would be:

§ = Appraised
¿ = Unappraised

**Comment by AbcentMineDead** [comment]
I personally add a custom symbol in the front of "multiple results" clipboard output. This works for me as I'm not interested in the use of an appraised token. If you do similar with "single" and "perfect" the need of a token wouldn't be necessary. I could be wrong.

**Comment by nahojjjen** [comment]
Ive added a "isAppr" token in the "IV info" list which does what's originally requested in this issue thread.
