### ISSUE TITLE
Update for gen IV ?

### ISSUE THREAD

**Issue by shrx** [farkam135/GoIV#989]
GoIV does not recognize the newly added gen IV pokemon.

**Comment by Scaredycatinc** [comment]
Have you guys got an ETA on the gen iv update?

**Comment by nahojjjen** [comment]
#991 adds support for gen IV, I'll try to push it out as an update asap.

**Comment by Scaredycatinc** [comment]
Love LOVE your work thank you!!

**Comment by ravemir** [comment]
It's out already, so we can close this?

**Comment by Scaredycatinc** [comment]
Go nuts. This was sorted ages ago.

**Comment by ravemir** [comment]
'Fraid I can't, just suggesting. :)
