### ISSUE TITLE
Not working on Sony Z3 Compact with Android 4.4.4

### ISSUE THREAD

**Issue by danielcha** [farkam135/GoIV#99]
I tried both version 2.0 and 2.1. But it doesn't seem to be working for me. I'm not getting the IV button.

- I disabled Flux (for tinting and dynamic brightness) or do I need to remove it?
- I have no idea how I can find out if I have a faulthy screen capture API. Running the stock Sony Android flavor
- I granted permissions when installing
- I have other apps that draw over apps and work fine 

How to go about troubleshooting what's wrong?

Android version 4.4.4.

**Comment by nahojjjen** [comment]
Android 4.4 does not have the screen capturing API, so the only mode you should have available should be the battery saver mode.

The battery saver mode activates when you take a screenshot, it never shows the IV button.

**Comment by sarav** [comment]
And I think the latest released implementation of the battery saver mode isn't working on Xperia phones. It should be fixable I hope/think. It used to work partially before. Don't worry, there's a feature coming where you can share a screenshot while GoIV is running and that might work if nothing else.

**Comment by danielcha** [comment]
So should I be able to select the battery saver mode? It's showing me a grayed out, checked, checkbox. I made a screenshot and nothing happened. I guess that's because @sarav is stating it's broken om Xperia phones.

Would it work if I upgrade my Android version? Or would I still have issues because I have an Xperia phone?

**Comment by sarav** [comment]
No, you are seeing that because it's checking that box for you and doesn't want to allow you to uncheck that box. Because batter saver mode is the only one that's compatible for your phone/android version.

If you upgrade to Marshmallow (or maybe Lollipop) it would work as is too (you can uncheck the battery saver mode).

**Comment by danielcha** [comment]
I upgraded to Marshmallow. Works like a charm now! Can be a bit buggy, but I'm loving it!

Just to confirm: the screenshot power save mode is still broken on my Xperia. But I don't mind, I prefer to check all my IVs at once after a good hunt :-)

You guys are awesome

**Comment by danielcha** [comment]
Been postponing that for ages... also seems alot snappier!

**Comment by farkam135** [comment]
Closed. Fixed after update.
